import type { N1Module } from "../niveau1/types";

/** Niveau 3 — Module 3 : Intelligence artificielle avancée et intégration responsable. */
export const MODULE_3: N1Module = {
  code: "N3-M3",
  slug: "module-3",
  num: 3,
  title: "Intelligence artificielle avancée et intégration responsable",
  subtitle:
    "Du prompt expert à la gouvernance : concevoir, auditer et intégrer l'IA générative au service de l'ingénierie professionnelle.",
  duration: "22 heures · 2,5 semaines",
  finalite:
    "Maîtriser l'IA générative avancée au service de l'ingénierie professionnelle : prompt engineering expert, assistants, workflows, évaluation critique, gouvernance éthique et protection des données.",
  objectives: [
    "Distinguer les familles d'IA générative et leurs usages : texte, image, code, multimodal.",
    "Concevoir des prompts experts et des chaînes d'instructions structurées.",
    "Construire un assistant ou un agent IA adapté à un besoin professionnel.",
    "Auditer et fiabiliser une production d'IA : biais, hallucinations, erreurs factuelles.",
    "Appliquer un cadre éthique, juridique et de protection des données à l'usage de l'IA.",
  ],
  competences: [
    { group: "Gouvernance & données", text: "C21 — Gouverner les données personnelles et garantir un usage éthique du numérique et de l'IA." },
    { group: "Compréhension de l'IA", text: "C22 — Expliquer l'IA générative avancée et ses limites." },
    { group: "Conception", text: "C23 — Concevoir des prompts experts et des chaînes d'instructions." },
    { group: "Audit & fiabilisation", text: "C24 — Évaluer, auditer et fiabiliser de façon critique les productions d'IA." },
    { group: "Intégration professionnelle", text: "C25 — Intégrer l'IA dans l'ingénierie pédagogique et la production professionnelle." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Comprendre l'IA générative avancée",
      icon: "Sparkles",
      blocks: [
        { type: "text", html: "Les outils d'IA générative produisent du <strong>texte</strong>, des <strong>images</strong>, du <strong>code</strong>, de l'audio ou des analyses de documents à partir d'instructions. Ils ne « savent » pas au sens humain : ils produisent des <strong>sorties probables</strong> à partir de modèles et de contextes. Cette nuance est indispensable pour éviter la confiance aveugle." },
        { type: "callout", tone: "warn", title: "Éviter la confiance aveugle", text: "Une IA ne consulte pas une vérité : elle prédit une suite plausible. Une sortie convaincante n'est pas une sortie vérifiée. Au niveau 3, la posture professionnelle repose sur la vérification systématique." },
        { type: "text", html: "L'IA avancée devient utile lorsqu'elle est intégrée dans un <strong>processus contrôlé</strong> : définition du besoin, fourniture du contexte, choix du format, vérification des sources, correction humaine et documentation de l'usage." },
        { type: "infographic", kind: "categories", title: "Familles d'IA générative et usages", data: { columns: [
          { title: "Texte", accent: "#6D5DF5", items: [{ label: "Rédaction de contenus" }, { label: "Synthèse de documents" }, { label: "Reformulation, traduction" }] },
          { title: "Image", accent: "#0891B2", items: [{ label: "Illustrations" }, { label: "Schémas, visuels" }, { label: "Maquettes" }] },
          { title: "Code", accent: "#16A34A", items: [{ label: "Génération de scripts" }, { label: "Correction de bugs" }, { label: "Explication de code" }] },
          { title: "Multimodal", accent: "#D97706", items: [{ label: "Texte + image" }, { label: "Analyse de document" }, { label: "Audio, vidéo" }] },
        ] } },
        { type: "callout", tone: "tip", title: "Point d'attention du formateur", text: "Faire verbaliser la logique de choix par les apprenants. Au niveau 3, la compétence ne se limite pas à appliquer une procédure : elle consiste à expliquer, ajuster et justifier une décision professionnelle." },
        { type: "infographic", kind: "steps", title: "Intégrer l'IA dans un processus contrôlé", data: { steps: [
          { title: "Définir le besoin", text: "objectif clair et public visé" },
          { title: "Fournir le contexte", text: "données utiles et contraintes" },
          { title: "Choisir le format", text: "structure de la sortie attendue" },
          { title: "Vérifier les sources", text: "faits et références" },
          { title: "Corriger humainement", text: "la responsabilité reste humaine" },
          { title: "Documenter l'usage", text: "traçabilité et transparence" },
        ] } },
      ],
    },
    {
      id: "seq-2",
      title: "Prompt engineering expert",
      icon: "Wand2",
      blocks: [
        { type: "text", html: "Un <strong>prompt expert</strong> précise le rôle, le contexte, la tâche, les contraintes, le format de sortie, les critères de qualité, les exemples et parfois la méthode de vérification. Il évite les demandes floues et <strong>encadre la production</strong>." },
        { type: "infographic", kind: "categories", title: "Anatomie d'un prompt expert", data: { columns: [
          { title: "Cadrage", accent: "#6D5DF5", items: [{ label: "Rôle", hint: "« Agis comme concepteur pédagogique »" }, { label: "Contexte", hint: "public, situation, objectif" }, { label: "Tâche", hint: "ce qui est précisément demandé" }] },
          { title: "Encadrement", accent: "#0891B2", items: [{ label: "Contraintes", hint: "durée, ton, longueur" }, { label: "Format de sortie", hint: "tableau, plan, liste" }, { label: "Critères de qualité", hint: "objectifs observables" }] },
          { title: "Fiabilisation", accent: "#16A34A", items: [{ label: "Exemples", hint: "illustrer le résultat attendu" }, { label: "Méthode de vérification", hint: "auto-contrôle demandé" }] },
        ] } },
        { type: "text", html: "La <strong>chaîne d'instructions</strong> (prompt chaining) découpe une tâche complexe en sous-tâches : analyser, proposer un plan, produire, vérifier, améliorer, générer une grille. Cette approche réduit les erreurs et rend le processus plus transparent." },
        { type: "infographic", kind: "steps", title: "Une chaîne d'instructions", data: { steps: [
          { title: "Analyser", text: "comprendre le besoin et les contraintes" },
          { title: "Proposer un plan", text: "structurer avant de produire" },
          { title: "Produire", text: "générer le contenu" },
          { title: "Vérifier", text: "repérer erreurs et incohérences" },
          { title: "Améliorer", text: "corriger et enrichir" },
          { title: "Générer une grille", text: "outil d'évaluation final" },
        ] } },
        { type: "callout", tone: "example", title: "Amélioration d'un prompt", text: "« Fais-moi un cours sur Excel » devient : « Agis comme concepteur pédagogique pour un public adulte débutant ; propose un module de 3 heures avec objectifs observables, activités pratiques et grille d'évaluation. »" },
        { type: "callout", tone: "tip", title: "Point d'attention du formateur", text: "Faire verbaliser la logique de choix : pourquoi ce rôle, ce format, ces critères ? Le prompt expert se justifie, il ne se devine pas." },
      ],
    },
    {
      id: "seq-3",
      title: "Assistants IA et workflows spécialisés",
      icon: "Bot",
      blocks: [
        { type: "text", html: "Un <strong>assistant IA spécialisé</strong> est configuré pour un métier ou une mission : assistant de conception pédagogique, assistant de révision de syllabus, assistant de génération de quiz, assistant d'audit de livrable. Sa valeur vient de ses <strong>consignes stables</strong>, de ses critères et de ses limites explicites." },
        { type: "infographic", kind: "two-columns", title: "Ce qui fait un bon assistant spécialisé", data: { left: { title: "Atouts", subtitle: "un cadrage documenté", items: ["Objectif précis et tâches délimitées", "Consignes stables et réutilisables", "Critères de qualité explicites", "Limites clairement posées", "Exemples de sorties corrigées"] }, right: { title: "Dérives à éviter", subtitle: "un assistant non maîtrisé", items: ["Accès libre à toutes les données", "Aucun critère de qualité", "Prompts secrets non documentés", "Tâches floues et illimitées", "Aucune vérification prévue"] } } },
        { type: "text", html: "Un <strong>workflow IA</strong> combine plusieurs étapes et parfois plusieurs outils. Par exemple : collecte d'un besoin par formulaire, synthèse IA, production d'un plan, génération d'un tableau, vérification humaine et envoi d'une note." },
        { type: "infographic", kind: "steps", title: "Exemple de workflow IA", data: { steps: [
          { title: "Collecter le besoin", text: "via un formulaire" },
          { title: "Synthèse IA", text: "résumer les données" },
          { title: "Produire un plan", text: "structurer le livrable" },
          { title: "Générer un tableau", text: "mettre en forme" },
          { title: "Vérification humaine", text: "contrôle de qualité" },
          { title: "Envoyer une note", text: "diffusion finale" },
        ] } },
        { type: "callout", tone: "tip", title: "Point d'attention du formateur", text: "Faire verbaliser la logique de choix : un assistant utile est un assistant borné. Sa fiabilité tient à ses limites, non à sa puissance." },
      ],
    },
    {
      id: "seq-4",
      title: "Évaluation critique et fiabilisation",
      icon: "ShieldCheck",
      blocks: [
        { type: "text", html: "Une réponse d'IA peut contenir une <strong>erreur</strong>, une <strong>source inventée</strong>, une <strong>généralisation abusive</strong>, une formulation biaisée ou une information périmée. L'<strong>audit critique</strong> consiste à vérifier les faits, repérer les contradictions, croiser les sources et corriger le contenu." },
        { type: "callout", tone: "warn", title: "L'hallucination", text: "Une hallucination est une erreur ou une invention présentée comme plausible. L'IA peut produire des contenus faux mais convaincants — c'est précisément ce qui la rend dangereuse sans vérification." },
        { type: "infographic", kind: "table", title: "Défauts fréquents d'une production IA", data: { columns: ["Défaut", "Signe d'alerte"], rows: [
          ["Hallucination", "Affirmation précise sans source vérifiable"],
          ["Source inventée", "Référence introuvable ou incohérente"],
          ["Généralisation abusive", "« Toujours », « jamais », sans nuance"],
          ["Biais", "Formulation orientée selon les données ou le cadrage"],
          ["Information périmée", "Date ou contexte non actualisés"],
        ] } },
        { type: "text", html: "La fiabilisation exige une posture <strong>méthodique</strong> : identifier les affirmations vérifiables, chercher des sources de référence, supprimer les éléments non justifiés, signaler les incertitudes et conserver la <strong>responsabilité humaine</strong> de la décision." },
        { type: "infographic", kind: "rules", title: "La méthode d'audit", data: { rules: [
          { icon: "Search", title: "Isoler", text: "Repérer chaque affirmation vérifiable." },
          { icon: "BookOpen", title: "Sourcer", text: "Chercher une source de référence fiable et datée." },
          { icon: "Scissors", title: "Élaguer", text: "Supprimer les éléments non justifiés ou douteux." },
          { icon: "AlertTriangle", title: "Signaler", text: "Indiquer clairement les incertitudes restantes." },
          { icon: "UserCheck", title: "Décider", text: "La responsabilité humaine reste centrale et finale." },
        ] } },
        { type: "callout", tone: "example", title: "Une statistique sans source", text: "Si une IA affirme une statistique sans source : isoler l'affirmation, demander ou chercher une source fiable, vérifier la date et le contexte, puis reformuler avec prudence ou supprimer l'affirmation si elle n'est pas vérifiable." },
      ],
    },
    {
      id: "seq-5",
      title: "IA responsable, droit d'auteur et données",
      icon: "Scale",
      blocks: [
        { type: "text", html: "L'utilisation de l'IA dans une organisation doit respecter les <strong>données personnelles</strong>, le <strong>secret professionnel</strong>, le <strong>droit d'auteur</strong> et la <strong>transparence</strong> envers les bénéficiaires. On ne doit pas saisir dans un outil IA des informations sensibles sans base légale, consentement ou cadre institutionnel." },
        { type: "callout", tone: "warn", title: "Minimisation des données", text: "Ne collecter ou ne transmettre que les données strictement nécessaires. C'est un principe fondamental de protection des données : tout ne doit pas être partagé ni publié." },
        { type: "text", html: "Une <strong>charte d'usage responsable</strong> doit préciser ce qui est autorisé, ce qui est interdit, les règles de citation, la vérification obligatoire, la protection des données et les responsabilités de chaque utilisateur." },
        { type: "infographic", kind: "two-columns", title: "Une charte d'usage responsable", data: { left: { title: "Ce qu'elle précise", items: ["Usages autorisés et interdits", "Règles de citation et de transparence", "Vérification obligatoire avant publication", "Protection et minimisation des données", "Responsabilités de chaque utilisateur"] }, right: { title: "Ce qu'elle n'est pas", items: ["Elle ne remplace pas la loi", "Elle n'interdit pas tout ordinateur", "Elle ne masque pas les erreurs", "Elle n'autorise pas les données sensibles", "Elle ne dispense pas du contrôle humain"] } } },
        { type: "infographic", kind: "rules", title: "Trois principes d'un usage responsable", data: { rules: [
          { icon: "Eye", title: "Transparence", text: "Signaler l'usage de l'IA et citer ce qui doit l'être." },
          { icon: "CheckCircle", title: "Vérification", text: "Auditer et corriger avant toute diffusion." },
          { icon: "Lock", title: "Protection des données", text: "Pas de données sensibles sans cadre légal." },
        ] } },
        { type: "callout", tone: "tip", title: "Point d'attention du formateur", text: "Faire verbaliser la logique de choix : l'usage responsable n'est pas une contrainte ajoutée, c'est la condition de la confiance professionnelle." },
      ],
    },
    {
      id: "seq-6",
      title: "Intégrer l'IA dans l'ingénierie professionnelle",
      icon: "Workflow",
      blocks: [
        { type: "text", html: "Au niveau 3, l'apprenant passe d'<strong>utilisateur autonome</strong> à <strong>concepteur, pilote et responsable</strong> d'un dispositif numérique. La progression s'inscrit dans les repères de <strong>DigComp 2.2</strong> (compétences numériques citoyennes) et de <strong>DigCompEdu</strong> (compétences numériques professionnelles des éducateurs), avec une posture centrée sur l'humain, la vérification, la transparence et la protection des données." },
        { type: "keypoints", title: "Une production professionnelle de niveau 3", points: [
          "Utile : elle répond à un besoin réel et délimité.",
          "Cohérente : pédagogiquement et professionnellement structurée.",
          "Testée : éprouvée par des cas d'usage et la relecture par pairs.",
          "Sécurisée : respectueuse des données et du cadre légal.",
          "Documentée : choix justifiés et méthode transférable.",
        ] },
        { type: "infographic", kind: "steps", title: "Du besoin au transfert", data: { steps: [
          { title: "Diagnostic du besoin", text: "cadrage et rappel des acquis" },
          { title: "Démonstration dirigée", text: "manipulation d'un exemple complet" },
          { title: "Production accompagnée", text: "travail individuel ou binôme" },
          { title: "Test et audit", text: "grille qualité, relecture par pairs" },
          { title: "Évaluation et transfert", text: "production finale et justification orale" },
        ] } },
        { type: "callout", tone: "info", title: "Trace écrite à retenir", text: "Dans le module N3-M3, la compétence professionnelle se manifeste par une production utile, cohérente, testée, sécurisée et documentée. L'apprenant doit pouvoir justifier ses choix, corriger les limites observées et transférer la méthode vers une situation réelle." },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "qcm", title: "Améliorer un prompt", multiple: true,
      instruction: "Améliorez le prompt « Fais-moi un cours sur Excel » pour un public d'adultes débutants. Quels éléments un bon prompt doit-il préciser ?",
      options: [
        { text: "Le rôle du modèle (ex. concepteur pédagogique)", correct: true },
        { text: "Le public visé (adultes débutants) et la durée", correct: true },
        { text: "Les objectifs observables, activités et grille d'évaluation", correct: true },
        { text: "Le ton, le format et les contraintes", correct: true },
        { text: "Des données personnelles sensibles à intégrer", correct: false },
      ],
      feedback: "Un bon prompt précise le rôle, le public, la durée, les objectifs, le contenu, les activités, l'évaluation, le ton, le format et les contraintes. Exemple : « Agis comme concepteur pédagogique… propose un module de 3 heures avec objectifs observables, activités pratiques et grille d'évaluation. »",
    },
    {
      id: "f2", kind: "order", title: "Auditer une statistique sans source",
      instruction: "Une IA affirme une statistique sans source. Remettez les étapes de l'audit dans le bon ordre.",
      items: ["Isoler l'affirmation", "Demander ou chercher une source fiable", "Vérifier la date et le contexte", "Reformuler avec prudence ou supprimer si non vérifiable"],
      feedback: "On isole d'abord l'affirmation, on cherche une source fiable, on vérifie sa date et son contexte, puis on reformule avec prudence ou on supprime l'affirmation si elle n'est pas vérifiable.",
    },
    {
      id: "f3", kind: "categorize", title: "Prompt expert ou demande floue ?",
      instruction: "Classez chaque élément selon qu'il relève d'un prompt expert ou d'une demande floue.",
      categories: ["Prompt expert", "Demande floue"],
      items: [
        { label: "Préciser le rôle, le contexte et la tâche", category: "Prompt expert" },
        { label: "Indiquer le format de sortie et les critères de qualité", category: "Prompt expert" },
        { label: "Donner un exemple du résultat attendu", category: "Prompt expert" },
        { label: "Écrire seulement « Fais-moi un cours »", category: "Demande floue" },
        { label: "Ne donner aucune contrainte ni public", category: "Demande floue" },
      ],
      feedback: "Le prompt expert précise rôle, contexte, tâche, contraintes, format, critères et exemples. La demande floue laisse la production sans cadre.",
    },
    {
      id: "f4", kind: "match", title: "Familles d'IA et usages",
      instruction: "Associez chaque famille d'IA générative à un usage typique.",
      pairs: [
        { left: "IA de texte", right: "Rédiger et synthétiser des contenus" },
        { left: "IA d'image", right: "Produire des illustrations et visuels" },
        { left: "IA de code", right: "Générer ou corriger des scripts" },
        { left: "IA multimodale", right: "Traiter plusieurs types de données (texte + image)" },
      ],
      feedback: "Chaque famille a un usage dominant ; l'IA multimodale combine plusieurs modalités, par exemple texte et image.",
    },
    { id: "q1", kind: "qcm", title: "Qu'est-ce qu'une hallucination IA ?", instruction: "Une hallucination IA est :", options: [{ text: "Une image très colorée", correct: false }, { text: "Une erreur ou invention présentée comme plausible", correct: true }, { text: "Une mise à jour", correct: false }, { text: "Un mot de passe", correct: false }], feedback: "Réponse B. L'IA peut produire des contenus faux mais convaincants." },
    { id: "q2", kind: "qcm", title: "Le contenu d'un prompt expert", instruction: "Un prompt expert doit inclure de préférence :", options: [{ text: "Rôle, contexte, tâche, format et critères", correct: true }, { text: "Uniquement un mot", correct: false }, { text: "Des données sensibles", correct: false }, { text: "Un lien suspect", correct: false }], feedback: "Réponse A. Ces éléments encadrent la production." },
    { id: "q3", kind: "qcm", title: "Le prompt chaining", instruction: "Le prompt chaining consiste à :", options: [{ text: "Décomposer une tâche en étapes successives", correct: true }, { text: "Fermer une session", correct: false }, { text: "Changer de navigateur", correct: false }, { text: "Supprimer un fichier", correct: false }], feedback: "Réponse A. La chaîne d'instructions rend le travail plus contrôlé." },
    { id: "q4", kind: "qcm", title: "Avant de publier une réponse d'IA", instruction: "Avant de publier une réponse d'IA, il faut :", options: [{ text: "La vérifier et la corriger", correct: true }, { text: "La copier sans lecture", correct: false }, { text: "Supprimer les sources", correct: false }, { text: "Ajouter des données sensibles", correct: false }], feedback: "Réponse A. La responsabilité humaine reste centrale." },
    { id: "q5", kind: "qcm", title: "Un assistant IA spécialisé", instruction: "Un assistant IA spécialisé doit avoir :", options: [{ text: "Un objectif, des limites et des consignes stables", correct: true }, { text: "Un accès libre à toutes les données", correct: false }, { text: "Aucun critère", correct: false }, { text: "Des prompts secrets non documentés", correct: false }], feedback: "Réponse A. La spécialisation repose sur un cadrage documenté." },
    { id: "q6", kind: "qcm", title: "La minimisation des données", instruction: "La minimisation des données signifie :", options: [{ text: "Ne collecter ou transmettre que les données nécessaires", correct: true }, { text: "Tout partager", correct: false }, { text: "Tout publier", correct: false }, { text: "Supprimer les mots de passe", correct: false }], feedback: "Réponse A. C'est un principe de protection des données." },
    { id: "q7", kind: "qcm", title: "Une charte d'usage IA", instruction: "Une charte d'usage IA sert à :", options: [{ text: "Fixer les règles, responsabilités et limites", correct: true }, { text: "Remplacer la loi", correct: false }, { text: "Interdire tout ordinateur", correct: false }, { text: "Masquer les erreurs", correct: false }], feedback: "Réponse A. Elle cadre l'usage responsable." },
    { id: "q8", kind: "qcm", title: "L'IA multimodale", instruction: "L'IA multimodale peut traiter :", options: [{ text: "Plusieurs types de données comme texte et image", correct: true }, { text: "Uniquement des mots de passe", correct: false }, { text: "Uniquement des impressions", correct: false }, { text: "Uniquement des chiffres", correct: false }], feedback: "Réponse A. Le multimodal combine plusieurs modalités." },
    { id: "q9", kind: "qcm", title: "L'origine d'un biais", instruction: "Un biais dans une production IA peut provenir :", options: [{ text: "Des données, du contexte ou du cadrage", correct: true }, { text: "Uniquement de l'imprimante", correct: false }, { text: "Du clavier uniquement", correct: false }, { text: "D'un fichier vide", correct: false }], feedback: "Réponse A. Les biais peuvent avoir plusieurs sources." },
    { id: "q10", kind: "qcm", title: "Un usage responsable de l'IA", instruction: "Un usage responsable de l'IA implique :", options: [{ text: "Transparence, vérification, protection des données", correct: true }, { text: "Copie aveugle", correct: false }, { text: "Absence de sources", correct: false }, { text: "Partage de secrets", correct: false }], feedback: "Réponse A. Ces trois principes sont fondamentaux." },
    { id: "q11", kind: "truefalse", title: "L'IA « sait » ?", instruction: "Vrai ou faux ?", statement: "Une IA générative « sait » au sens humain : elle consulte une vérité avant de répondre.", answer: false, feedback: "Faux : l'IA ne sait pas au sens humain, elle produit des sorties probables à partir de modèles et de contextes. D'où la nécessité de vérifier." },
    { id: "q12", kind: "truefalse", title: "Données sensibles dans un outil IA", instruction: "Vrai ou faux ?", statement: "On peut saisir des informations sensibles dans un outil IA sans base légale, consentement ou cadre institutionnel.", answer: false, feedback: "Faux : il ne faut pas saisir d'informations sensibles sans base légale, consentement ou cadre institutionnel. La minimisation des données s'impose." },
    {
      id: "q13", kind: "categorize", title: "Charte d'usage responsable",
      instruction: "Classez chaque pratique selon qu'elle est conforme ou contraire à une charte d'usage responsable de l'IA.",
      categories: ["Conforme", "Contraire"],
      items: [
        { label: "Citer et vérifier tout contenu produit par IA", category: "Conforme" },
        { label: "Anonymiser les exercices et minimiser les données", category: "Conforme" },
        { label: "Publier un cours IA sans aucune relecture", category: "Contraire" },
        { label: "Demander aux apprenants de saisir des données personnelles dans un outil externe", category: "Contraire" },
      ],
      feedback: "Tout contenu IA publié doit être audité, cité, vérifié et conforme à la politique de données ; les pratiques opposées exposent à la désinformation et à la violation de données.",
    },
  ],
  caseStudy: {
    title: "Étude de cas — Production IA non vérifiée",
    scenario:
      "Un formateur publie sur le LMS un cours produit par IA. Plusieurs références sont inventées et une consigne demande aux apprenants de saisir des données personnelles dans un outil externe.",
    questions: [
      "Quels risques voyez-vous dans cette situation ?",
      "Comment corriger le cours avant publication ?",
      "Quelle règle institutionnelle proposer pour l'avenir ?",
    ],
    corrige: [
      "Risques : désinformation due aux références inventées, atteinte à la confiance, violation de données personnelles via l'outil externe, et problème de droit d'auteur.",
      "Correction : vérifier les sources, retirer les références douteuses, anonymiser les exercices et ne pas exiger de données personnelles, puis ajouter une note de transparence indiquant le recours à l'IA.",
      "Règle : tout contenu IA publié doit être audité, cité, vérifié et conforme à la politique de protection des données de l'établissement.",
    ],
  },
};
