import { N1Module } from "../niveau1/types";

/** Niveau 2 — Module 2 : Création de contenus numériques et visuels. */
export const MODULE_2: N1Module = {
  code: "N2-M2",
  slug: "module-2",
  num: 2,
  title: "Création de contenus numériques et visuels",
  subtitle:
    "Concevoir des affiches, infographies, formulaires et activités interactives clairs, utiles et conformes.",
  duration: "18 heures · 2 semaines",
  finalite:
    "Former l'apprenant à créer un kit de contenus numériques : affiche, infographie, formulaire et activité interactive simple, attractifs, utiles et conformes aux règles de lisibilité, d'accessibilité et de droit d'auteur.",
  objectives: [
    "Concevoir un visuel professionnel respectant une identité graphique.",
    "Mobiliser les principes de design : composition, couleurs, typographie, hiérarchie visuelle.",
    "Créer un formulaire en ligne structuré pour collecter et organiser des informations.",
    "Paramétrer la logique d'un formulaire : champs obligatoires, validation, notifications, synthèse des réponses.",
    "Exploiter les réponses d'un formulaire par synthèse automatique ou export vers un tableur.",
    "Produire une première activité interactive simple à partir de contenus créés.",
  ],
  competences: [
    { group: "Techniques", text: "Créer une affiche, une carte ou une infographie professionnelle avec un outil de design assisté ; construire un formulaire en ligne clair et exploitable ; produire une activité interactive de base (quiz, image interactive, association, glisser-déposer)." },
    { group: "Méthodologiques", text: "Clarifier le message avant de créer (public, objectif, action attendue), établir une hiérarchie visuelle et justifier ses choix graphiques et fonctionnels." },
    { group: "Sécurité / Qualité", text: "Collecter les réponses dans le respect de la minimisation des données, vérifier les droits d'usage des images, citer ses sources et tester le rendu avant diffusion." },
    { group: "Transversales", text: "Exporter aux formats adaptés (PNG, PDF, lien, intégration LMS), nommer et déposer proprement ses productions, et solliciter une relecture entre pairs." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Concevoir avant de créer",
      icon: "Lightbulb",
      blocks: [
        { type: "text", html: "Une ressource visuelle réussie commence <strong>avant</strong> l'ouverture de Canva, PowerPoint ou tout autre outil. Il faut d'abord clarifier le message : qui parle, à qui, pour quoi faire et avec quelle action attendue ? Un visuel destiné à informer ne se construit pas comme un visuel destiné à convaincre ou à faire s'inscrire à une activité." },
        { type: "text", html: "L'apprenant doit pouvoir répondre en une phrase : « Ce visuel doit permettre à tel public de comprendre telle information et de faire telle action. » Cette étape évite les productions <em>décoratives mais inefficaces</em>." },
        { type: "text", html: "La <strong>hiérarchie visuelle</strong> organise la lecture : un titre fort, une information principale, quelques éléments secondaires, puis un appel à l'action. Lorsque tout est mis en grand, plus rien ne ressort." },
        { type: "infographic", kind: "steps", title: "Avant d'ouvrir l'outil de design", data: { steps: [
          { title: "Définir le cadrage", text: "public cible, objectif, message et action attendue" },
          { title: "Choisir le format", text: "affiche, infographie, carte, publication réseau social ou support imprimable" },
          { title: "Établir la hiérarchie", text: "titre, sous-titre, contenu, appel à l'action" },
        ] } },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Pour une formation, le visuel doit faire apparaître clairement le thème, le public visé, la date, le lieu ou le lien, le contact et l'action : s'inscrire ou scanner un code QR." },
      ],
    },
    {
      id: "seq-2",
      title: "Principes de design avec Canva ou un outil équivalent",
      icon: "Palette",
      blocks: [
        { type: "text", html: "Les outils de design proposent de nombreux modèles, mais un modèle n'est qu'un <strong>point de départ</strong>. Il faut l'adapter au message, à l'identité de l'organisation et au contexte culturel. La cohérence repose sur une palette limitée, deux polices au maximum et des alignements précis." },
        { type: "text", html: "La couleur doit servir la <strong>lisibilité</strong>. Une couleur vive peut attirer l'attention, mais trop de couleurs concurrencent le message. Le contraste entre texte et fond est essentiel, surtout pour les impressions ou les projections. La typographie doit rester lisible : les polices décoratives sont à utiliser avec prudence." },
        { type: "text", html: "Les images doivent être choisies pour leur <strong>pertinence</strong> et leur <strong>qualité</strong>. Une image floue ou mal recadrée peut affaiblir un support sérieux. Toute image trouvée en ligne n'est pas librement réutilisable : il faut vérifier les droits d'usage." },
        { type: "infographic", kind: "rules", title: "Quatre règles de design", data: { rules: [
          { icon: "Palette", title: "Palette cohérente", text: "Utiliser une palette de couleurs limitée et institutionnelle." },
          { icon: "Type", title: "Peu de polices", text: "Limiter le nombre de polices (deux au maximum)." },
          { icon: "AlignLeft", title: "Alignements", text: "Respecter les alignements et les espaces." },
          { icon: "Image", title: "Droits d'image", text: "Vérifier les droits d'utilisation des images." },
        ] } },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Une affiche EduWeb peut utiliser un fond clair, une couleur institutionnelle, un titre très lisible et un QR code accompagné de l'instruction « Scannez pour vous inscrire »." },
      ],
    },
    {
      id: "seq-3",
      title: "Formulaires en ligne : collecter utilement",
      icon: "ClipboardList",
      blocks: [
        { type: "text", html: "Un formulaire est un <strong>outil de collecte</strong>, pas une simple liste de questions. Sa qualité dépend de son objectif. Si le formulaire sert à inscrire des participants, les champs doivent être limités aux informations nécessaires. S'il sert à évaluer une formation, les questions doivent produire des réponses exploitables." },
        { type: "text", html: "Le principe de <strong>minimisation des données</strong> est central : on ne collecte pas une donnée parce qu'elle pourrait être intéressante, mais parce qu'elle est nécessaire à l'objectif. Cette logique est cohérente avec les principes du RGPD relayés par la CNIL." },
        { type: "infographic", kind: "two-columns", title: "Paramétrer un formulaire de qualité", data: { left: { title: "Structure du formulaire", subtitle: "ce que l'on paramètre", items: ["Titre et description", "Sections", "Champs obligatoires", "Validation des réponses", "Message de confirmation", "Limitation éventuelle à une réponse", "Export vers tableur", "Notifications"] }, right: { title: "Bonnes pratiques", subtitle: "ce qui rend les réponses exploitables", items: ["Questions courtes et non ambiguës", "Champs obligatoires limités à l'indispensable", "Validation des e-mails ou nombres si nécessaire", "Synthèse des réponses et export vers tableur"] } } },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Pour une inscription, il peut suffire de collecter nom, prénom, établissement, contact, choix de session et consentement. La date de naissance n'est demandée que si elle est nécessaire." },
      ],
    },
    {
      id: "seq-4",
      title: "Activités interactives simples",
      icon: "MousePointerClick",
      blocks: [
        { type: "text", html: "L'<strong>interactivité</strong> transforme un contenu consulté passivement en activité d'apprentissage. Un quiz, une image interactive ou un exercice d'association oblige l'apprenant à agir, à vérifier sa compréhension et à recevoir une rétroaction." },
        { type: "text", html: "L'activité interactive doit rester <strong>alignée sur un objectif</strong>. On ne crée pas un quiz pour occuper l'écran, mais pour vérifier une connaissance ou entraîner une compétence. Les rétroactions doivent expliquer la réponse, et non se limiter à « vrai » ou « faux »." },
        { type: "text", html: "Le formateur peut utiliser H5P, LearningApps, Wooclap ou un outil intégré à une plateforme. L'essentiel est d'apprendre la <strong>logique</strong> : objectif, consigne, interaction, correction, rétroaction, test." },
        { type: "infographic", kind: "steps", title: "La logique d'une activité interactive", data: { steps: [
          { title: "Objectif", text: "une activité = un objectif clair" },
          { title: "Consigne", text: "courte et compréhensible" },
          { title: "Interaction", text: "l'apprenant agit (quiz, association, glisser-déposer)" },
          { title: "Correction", text: "et rétroaction formative" },
          { title: "Test", text: "tester l'activité avant diffusion" },
        ] } },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Une image interactive sur les parties d'un ordinateur peut afficher des points cliquables : écran, clavier, souris, unité centrale, imprimante." },
      ],
    },
    {
      id: "seq-5",
      title: "Diffusion, formats et droits d'auteur",
      icon: "Share2",
      blocks: [
        { type: "text", html: "La diffusion d'un contenu dépend du support. Une affiche imprimée doit être exportée en <strong>PDF</strong> ou <strong>PNG</strong> de bonne qualité. Une publication web peut être plus légère. Une activité interactive peut être partagée par lien, intégrée à un LMS ou exportée selon l'outil." },
        { type: "text", html: "L'apprenant doit aussi apprendre à <strong>citer ses sources</strong> et à respecter les licences. Les images, icônes, musiques et vidéos ont des droits. Les banques gratuites ne dispensent pas toujours de lire les conditions d'utilisation." },
        { type: "text", html: "La qualité professionnelle inclut le nommage des fichiers, la conservation des <strong>versions modifiables</strong>, le dépôt dans un dossier organisé et la vérification du rendu sur plusieurs écrans." },
        { type: "infographic", kind: "table", title: "Choisir le bon format de diffusion", data: { columns: ["Support", "Format conseillé"], rows: [
          ["Affiche imprimée", "PDF ou PNG haute qualité"],
          ["Publication web", "Image légère (PNG / JPG optimisé)"],
          ["Activité interactive", "Lien de partage ou fichier intégrable au LMS"],
          ["Version de travail", "Fichier modifiable conservé"],
        ] } },
        { type: "keypoints", title: "Avant de diffuser", points: [
          "Exporter au bon format : PDF, PNG, lien ou fichier intégrable.",
          "Citer les sources et licences utiles.",
          "Conserver la version modifiable.",
          "Tester le rendu final sur plusieurs écrans.",
        ] },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Un kit final peut contenir Affiche_Formation_CERTEL.pdf, Infographie_Objectifs.png, Formulaire_Inscription_lien.txt et Activite_Quiz_lien.txt." },
      ],
    },
    {
      id: "seq-6",
      title: "Travaux pratiques et productions attendues",
      icon: "Wrench",
      blocks: [
        { type: "text", html: "Le module alterne conception, design, collecte, interactivité et diffusion. Chaque séance produit un élément du <strong>portfolio visuel</strong> : brief, visuel V1, visuel final, formulaire, synthèse des réponses, puis activité interactive publiée." },
        { type: "infographic", kind: "categories", title: "Les trois travaux pratiques", data: { columns: [
          { title: "TP 1 — Affiche événementielle", accent: "#6D5DF5", items: [{ label: "Rédiger le brief", hint: "public, objectif, message, action" }, { label: "Choisir un format adapté" }, { label: "Palette de couleurs limitée" }, { label: "Informations essentielles + appel à l'action" }, { label: "Exporter en PDF et PNG" }] },
          { title: "TP 2 — Formulaire", accent: "#0891B2", items: [{ label: "Définir l'objectif de la collecte" }, { label: "Créer sections et questions" }, { label: "Limiter les champs obligatoires" }, { label: "Message de confirmation" }, { label: "Tester avec 3 réponses fictives" }, { label: "Exporter / consulter la synthèse" }] },
          { title: "TP 3 — Activité interactive", accent: "#16A34A", items: [{ label: "Choisir un objectif d'apprentissage" }, { label: "Format : quiz, association, image interactive" }, { label: "Rédiger une consigne claire" }, { label: "Rétroaction pour chaque réponse" }, { label: "Tester avec un pair" }] },
        ] } },
        { type: "callout", tone: "tip", title: "Critères de réussite", text: "Affiche : message immédiatement compréhensible, lisibilité à distance, cohérence graphique, export professionnel. Formulaire : questions utiles, données personnelles limitées, réponses exploitables, synthèse lisible. Activité : objectif clair, rétroactions utiles, activité fonctionnelle, présentation sobre." },
      ],
    },
    {
      id: "seq-7",
      title: "Qualité, droits et protection des données",
      icon: "ShieldCheck",
      blocks: [
        { type: "text", html: "Créer un contenu numérique professionnel, c'est articuler <strong>message, design, utilité, interactivité, droits et protection des données</strong>. Un bon contenu se comprend vite, se teste facilement et respecte le public auquel il s'adresse." },
        { type: "text", html: "Une rétroaction efficace ne se limite pas à « faux » : elle <strong>explique l'erreur et propose une amélioration</strong>. Par exemple, plutôt que « Faux », on écrira : « Ce mot de passe est trop court et facile à deviner. Un mot de passe robuste doit être long, unique et difficile à associer à votre identité. »" },
        { type: "callout", tone: "warn", title: "À éviter", text: "Une affiche surchargée (cinq polices, trop de couleurs), un QR code sans consigne et un formulaire qui demande le numéro de carte d'identité sans justification : surcharge visuelle, incohérence typographique et collecte excessive de données." },
        { type: "callout", tone: "tip", title: "Trace écrite à retenir", text: "Un bon contenu se comprend vite, se teste facilement et respecte le public auquel il s'adresse. La qualité passe par une charte sobre, un message clair, un appel à l'action et une collecte limitée à l'essentiel." },
        { type: "infographic", kind: "rules", title: "Tester avant de diffuser", data: { rules: [
          { icon: "Eye", title: "Faire relire", text: "Faire lire l'affiche à un pair pour vérifier la compréhension." },
          { icon: "QrCode", title: "Vérifier le QR code", text: "S'assurer que le lien fonctionne et que la consigne est claire." },
          { icon: "Send", title: "Réponse fictive", text: "Soumettre une réponse de test au formulaire." },
          { icon: "BarChart3", title: "Consulter la synthèse", text: "Vérifier que les réponses sont exploitables." },
        ] } },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "categorize", title: "Minimisation des données",
      instruction: "Pour un formulaire d'inscription à un atelier de deux heures, classez chaque donnée : utile (à collecter) ou à éviter (sauf nécessité justifiée).",
      categories: ["Donnée utile", "Donnée à éviter"],
      items: [
        { label: "Nom", category: "Donnée utile" },
        { label: "Prénom", category: "Donnée utile" },
        { label: "Contact", category: "Donnée utile" },
        { label: "Structure / établissement", category: "Donnée utile" },
        { label: "Choix de session", category: "Donnée utile" },
        { label: "Besoin particulier éventuel", category: "Donnée utile" },
        { label: "Date de naissance", category: "Donnée à éviter" },
        { label: "Adresse complète", category: "Donnée à éviter" },
        { label: "Informations familiales", category: "Donnée à éviter" },
        { label: "Numéro de carte d'identité", category: "Donnée à éviter" },
      ],
      feedback: "La réponse est correcte lorsqu'elle relie chaque donnée à l'objectif du formulaire. On collecte le nom, le prénom, le contact, la structure, le choix de session et un éventuel besoin particulier. On évite la date de naissance, l'adresse complète, les informations familiales ou le numéro d'identité tant qu'ils ne sont pas nécessaires (principe de minimisation des données / RGPD).",
    },
    {
      id: "f2", kind: "order", title: "La logique d'une activité interactive",
      instruction: "Remettez dans le bon ordre les étapes de conception d'une activité interactive.",
      items: ["Définir l'objectif d'apprentissage", "Rédiger une consigne claire", "Construire l'interaction (quiz, association, image interactive)", "Ajouter la correction et la rétroaction", "Tester l'activité avant diffusion"],
      feedback: "L'essentiel est d'apprendre la logique : objectif, consigne, interaction, correction, rétroaction, test. Une activité = un objectif clair, et on la teste toujours avant de la diffuser.",
    },
    {
      id: "f3", kind: "order", title: "Créer une affiche événementielle (TP 1)",
      instruction: "Remettez les étapes du TP 1 dans le bon ordre.",
      items: ["Rédiger le brief : public, objectif, message, action attendue", "Choisir un format adapté", "Créer le visuel avec une palette de couleurs limitée", "Ajouter les informations essentielles et un appel à l'action", "Exporter en PDF et PNG"],
      feedback: "On clarifie d'abord le besoin (brief), puis on choisit le format, on conçoit le visuel avec une palette limitée, on ajoute l'information centrale et l'appel à l'action, et on exporte enfin aux bons formats.",
    },
    {
      id: "f4", kind: "categorize", title: "Choisir le bon format de diffusion",
      instruction: "Associez chaque besoin de diffusion au format le plus adapté.",
      categories: ["PDF / PNG haute qualité", "Lien de partage ou fichier intégrable"],
      items: [
        { label: "Affiche destinée à l'impression", category: "PDF / PNG haute qualité" },
        { label: "Infographie à imprimer ou projeter", category: "PDF / PNG haute qualité" },
        { label: "Quiz à partager aux apprenants", category: "Lien de partage ou fichier intégrable" },
        { label: "Activité interactive intégrée au LMS", category: "Lien de partage ou fichier intégrable" },
      ],
      feedback: "Les supports imprimables s'exportent en PDF ou PNG de bonne qualité ; les activités interactives se partagent par lien ou s'intègrent au LMS. On conserve aussi toujours la version modifiable.",
    },
    {
      id: "f5", kind: "match", title: "Vérifier une campagne avant diffusion",
      instruction: "Reliez chaque test de validation à ce qu'il permet de vérifier.",
      pairs: [
        { left: "Faire lire l'affiche à un pair", right: "La compréhension du message" },
        { left: "Vérifier le QR code", right: "Le lien fonctionne et la consigne est claire" },
        { left: "Soumettre une réponse fictive", right: "Le formulaire fonctionne" },
        { left: "Consulter la synthèse", right: "Les réponses sont exploitables" },
      ],
      feedback: "Tester une campagne consiste à faire lire l'affiche à un pair, à vérifier le QR code, à soumettre une réponse fictive et à consulter la synthèse des réponses.",
    },
    {
      id: "q1", kind: "qcm", title: "La première étape d'un visuel",
      instruction: "La première étape d'un visuel professionnel est :",
      options: [
        { text: "Choisir une animation", correct: false },
        { text: "Clarifier le public et le message", correct: true },
        { text: "Ajouter beaucoup d'images", correct: false },
        { text: "Exporter en PDF", correct: false },
      ],
      feedback: "Bonne réponse : clarifier le public et le message. Le design doit servir un objectif de communication.",
    },
    {
      id: "q2", kind: "qcm", title: "La hiérarchie visuelle",
      instruction: "Une bonne hiérarchie visuelle permet :",
      options: [
        { text: "De guider la lecture", correct: true },
        { text: "De cacher les informations", correct: false },
        { text: "De supprimer les titres", correct: false },
        { text: "De multiplier les polices", correct: false },
      ],
      feedback: "Bonne réponse : guider la lecture. Elle aide le lecteur à distinguer l'essentiel du secondaire.",
    },
    {
      id: "q3", kind: "qcm", title: "Un champ obligatoire",
      instruction: "Dans un formulaire, un champ obligatoire doit être :",
      options: [
        { text: "Toujours très nombreux", correct: false },
        { text: "Limité aux informations indispensables", correct: true },
        { text: "Décoratif", correct: false },
        { text: "Sans rapport avec l'objectif", correct: false },
      ],
      feedback: "Bonne réponse : limité aux informations indispensables. Cela respecte le principe de minimisation des données.",
    },
    {
      id: "q4", kind: "qcm", title: "Une activité interactive",
      instruction: "Une activité interactive doit d'abord être alignée sur :",
      options: [
        { text: "Un objectif pédagogique", correct: true },
        { text: "Une couleur", correct: false },
        { text: "Le hasard", correct: false },
        { text: "La longueur du fichier", correct: false },
      ],
      feedback: "Bonne réponse : un objectif pédagogique. L'interactivité a du sens si elle sert un apprentissage.",
    },
    {
      id: "q5", kind: "qcm", title: "Une rétroaction efficace",
      instruction: "Une rétroaction efficace :",
      options: [
        { text: "Explique la réponse", correct: true },
        { text: "Se limite à « faux »", correct: false },
        { text: "Humilie l'apprenant", correct: false },
        { text: "Empêche de recommencer", correct: false },
      ],
      feedback: "Bonne réponse : elle explique la réponse. La rétroaction doit aider à comprendre et à progresser.",
    },
    {
      id: "q6", kind: "qcm", title: "Le format PDF",
      instruction: "Le format PDF est souvent utile pour :",
      options: [
        { text: "Diffuser un visuel imprimable", correct: true },
        { text: "Installer une application", correct: false },
        { text: "Créer un mot de passe", correct: false },
        { text: "Remplacer une source", correct: false },
      ],
      feedback: "Bonne réponse : diffuser un visuel imprimable. Le PDF conserve la mise en page.",
    },
    {
      id: "q7", kind: "qcm", title: "Une image trouvée en ligne",
      instruction: "Une image trouvée en ligne :",
      options: [
        { text: "Est toujours libre", correct: false },
        { text: "Peut être protégée par des droits", correct: true },
        { text: "Est toujours interdite", correct: false },
        { text: "Supprime la nécessité de citer", correct: false },
      ],
      feedback: "Bonne réponse : elle peut être protégée par des droits. Il faut vérifier les conditions d'usage.",
    },
    {
      id: "q8", kind: "qcm", title: "Un formulaire en ligne",
      instruction: "Un formulaire en ligne peut être relié à :",
      options: [
        { text: "Un tableur de réponses", correct: true },
        { text: "Une souris uniquement", correct: false },
        { text: "Une imprimante invisible", correct: false },
        { text: "Un câble audio", correct: false },
      ],
      feedback: "Bonne réponse : un tableur de réponses. Les réponses peuvent être exploitées dans un tableur.",
    },
    {
      id: "q9", kind: "qcm", title: "Le QR code sur une affiche",
      instruction: "Un QR code sur une affiche doit être accompagné :",
      options: [
        { text: "D'une consigne claire", correct: true },
        { text: "D'un mot de passe public", correct: false },
        { text: "De données privées", correct: false },
        { text: "D'une image floue", correct: false },
      ],
      feedback: "Bonne réponse : d'une consigne claire. Le lecteur doit savoir pourquoi scanner.",
    },
    {
      id: "q10", kind: "qcm", title: "Un visuel surchargé",
      instruction: "Un visuel surchargé produit souvent :",
      options: [
        { text: "Une baisse de compréhension", correct: true },
        { text: "Une meilleure lisibilité", correct: false },
        { text: "Une correction automatique", correct: false },
        { text: "Une confidentialité renforcée", correct: false },
      ],
      feedback: "Bonne réponse : une baisse de compréhension. Trop d'éléments concurrents diminuent l'attention.",
    },
    {
      id: "q11", kind: "qcm", multiple: true, title: "Principes de design",
      instruction: "Quelles pratiques relèvent d'un bon design graphique ? (plusieurs réponses)",
      options: [
        { text: "Utiliser une palette de couleurs limitée", correct: true },
        { text: "Limiter le nombre de polices", correct: true },
        { text: "Respecter les alignements et les espaces", correct: true },
        { text: "Multiplier les couleurs vives pour attirer l'œil", correct: false },
        { text: "Vérifier les droits d'utilisation des images", correct: true },
      ],
      feedback: "Un design efficace repose sur une palette cohérente, peu de polices, des alignements précis et des images dont on a vérifié les droits. Trop de couleurs concurrencent le message.",
    },
    {
      id: "q12", kind: "truefalse", title: "Toute image en ligne est réutilisable",
      instruction: "Vrai ou faux ?",
      statement: "Toute image trouvée en ligne est librement réutilisable dans un visuel professionnel.",
      answer: false,
      feedback: "Faux : les images, icônes, musiques et vidéos ont des droits. Les banques gratuites ne dispensent pas toujours de lire les conditions d'utilisation.",
    },
    {
      id: "q13", kind: "truefalse", title: "Le modèle de départ",
      instruction: "Vrai ou faux ?",
      statement: "Un modèle proposé par un outil de design n'est qu'un point de départ à adapter au message et à l'identité de l'organisation.",
      answer: true,
      feedback: "Vrai : un modèle n'est qu'un point de départ. Il faut l'adapter au message, à l'identité de l'organisation et au contexte culturel.",
    },
    {
      id: "q14", kind: "truefalse", title: "Tester avant de diffuser",
      instruction: "Vrai ou faux ?",
      statement: "Une activité interactive peut être diffusée sans avoir été testée au préalable.",
      answer: false,
      feedback: "Faux : on teste toujours l'activité avant diffusion, idéalement avec un pair, pour vérifier que la consigne est comprise et que la rétroaction est utile.",
    },
  ],
  caseStudy: {
    title: "Étude de cas — La campagne de l'association",
    scenario:
      "Une association lance une campagne de formation avec une affiche très colorée, cinq polices différentes, un QR code sans explication et un formulaire demandant le numéro de carte d'identité sans justification.",
    questions: [
      "Repérez les problèmes de design et de protection des données.",
      "Proposez une version améliorée de la campagne.",
      "Indiquez comment tester la campagne avant diffusion.",
    ],
    corrige: [
      "Les problèmes sont la surcharge visuelle, l'incohérence typographique (cinq polices), l'absence d'appel à l'action autour du QR code et la collecte excessive de données (numéro de carte d'identité non justifié).",
      "La version améliorée doit utiliser une charte sobre, un message clair, un QR code accompagné d'une consigne (« Scannez pour vous inscrire ») et un formulaire limité aux informations nécessaires.",
      "Le test consiste à faire lire l'affiche à un pair, à vérifier le QR code, à soumettre une réponse fictive au formulaire et à consulter la synthèse des réponses.",
    ],
  },
};
