import type { N1Module } from "../niveau1/types";

/** Niveau 2 — Module 1 : Production bureautique avancée et documents professionnels. */
export const MODULE_1: N1Module = {
  code: "N2-M1",
  slug: "module-1",
  num: 1,
  title: "Production bureautique avancée et documents professionnels",
  subtitle:
    "Passer d'une bureautique fonctionnelle à une production professionnelle : Word structuré, Excel de gestion et PowerPoint sobre, diffusables en PDF ou cloud.",
  duration: "27 heures · 3 semaines",
  finalite:
    "Amener l'apprenant à produire un dossier bureautique professionnel complet, fiable, lisible, accessible et exportable en PDF ou dans un espace cloud partagé.",
  objectives: [
    "Structurer un document Word à l'aide des styles, d'un sommaire automatique, d'en-têtes, de pieds de page et d'une numérotation cohérente.",
    "Concevoir un modèle de document professionnel réutilisable intégrant charte graphique, marges, titres, tableaux et règles d'accessibilité.",
    "Construire dans Excel un tableau de gestion combinant formules essentielles et fonctions de synthèse.",
    "Appliquer une mise en forme conditionnelle et sélectionner des graphiques pertinents pour interpréter les données.",
    "Finaliser une présentation PowerPoint à fort impact en harmonisant les transitions et les visuels.",
    "Exporter et diffuser un livrable bureautique aux formats professionnels, notamment PDF et partage cloud.",
  ],
  competences: [
    { group: "Techniques", text: "Créer des documents longs, propres et navigables grâce aux styles et au sommaire automatique ; utiliser les fonctions SOMME, MOYENNE, SI, NB.SI et SOMME.SI dans un tableau de gestion ; produire un graphique lisible et adapté à la nature des données." },
    { group: "Méthodologiques", text: "Concevoir et réutiliser un modèle institutionnel cohérent (police, marges, titres, logo), préparer un document à l'impression et à la diffusion numérique, et transformer un ensemble de fichiers en livrable unique et professionnel." },
    { group: "Qualité et accessibilité", text: "Appliquer les premiers principes d'accessibilité documentaire — contraste, hiérarchie des titres, texte alternatif, lisibilité — et effectuer un contrôle qualité avant diffusion." },
    { group: "Transversales", text: "Développer le jugement (choix du bon graphique, du bon format, des bons droits de partage), la rigueur de finition et la capacité à communiquer une information de manière claire et crédible." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Du document saisi au document structuré",
      icon: "FileText",
      blocks: [
        { type: "text", html: "Un document professionnel n'est pas un simple texte aligné sur une page. Il possède une <strong>architecture</strong> : titre principal, sous-titres, paragraphes équilibrés, tableaux lisibles, illustrations utiles, références et informations de suivi. Cette architecture permet au lecteur de circuler facilement dans le document et au producteur de gagner du temps lors des modifications." },
        { type: "text", html: "L'erreur la plus fréquente consiste à mettre en forme <em>manuellement</em> chaque titre : gras, taille de police, couleur, numérotation improvisée. Cette méthode semble rapide au début, mais elle devient fragile dès que le document dépasse quelques pages. L'usage des <strong>styles</strong> règle ce problème : un style définit une apparence et une fonction. Un titre de niveau 1 n'est donc pas seulement un texte en gros caractères ; il est reconnu par Word comme un élément de structure susceptible d'apparaître dans le sommaire." },
        { type: "infographic", kind: "categories", title: "Les styles, apparence et fonction", data: { columns: [
          { title: "Normal", accent: "#0891B2", items: [{ label: "Corps du texte", hint: "paragraphes courants" }] },
          { title: "Titre 1", accent: "#6D5DF5", items: [{ label: "Grandes parties", hint: "apparaît dans le sommaire" }] },
          { title: "Titre 2 / Titre 3", accent: "#16A34A", items: [{ label: "Sous-parties", hint: "hiérarchie fine" }] },
        ] } },
        { type: "keypoints", title: "Trois leviers de structuration", points: [
          "Style Normal pour le corps du texte ; Titre 1 pour les grandes parties ; Titre 2 et Titre 3 pour les sous-parties.",
          "Sommaire automatique généré après application des styles.",
          "En-têtes et pieds de page pour l'identification du document, la date, l'institution et la pagination.",
        ] },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "À partir d'un rapport de trois pages intitulé « Bilan d'activité », l'apprenant applique les styles aux sections Introduction, Résultats, Difficultés et Perspectives, puis génère le sommaire automatiquement." },
      ],
    },
    {
      id: "seq-2",
      title: "Modèles, charte et accessibilité documentaire",
      icon: "LayoutTemplate",
      blocks: [
        { type: "text", html: "Un <strong>modèle</strong> est un document de référence que l'on réutilise pour éviter de reconstruire la mise en page à chaque nouvelle production. Dans une institution, les modèles favorisent la cohérence : même police, mêmes marges, même logique de titres, même emplacement pour le logo, les coordonnées et la signature." },
        { type: "text", html: "La <strong>charte graphique</strong> ne doit pas être comprise comme une décoration. Elle exprime l'identité de l'organisation et améliore la lecture. Une couleur principale, une couleur secondaire et une police lisible suffisent souvent. Trop de couleurs, trop de polices ou trop d'effets diminuent la crédibilité du document." },
        { type: "text", html: "L'<strong>accessibilité</strong> signifie que le document peut être compris par le plus grand nombre, y compris les personnes qui utilisent un lecteur d'écran ou qui ont des difficultés visuelles. Le formateur introduit des gestes simples : utiliser de vrais titres, éviter les images sans texte alternatif, préserver un bon contraste, ne pas transmettre une information uniquement par la couleur." },
        { type: "infographic", kind: "rules", title: "Quatre gestes d'accessibilité", data: { rules: [
          { icon: "Heading", title: "De vrais titres", text: "Hiérarchiser avec les styles, jamais avec du simple gras agrandi." },
          { icon: "Image", title: "Texte alternatif", text: "Décrire les images utiles pour les lecteurs d'écran." },
          { icon: "Contrast", title: "Bon contraste", text: "Garantir la lisibilité du texte sur le fond." },
          { icon: "Palette", title: "Pas que la couleur", text: "Ne jamais transmettre une information uniquement par la couleur." },
        ] } },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Un rapport institutionnel utilise une couleur EduWeb en titre, un pied de page avec contacts et un sommaire automatique. Le résultat est plus crédible qu'un document rempli d'effets décoratifs." },
      ],
    },
    {
      id: "seq-3",
      title: "Excel comme outil de gestion et de décision",
      icon: "Table",
      blocks: [
        { type: "text", html: "Dans ce niveau, Excel n'est plus abordé seulement comme un tableau de calcul. Il devient un <strong>outil de gestion</strong>. Un tableau professionnel doit être pensé pour recevoir des données, calculer automatiquement des résultats, signaler les situations importantes et produire une synthèse visuelle." },
        { type: "text", html: "Les fonctions <strong>SOMME</strong> et <strong>MOYENNE</strong> servent à synthétiser des quantités ou des performances. La fonction <strong>SI</strong> introduit la logique conditionnelle : si une condition est vérifiée, Excel affiche une valeur ; sinon, il affiche une autre valeur. Les fonctions <strong>NB.SI</strong> et <strong>SOMME.SI</strong> permettent de compter ou d'additionner selon un critère. Ces fonctions sont très utiles pour les listes de présence, budgets, notes, ventes ou suivis d'activités." },
        { type: "infographic", kind: "table", title: "Les fonctions essentielles de gestion", data: { columns: ["Fonction", "Rôle"], rows: [
          ["=SOMME(D2:D10)", "Additionner une plage de valeurs"],
          ["=MOYENNE(D2:D10)", "Calculer la moyenne d'une plage"],
          ["=SI(D2>C2;\"Dépassement\";\"Conforme\")", "Afficher un résultat selon une condition"],
          ["=NB.SI(plage;critère)", "Compter les cellules répondant à un critère"],
          ["=SOMME.SI(plage;critère;somme)", "Additionner selon un critère"],
        ] } },
        { type: "text", html: "La <strong>mise en forme conditionnelle</strong> est un outil de lecture. Elle ne remplace pas l'analyse, mais attire l'attention. Par exemple, les dépenses supérieures au budget prévu peuvent apparaître en rouge, les notes validées en vert ou les retards en orange." },
        { type: "keypoints", title: "Bonnes pratiques d'un tableau de gestion", points: [
          "Utiliser une ligne d'en-tête claire.",
          "Figer les volets lorsque le tableau devient long.",
          "Nommer les colonnes de manière explicite.",
          "Privilégier des formules recopiables et éviter les cellules fusionnées dans les tableaux de données.",
        ] },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Dans un tableau de budget, =SOMME(D2:D10) calcule la dépense totale, =MOYENNE(D2:D10) donne la moyenne des dépenses et =SI(D2>C2;\"Dépassement\";\"Conforme\") signale si une dépense dépasse le budget prévu." },
      ],
    },
    {
      id: "seq-4",
      title: "Graphiques et interprétation des données",
      icon: "BarChart3",
      blocks: [
        { type: "text", html: "Un graphique n'est pas une décoration. Il doit <strong>répondre à une question</strong>. Si l'on veut comparer des catégories, l'histogramme est souvent adapté. Si l'on veut montrer une répartition, le secteur peut être utilisé avec prudence. Si l'on veut observer une évolution, une courbe est généralement plus pertinente." },
        { type: "infographic", kind: "two-columns", title: "Choisir le bon graphique", data: { left: { title: "La question posée", subtitle: "ce que l'on cherche à montrer", items: ["Comparer des catégories", "Montrer une répartition d'un total", "Observer une évolution dans le temps"] }, right: { title: "Le graphique adapté", subtitle: "le choix pertinent", items: ["Histogramme", "Secteur (peu de catégories)", "Courbe"] } } },
        { type: "text", html: "Le <strong>titre du graphique</strong> doit être informatif. Une légende n'est utile que lorsqu'elle aide réellement à comprendre. Les axes doivent être lisibles, les unités clairement indiquées, et la source des données connue. L'apprenant doit apprendre à <strong>commenter</strong> un graphique en une ou deux phrases : ce qui augmente, ce qui baisse, ce qui domine, ce qui surprend." },
        { type: "keypoints", title: "La méthode en quatre temps", points: [
          "Choisir le graphique selon la nature des données.",
          "Donner un titre explicite.",
          "Vérifier que les valeurs et unités sont lisibles.",
          "Ajouter un commentaire court et factuel.",
        ] },
        { type: "callout", tone: "tip", title: "Développer le jugement", text: "Le formateur peut montrer deux graphiques issus des mêmes données : l'un mal choisi et l'autre pertinent. Un graphique des dépenses par rubrique sera mieux compris avec un histogramme qu'avec une courbe, car il s'agit de comparer des catégories et non une évolution temporelle." },
      ],
    },
    {
      id: "seq-5",
      title: "Présentation PowerPoint professionnelle",
      icon: "Presentation",
      blocks: [
        { type: "text", html: "La présentation PowerPoint doit <strong>soutenir un message oral</strong>. Elle ne doit pas contenir tout le discours. Une diapositive efficace porte une idée principale, quelques mots-clés et un visuel utile. Plus la diapositive est dense, moins l'auditoire écoute l'orateur." },
        { type: "text", html: "Une présentation professionnelle respecte une <strong>cohérence visuelle</strong> : même style de titre, même palette de couleurs, alignements propres, images de qualité et transitions discrètes. Les transitions et animations doivent guider l'attention, non distraire. Le mode présentateur et les notes de l'orateur permettent de garder le fil sans surcharger les diapositives." },
        { type: "infographic", kind: "steps", title: "Une présentation de 5 minutes en 6 diapositives", data: { steps: [
          { title: "Titre" },
          { title: "Contexte" },
          { title: "Problème" },
          { title: "Solution" },
          { title: "Résultats attendus" },
          { title: "Conclusion" },
        ] } },
        { type: "keypoints", title: "Les principes d'une diapositive efficace", points: [
          "Une idée forte par diapositive.",
          "Texte court, lisible et hiérarchisé.",
          "Transitions simples et cohérentes.",
          "Export en PDF pour diffusion.",
        ] },
      ],
    },
    {
      id: "seq-6",
      title: "Export, diffusion et contrôle qualité",
      icon: "Cloud",
      blocks: [
        { type: "text", html: "Avant de diffuser un livrable, l'apprenant doit effectuer un <strong>contrôle qualité</strong>. Ce contrôle porte sur l'orthographe, la cohérence des titres, la pagination, les tableaux, les images, les formules Excel, les graphiques, les liens et les propriétés du fichier." },
        { type: "text", html: "L'<strong>export PDF</strong> permet de préserver la mise en page. Il est recommandé pour la diffusion finale, tandis que les formats modifiables doivent être conservés pour les corrections futures. Le partage cloud nécessite de choisir les bons droits : lecture seule, commentaire ou modification." },
        { type: "infographic", kind: "steps", title: "De la relecture à la diffusion", data: { steps: [
          { title: "Relire et vérifier", text: "le document avant export" },
          { title: "Exporter en PDF", text: "pour la diffusion finale" },
          { title: "Conserver une version modifiable", text: "pour les corrections futures" },
          { title: "Partager", text: "avec des droits adaptés" },
        ] } },
        { type: "text", html: "La compétence professionnelle se voit dans ces derniers gestes : <strong>nommer correctement</strong> les fichiers, produire une version finale, conserver une version modifiable et transmettre un lien fonctionnel au bon destinataire." },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Un dossier final peut contenir Rapport_CERTEL_N2M1_Nom.pdf, Tableau_Gestion_CERTEL_N2M1_Nom.xlsx et Presentation_CERTEL_N2M1_Nom.pdf." },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "match", title: "Choisir le bon graphique",
      instruction: "Reliez chaque besoin d'analyse au type de graphique le plus adapté.",
      pairs: [
        { left: "Comparer des dépenses par rubrique", right: "Histogramme" },
        { left: "Montrer la progression mensuelle des inscriptions", right: "Courbe" },
        { left: "Montrer la répartition en parts d'un total", right: "Secteur" },
      ],
      feedback: "L'histogramme sert à comparer des catégories ; la courbe représente une évolution dans le temps ; le secteur montre une répartition en parts d'un total, à utiliser avec peu de catégories pour rester lisible.",
    },
    {
      id: "f2", kind: "categorize", title: "Manuel ou automatique ?",
      instruction: "Classez chaque pratique selon qu'elle relève d'une production manuelle (à proscrire) ou automatique (professionnelle).",
      categories: ["Manuel (à éviter)", "Automatique (professionnel)"],
      items: [
        { label: "Mettre les titres en gras agrandi à la main", category: "Manuel (à éviter)" },
        { label: "Saisir le sommaire ligne par ligne", category: "Manuel (à éviter)" },
        { label: "Calculer les totaux à la calculatrice puis les taper", category: "Manuel (à éviter)" },
        { label: "Appliquer les styles Titre 1, Titre 2 et Normal", category: "Automatique (professionnel)" },
        { label: "Générer le sommaire à partir des styles", category: "Automatique (professionnel)" },
        { label: "Utiliser =SOMME et =SI dans le tableau", category: "Automatique (professionnel)" },
      ],
      feedback: "Les styles structurent et permettent de générer le sommaire ; les formules assurent la fiabilité des calculs. La production manuelle multiplie les incohérences et les erreurs dans un document long.",
    },
    {
      id: "f3", kind: "order", title: "Transformer un brouillon en rapport professionnel",
      instruction: "Remettez les étapes du TP 1 dans l'ordre logique de production.",
      items: [
        "Appliquer les styles Titre 1, Titre 2 et Normal",
        "Insérer une page de garde simple",
        "Ajouter un en-tête, un pied de page et une numérotation",
        "Insérer un tableau et une image avec légende",
        "Générer un sommaire automatique",
        "Exporter le document en PDF",
      ],
      feedback: "On structure d'abord avec les styles, on ajoute les éléments d'identification et de contenu, puis on génère le sommaire (qui dépend des styles) et enfin on exporte en PDF pour la diffusion.",
    },
    {
      id: "f4", kind: "qcm", multiple: true, title: "Critères de réussite d'un rapport",
      instruction: "Parmi ces éléments, lesquels font partie des critères de réussite d'un rapport professionnel ?",
      options: [
        { text: "Sommaire fonctionnel", correct: true },
        { text: "Titres hiérarchisés", correct: true },
        { text: "Document lisible et homogène", correct: true },
        { text: "Beaucoup d'animations sur chaque page", correct: false },
        { text: "PDF conforme et bien nommé", correct: true },
      ],
      feedback: "Un rapport réussi se reconnaît à un sommaire fonctionnel, des titres hiérarchisés, une lisibilité homogène et un PDF conforme et bien nommé. Les effets décoratifs n'ajoutent rien à la crédibilité.",
    },
    {
      id: "f5", kind: "truefalse", title: "Modifier un style",
      instruction: "Vrai ou faux ?",
      statement: "Si l'on modifie le style Titre 1, tous les titres de niveau 1 du document changent automatiquement.",
      answer: true,
      feedback: "Vrai : c'est l'un des grands avantages des styles. Une modification globale du style se répercute sur tous les titres de même niveau, ce qui garantit la cohérence d'un document long.",
    },
    { id: "q1", kind: "qcm", title: "Rôle d'un style", instruction: "À quoi sert principalement un style dans Word ?", options: [{ text: "Décorer uniquement le texte", correct: false }, { text: "Définir une apparence et une structure réutilisable", correct: true }, { text: "Supprimer le texte", correct: false }, { text: "Convertir le document en image", correct: false }], feedback: "Un style donne une apparence au texte et signale son rôle dans la structure du document." },
    { id: "q2", kind: "qcm", title: "Générer une table des matières", instruction: "Quel outil permet de générer automatiquement une table des matières ?", options: [{ text: "Les styles de titres", correct: true }, { text: "Le correcteur orthographique seul", correct: false }, { text: "La couleur de police", correct: false }, { text: "Le zoom", correct: false }], feedback: "Word s'appuie sur les styles de titres pour construire le sommaire." },
    { id: "q3", kind: "qcm", title: "Calculer une moyenne", instruction: "Quelle formule calcule une moyenne des cellules B2 à B10 ?", options: [{ text: "=SOMME(B2:B10)", correct: false }, { text: "=MOYENNE(B2:B10)", correct: true }, { text: "=SI(B2:B10)", correct: false }, { text: "=TOTAL(B2:B10)", correct: false }], feedback: "MOYENNE additionne les valeurs et divise par leur nombre." },
    { id: "q4", kind: "qcm", title: "La fonction SI", instruction: "La fonction SI sert à :", options: [{ text: "Corriger l'orthographe", correct: false }, { text: "Afficher un résultat selon une condition", correct: true }, { text: "Fusionner des cellules", correct: false }, { text: "Insérer une image", correct: false }], feedback: "SI introduit une logique conditionnelle dans le tableau." },
    { id: "q5", kind: "qcm", title: "Comparer des catégories", instruction: "Quel graphique convient surtout pour comparer des catégories ?", options: [{ text: "Histogramme", correct: true }, { text: "Courbe", correct: false }, { text: "Nuage de points avancé", correct: false }, { text: "Aucun graphique", correct: false }], feedback: "L'histogramme facilite la comparaison entre rubriques." },
    { id: "q6", kind: "qcm", title: "Pourquoi le PDF", instruction: "Pourquoi exporter un rapport en PDF ?", options: [{ text: "Pour préserver la mise en page lors de la diffusion", correct: true }, { text: "Pour supprimer automatiquement les fautes", correct: false }, { text: "Pour empêcher toute lecture", correct: false }, { text: "Pour transformer les formules en graphiques", correct: false }], feedback: "Le PDF conserve généralement l'apparence du document sur différents appareils." },
    { id: "q7", kind: "qcm", title: "Une diapositive professionnelle", instruction: "Une présentation PowerPoint professionnelle doit contenir :", options: [{ text: "Le discours complet sur chaque diapositive", correct: false }, { text: "Une idée claire par diapositive", correct: true }, { text: "Beaucoup d'animations complexes", correct: false }, { text: "Des polices différentes à chaque page", correct: false }], feedback: "La diapositive soutient l'oral ; elle ne doit pas remplacer l'orateur." },
    { id: "q8", kind: "qcm", title: "Le texte alternatif", instruction: "Le texte alternatif d'une image sert notamment à :", options: [{ text: "Améliorer l'accessibilité", correct: true }, { text: "Agrandir automatiquement l'image", correct: false }, { text: "Changer la couleur du fichier", correct: false }, { text: "Supprimer la légende", correct: false }], feedback: "Il décrit l'image pour les personnes utilisant des lecteurs d'écran." },
    { id: "q9", kind: "qcm", title: "La mise en forme conditionnelle", instruction: "La mise en forme conditionnelle permet de :", options: [{ text: "Colorer ou signaler automatiquement selon une règle", correct: true }, { text: "Éteindre l'ordinateur", correct: false }, { text: "Traduire un texte", correct: false }, { text: "Imprimer sans marge", correct: false }], feedback: "Elle attire l'attention sur des valeurs répondant à une condition." },
    { id: "q10", kind: "qcm", title: "Les droits de partage cloud", instruction: "Quel droit cloud convient à une personne qui doit seulement lire un document ?", options: [{ text: "Lecture seule", correct: true }, { text: "Modification complète", correct: false }, { text: "Suppression", correct: false }, { text: "Administration", correct: false }], feedback: "Le droit lecture seule limite les modifications non souhaitées." },
    { id: "q11", kind: "qcm", title: "La formule conditionnelle d'admission", instruction: "Dans un tableau de notes, la note est en cellule C2. Quelle formule affiche « Admis » si la note est supérieure ou égale à 10, sinon « Ajourné » ?", options: [{ text: "=MOYENNE(C2>=10)", correct: false }, { text: "=SI(C2>=10;\"Admis\";\"Ajourné\")", correct: true }, { text: "=NB.SI(C2;\"Admis\")", correct: false }, { text: "=SOMME(C2>=10)", correct: false }], feedback: "La formule =SI(C2>=10;\"Admis\";\"Ajourné\") vérifie d'abord la condition C2>=10 : si elle est vraie, Excel affiche Admis ; sinon, il affiche Ajourné. Les guillemets encadrent les textes." },
    { id: "q12", kind: "qcm", title: "Compter selon un critère", instruction: "Quelle fonction permet de compter le nombre de cellules répondant à un critère ?", options: [{ text: "NB.SI", correct: true }, { text: "MOYENNE", correct: false }, { text: "SOMME", correct: false }, { text: "MAJUSCULE", correct: false }], feedback: "NB.SI compte les cellules d'une plage qui satisfont un critère donné ; SOMME.SI les additionne selon un critère." },
    { id: "q13", kind: "truefalse", title: "Captures et qualité", instruction: "Vrai ou faux ?", statement: "Reprendre des captures d'écran floues dans une présentation est sans conséquence sur sa qualité.", answer: false, feedback: "Faux : la mauvaise qualité visuelle des captures nuit à la crédibilité et à la lisibilité. Il faut privilégier des graphiques propres ou des captures nettes." },
    { id: "q14", kind: "truefalse", title: "Statut manuel ou fonction SI", instruction: "Vrai ou faux ?", statement: "Une cellule de statut écrite manuellement à la place d'une fonction SI est considérée comme pleinement acquise lors de l'évaluation.", answer: false, feedback: "Faux : selon le barème, un statut saisi manuellement à la place d'une fonction SI est considéré comme partiellement acquis. Le fichier Excel doit montrer des calculs automatiques." },
  ],
  caseStudy: {
    title: "Étude de cas — Le rapport mensuel du service administratif",
    scenario:
      "Un service administratif produit chaque mois un rapport en copiant-collant l'ancien fichier. Les titres sont mis en gras manuellement, le sommaire est saisi à la main, les tableaux Excel contiennent des résultats calculés avec une calculatrice, et la présentation finale reprend des captures floues.",
    questions: [
      "Identifiez quatre problèmes de qualité.",
      "Proposez une méthode de production plus professionnelle.",
      "Expliquez comment vérifier le livrable avant diffusion.",
    ],
    corrige: [
      "Les problèmes sont l'absence de styles, le sommaire manuel, les calculs non automatisés et la mauvaise qualité visuelle des captures. On peut aussi relever le risque de versions incohérentes.",
      "La méthode professionnelle consiste à créer un modèle Word, un tableau Excel avec formules, des graphiques propres et une présentation basée sur les résultats synthétiques.",
      "La vérification finale doit porter sur les titres, la pagination, les formules, les graphiques, l'orthographe, les exports PDF et les droits de partage.",
    ],
  },
};
