import type { N1Module } from "../niveau1/types";

/** Niveau 2 — Module 6 : Protection des données et livrable professionnel intégré. */
export const MODULE_6: N1Module = {
  code: "N2-M6",
  slug: "module-6",
  num: 6,
  title: "Protection des données et livrable professionnel intégré",
  subtitle:
    "Consolider une culture de sécurité et de données, puis réunir tous les acquis du Niveau 2 dans un livrable professionnel cohérent.",
  duration: "18 heures · 2 semaines",
  finalite:
    "Consolider une culture de sécurité et de protection des données, puis mobiliser l'ensemble des acquis du Niveau 2 dans un livrable professionnel intégré.",
  objectives: [
    "Identifier les risques liés aux données personnelles et appliquer le principe de minimisation.",
    "Sécuriser ses comptes et reconnaître les tentatives de fraude.",
    "Appliquer les bonnes pratiques de protection des données dans une production numérique.",
    "Planifier et conduire un projet de livrable professionnel intégré.",
    "Mobiliser bureautique, contenus visuels, LMS et IA dans une production cohérente.",
    "Présenter et défendre un livrable selon des critères professionnels.",
  ],
  competences: [
    { group: "Techniques", text: "Distinguer donnée personnelle, donnée sensible et donnée anonymisée ; créer une stratégie de mots de passe et activer la double authentification lorsque c'est possible." },
    { group: "Méthodologiques", text: "Appliquer finalité, minimisation, consentement et conservation limitée ; planifier et conduire le projet de livrable intégré par jalons (cadrage, plan, production, vérification, dépôt, soutenance)." },
    { group: "Sécurité / Qualité", text: "Identifier hameçonnage, ingénierie sociale et usurpation d'identité ; vérifier captures, tableaux et droits de partage, encadrer l'usage de l'IA et produire une note de protection des données." },
    { group: "Transversales", text: "Produire un livrable cohérent intégrant rapport, visuels, formulaire, espace LMS, IA et note de données, puis présenter et défendre sa démarche devant un jury avec responsabilité." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Données personnelles et responsabilité",
      icon: "ShieldCheck",
      blocks: [
        { type: "text", html: "Une <strong>donnée personnelle</strong> est une information se rapportant à une personne identifiée ou identifiable. Un nom, une adresse e-mail, une photographie, un numéro de téléphone, un identifiant ou une combinaison d'informations peuvent permettre d'identifier quelqu'un." },
        { type: "text", html: "La protection des données repose sur des principes simples : <strong>finalité</strong>, <strong>minimisation</strong>, <strong>transparence</strong>, <strong>sécurité</strong>, <strong>durée de conservation limitée</strong> et respect des droits des personnes. Dans un contexte de formation, ces principes concernent les formulaires, listes de présence, notes, productions d'apprenants et traces LMS." },
        { type: "text", html: "L'apprenant doit comprendre qu'il ne faut pas collecter une information simplement parce que l'outil le permet. La question professionnelle est : <em>cette donnée est-elle nécessaire à l'objectif annoncé ?</em>" },
        { type: "infographic", kind: "rules", title: "Les principes clés de la protection des données", data: { rules: [
          { icon: "Target", title: "Finalité claire", text: "Chaque collecte sert un objectif précis et annoncé." },
          { icon: "Minimize2", title: "Collecte limitée", text: "On ne collecte que les données strictement nécessaires." },
          { icon: "Info", title: "Information des personnes", text: "Les personnes savent quelles données sont recueillies et pourquoi." },
          { icon: "Clock", title: "Conservation limitée", text: "Les données ne sont pas gardées plus longtemps que nécessaire." },
          { icon: "KeyRound", title: "Droits d'accès sécurisés", text: "Seules les personnes autorisées accèdent aux données." },
        ] } },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Un formulaire d'inscription à une formation n'a pas forcément besoin de l'adresse complète du participant si les échanges se font par e-mail." },
      ],
    },
    {
      id: "seq-2",
      title: "Sécurité numérique appliquée",
      icon: "Lock",
      blocks: [
        { type: "text", html: "La sécurité numérique commence par les <strong>comptes</strong>. Un mot de passe robuste, unique et protégé limite les risques d'accès non autorisé. Lorsque c'est possible, l'<strong>authentification à deux facteurs</strong> ajoute une couche de protection." },
        { type: "text", html: "Les fraudes prennent souvent la forme de messages urgents, de liens suspects, de pièces jointes inattendues ou de demandes d'informations confidentielles. L'<strong>ingénierie sociale</strong> exploite la confiance, la peur, l'urgence ou l'autorité." },
        { type: "text", html: "Réagir à un incident suppose de ne pas paniquer : ne pas cliquer davantage, faire une capture si nécessaire, signaler, changer les accès compromis et prévenir les personnes concernées." },
        { type: "infographic", kind: "categories", title: "Cinq réflexes de sécurité", data: { columns: [
          { title: "Protéger ses accès", accent: "#6D5DF5", items: [{ label: "Mots de passe uniques" }, { label: "Double authentification" }] },
          { title: "Rester prudent", accent: "#0891B2", items: [{ label: "Vérification des expéditeurs" }, { label: "Prudence avec liens et pièces jointes" }] },
          { title: "Réagir", accent: "#16A34A", items: [{ label: "Signalement des incidents" }] },
        ] } },
        { type: "callout", tone: "warn", title: "Exemple pédagogique", text: "Un message demandant de « confirmer immédiatement votre mot de passe » en suivant un lien doit être traité comme suspect." },
      ],
    },
    {
      id: "seq-3",
      title: "Protection des données dans les livrables",
      icon: "EyeOff",
      blocks: [
        { type: "text", html: "Un livrable professionnel peut contenir des données personnelles dans un rapport, un tableau, un formulaire, une capture d'écran ou une production IA. L'apprenant doit <strong>repérer ces données avant diffusion</strong>." },
        { type: "text", html: "L'<strong>anonymisation</strong> ou la <strong>pseudonymisation</strong> peuvent être nécessaires. Les captures d'écran doivent être vérifiées pour éviter les noms, adresses, notifications ou informations confidentielles visibles." },
        { type: "text", html: "L'usage de l'IA doit également être encadré : ne pas intégrer de données sensibles dans les requêtes et documenter les corrections humaines." },
        { type: "infographic", kind: "steps", title: "Vérifier un livrable avant diffusion", data: { steps: [
          { title: "Relire les tableaux et captures", text: "repérer les données personnelles visibles" },
          { title: "Masquer les données non nécessaires", text: "anonymiser ou pseudonymiser" },
          { title: "Limiter les droits de partage", text: "n'ouvrir l'accès qu'aux personnes concernées" },
          { title: "Documenter l'usage de l'IA", text: "préciser la démarche et les corrections" },
        ] } },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Avant de présenter un tableau de notes, on peut remplacer les noms par des codes anonymes si les identités ne sont pas nécessaires." },
      ],
    },
    {
      id: "seq-4",
      title: "Projet de livrable intégré",
      icon: "Boxes",
      blocks: [
        { type: "text", html: "Le projet de livrable intégré est le <strong>fil rouge</strong> du module. Il oblige l'apprenant à mobiliser les acquis : rapport Word structuré, tableau Excel avec indicateurs, visuel ou infographie, formulaire, espace LMS ou mini-parcours, activité interactive, usage de l'IA documenté et note de protection des données." },
        { type: "text", html: "Le projet doit répondre à un <strong>besoin réel ou réaliste</strong>. Il peut s'agir d'un mini-dispositif de formation, d'un kit de communication, d'un dossier d'activité ou d'un parcours d'initiation." },
        { type: "text", html: "Le formateur accompagne par <strong>jalons</strong> : cadrage, plan, production, vérification, dépôt, soutenance." },
        { type: "infographic", kind: "steps", title: "Conduire le projet par jalons", data: { steps: [
          { title: "Cadrer le besoin et le public" },
          { title: "Définir les livrables" },
          { title: "Planifier les tâches" },
          { title: "Contrôler qualité, données et sources" },
          { title: "Présenter et défendre" },
        ] } },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Thème possible : « Sensibilisation des enseignants à la sécurité numérique ». Le livrable comprend rapport, affiche, formulaire d'inscription, mini-cours LMS, quiz et note d'usage IA." },
      ],
    },
    {
      id: "seq-5",
      title: "Déroulement pédagogique conseillé",
      icon: "CalendarDays",
      blocks: [
        { type: "text", html: "Le module alterne <strong>apports</strong> sur la sécurité et les données et <strong>production accompagnée</strong> du projet final de Niveau 2." },
        { type: "infographic", kind: "table", title: "Six séances de 3 heures", data: { columns: ["Séance", "Objectifs dominants", "Production attendue"], rows: [
          ["Séance 1", "Données personnelles, finalité et minimisation", "Fiche d'analyse de données"],
          ["Séance 2", "Sécurité des comptes, phishing et réaction à incident", "Check-list sécurité"],
          ["Séance 3", "Audit d'un formulaire et d'un espace cloud", "Fiche d'audit"],
          ["Séance 4", "Cadrage du livrable intégré", "Plan projet"],
          ["Séance 5", "Production et contrôle qualité", "Livrable V1"],
          ["Séance 6", "Soutenance blanche et corrections", "Livrable finalisé"],
        ] } },
      ],
    },
    {
      id: "seq-6",
      title: "Travaux pratiques et productions attendues",
      icon: "ClipboardCheck",
      blocks: [
        { type: "text", html: "Trois activités structurent la pratique du module : une <strong>étude de cas sécurité</strong>, un <strong>audit de protection des données</strong> et le <strong>projet fil rouge intégré</strong>." },
        { type: "keypoints", title: "Étude de cas sécurité — analyser des messages douteux", points: [
          "Repérer l'expéditeur et le domaine.",
          "Identifier les indices d'urgence ou de menace.",
          "Analyser liens et pièces jointes.",
          "Proposer une réaction appropriée.",
        ] },
        { type: "callout", tone: "tip", title: "Production attendue", text: "Une bonne réponse repère l'urgence artificielle, le lien suspect, les fautes, la demande de données confidentielles et recommande de ne pas cliquer, de signaler et de vérifier par un canal officiel." },
        { type: "keypoints", title: "Audit de protection des données — formulaire ou dossier cloud", points: [
          "Lister les données collectées.",
          "Relier chaque donnée à la finalité.",
          "Identifier les données inutiles.",
          "Vérifier les droits de partage.",
          "Proposer des corrections.",
        ] },
        { type: "callout", tone: "tip", title: "Production attendue", text: "Les données inutiles sont retirées ou rendues facultatives, les droits sont limités et un message d'information est ajouté." },
      ],
    },
    {
      id: "seq-7",
      title: "Le projet fil rouge et son évaluation",
      icon: "Trophy",
      blocks: [
        { type: "text", html: "L'apprenant produit son <strong>livrable final de Niveau 2</strong>, un dossier professionnel intégré qui mobilise toutes les compétences acquises au cours du niveau." },
        { type: "infographic", kind: "steps", title: "Les sept productions du livrable", data: { steps: [
          { title: "Thème et public", text: "choisir un sujet et définir le public" },
          { title: "Rapport Word", text: "structuré et exporté en PDF" },
          { title: "Tableau Excel", text: "ou synthèse de données" },
          { title: "Visuel et formulaire", text: "infographie et formulaire en ligne" },
          { title: "Espace LMS", text: "ressource, activité et quiz" },
          { title: "Usage de l'IA", text: "amélioration documentée" },
          { title: "Note de données", text: "protection des données et présentation" },
        ] } },
        { type: "infographic", kind: "table", title: "Barème de l'évaluation sommative (100 points)", data: { columns: ["Critère", "Points"], rows: [
          ["Cadrage, cohérence et besoin du public", "10"],
          ["Rapport et éléments bureautiques", "15"],
          ["Contenus visuels et formulaire", "15"],
          ["Espace LMS, activité et quiz", "20"],
          ["Usage documenté et critique de l'IA", "15"],
          ["Protection des données et sécurité", "15"],
          ["Soutenance et professionnalisme", "10"],
          ["Total", "100"],
        ] } },
        { type: "callout", tone: "info", title: "Ce que vise un livrable excellent", text: "Le rapport explique, le visuel communique, le formulaire collecte, le LMS organise, le quiz évalue, l'IA soutient et la note de données sécurise. Le jury doit pouvoir accéder aux fichiers sans difficulté et comprendre la logique du projet en quelques minutes." },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "categorize", title: "Données utiles ou inutiles ?",
      instruction: "Pour un formulaire de participation à un webinaire, classez chaque donnée en « utile » ou « probablement inutile ».",
      categories: ["Utile", "Probablement inutile"],
      items: [
        { label: "Nom et prénom", category: "Utile" },
        { label: "Adresse e-mail", category: "Utile" },
        { label: "Structure ou choix de session", category: "Utile" },
        { label: "Adresse postale complète", category: "Probablement inutile" },
        { label: "Numéro d'identité", category: "Probablement inutile" },
        { label: "Situation familiale", category: "Probablement inutile" },
      ],
      feedback: "Pour un webinaire en ligne, nom, e-mail et structure (ou choix de session) suffisent. L'adresse complète, le numéro d'identité ou la situation familiale ne sont pas nécessaires, sauf justification particulière : c'est le principe de minimisation.",
    },
    {
      id: "f2", kind: "qcm", multiple: true, title: "Reconnaître un message de phishing",
      instruction: "Quels indices doivent vous faire suspecter un message frauduleux ? (Plusieurs réponses.)",
      options: [
        { text: "Expéditeur suspect", correct: true },
        { text: "Urgence excessive", correct: true },
        { text: "Lien étrange ou pièce jointe inattendue", correct: true },
        { text: "Fautes inhabituelles", correct: true },
        { text: "Demande de mot de passe ou promesse irréaliste", correct: true },
        { text: "Signature professionnelle attendue de votre établissement", correct: false },
      ],
      feedback: "Un message frauduleux cumule souvent plusieurs indices : expéditeur suspect, urgence excessive, lien étrange, pièce jointe inattendue, fautes inhabituelles, demande de mot de passe ou promesse irréaliste. Une signature légitime attendue n'est pas un indice de fraude.",
    },
    {
      id: "f3", kind: "order", title: "Réagir à un incident de sécurité",
      instruction: "Remettez dans l'ordre les bons réflexes face à un message ou un incident suspect.",
      items: ["Ne pas cliquer davantage", "Faire une capture si nécessaire", "Signaler l'incident", "Changer les accès compromis", "Prévenir les personnes concernées"],
      feedback: "On évite d'abord d'aggraver la situation en ne cliquant plus, on garde une trace par capture, on signale, on change les accès compromis puis on prévient les personnes concernées.",
    },
    {
      id: "f4", kind: "order", title: "Conduire le projet par jalons",
      instruction: "Remettez les jalons du projet de livrable intégré dans le bon ordre.",
      items: ["Cadrer le besoin et le public", "Définir les livrables", "Planifier les tâches", "Contrôler qualité, données et sources", "Présenter et défendre"],
      feedback: "Le projet se conduit du cadrage à la soutenance : on cadre le besoin et le public, on définit les livrables, on planifie les tâches, on contrôle la qualité, les données et les sources, puis on présente et on défend.",
    },
    {
      id: "f5", kind: "match", title: "Principes de protection des données",
      instruction: "Associez chaque principe à sa définition.",
      pairs: [
        { left: "Finalité", right: "La collecte sert un objectif précis et annoncé." },
        { left: "Minimisation", right: "On ne collecte que les données nécessaires." },
        { left: "Transparence", right: "Les personnes sont informées de l'usage de leurs données." },
        { left: "Conservation limitée", right: "Les données ne sont pas gardées plus longtemps que nécessaire." },
      ],
      feedback: "La finalité justifie la collecte, la minimisation la limite, la transparence informe les personnes et la conservation limitée évite de garder les données indéfiniment.",
    },
    {
      id: "f6", kind: "categorize", title: "Vérifier un livrable avant diffusion",
      instruction: "Classez chaque bonne pratique selon qu'elle concerne les contenus visibles ou le partage et l'IA.",
      categories: ["Contenus visibles", "Partage et IA"],
      items: [
        { label: "Relire les tableaux et captures", category: "Contenus visibles" },
        { label: "Masquer les données non nécessaires", category: "Contenus visibles" },
        { label: "Limiter les droits de partage", category: "Partage et IA" },
        { label: "Documenter l'usage de l'IA", category: "Partage et IA" },
      ],
      feedback: "Avant diffusion, on vérifie les contenus visibles (relire tableaux et captures, masquer les données non nécessaires) et on encadre le partage et l'IA (limiter les droits, documenter l'usage de l'IA).",
    },
    { id: "q1", kind: "qcm", title: "Donnée personnelle", instruction: "Une donnée personnelle permet :", options: [{ text: "D'identifier directement ou indirectement une personne", correct: true }, { text: "De changer la couleur d'un document", correct: false }, { text: "D'additionner des cellules", correct: false }, { text: "De compresser une image", correct: false }], feedback: "L'identification peut être directe ou indirecte." },
    { id: "q2", kind: "qcm", title: "Principe de minimisation", instruction: "Le principe de minimisation signifie :", options: [{ text: "Collecter seulement les données nécessaires", correct: true }, { text: "Collecter toutes les données possibles", correct: false }, { text: "Supprimer les objectifs", correct: false }, { text: "Masquer le formulaire", correct: false }], feedback: "La donnée doit être justifiée par la finalité." },
    { id: "q3", kind: "qcm", title: "Double authentification", instruction: "La double authentification sert à :", options: [{ text: "Ajouter une protection au compte", correct: true }, { text: "Supprimer le mot de passe", correct: false }, { text: "Partager le compte", correct: false }, { text: "Rendre le compte public", correct: false }], feedback: "Elle ajoute un second facteur de vérification." },
    { id: "q4", kind: "qcm", title: "Demande de mot de passe", instruction: "Un message demandant un mot de passe par e-mail doit être :", options: [{ text: "Considéré comme suspect", correct: true }, { text: "Suivi immédiatement", correct: false }, { text: "Transféré à tous", correct: false }, { text: "Imprimé seulement", correct: false }], feedback: "Les mots de passe ne doivent pas être transmis par e-mail." },
    { id: "q5", kind: "qcm", title: "Avant de partager un dossier cloud", instruction: "Avant de partager un dossier cloud, il faut vérifier :", options: [{ text: "Les droits d'accès", correct: true }, { text: "La couleur du clavier", correct: false }, { text: "Le volume du haut-parleur", correct: false }, { text: "Le fond d'écran", correct: false }], feedback: "Les droits déterminent qui peut voir ou modifier." },
    { id: "q6", kind: "qcm", title: "Capture d'écran", instruction: "Une capture d'écran peut contenir :", options: [{ text: "Des données personnelles visibles", correct: true }, { text: "Un antivirus obligatoire", correct: false }, { text: "Une formule cachée toujours sûre", correct: false }, { text: "Aucun risque", correct: false }], feedback: "Il faut vérifier les noms, e-mails et notifications visibles." },
    { id: "q7", kind: "qcm", title: "IA et données sensibles", instruction: "L'usage de l'IA avec des données sensibles doit être :", options: [{ text: "Évité ou strictement encadré", correct: true }, { text: "Toujours public", correct: false }, { text: "Jamais vérifié", correct: false }, { text: "Sans responsabilité", correct: false }], feedback: "La confidentialité doit être protégée." },
    { id: "q8", kind: "qcm", title: "Livrable intégré", instruction: "Un livrable intégré doit :", options: [{ text: "Mobiliser plusieurs compétences de façon cohérente", correct: true }, { text: "Être seulement décoratif", correct: false }, { text: "Exclure toute vérification", correct: false }, { text: "Ne contenir qu'une image", correct: false }], feedback: "Il montre une compétence globale." },
    { id: "q9", kind: "qcm", title: "Réagir à un incident", instruction: "Réagir à un incident consiste notamment à :", options: [{ text: "Signaler et changer les accès si nécessaire", correct: true }, { text: "Cliquer plusieurs fois", correct: false }, { text: "Cacher l'incident", correct: false }, { text: "Partager le lien suspect", correct: false }], feedback: "La réaction doit limiter les dégâts." },
    { id: "q10", kind: "qcm", title: "Note de protection des données", instruction: "La note de protection des données sert à :", options: [{ text: "Expliquer quelles données sont collectées et protégées", correct: true }, { text: "Remplacer les contenus", correct: false }, { text: "Augmenter la taille du fichier", correct: false }, { text: "Supprimer le projet", correct: false }], feedback: "Elle montre la responsabilité du producteur." },
    { id: "q11", kind: "truefalse", title: "Collecter par défaut", instruction: "Vrai ou faux ?", statement: "Il faut collecter une information dès que l'outil le permet, même sans objectif précis.", answer: false, feedback: "Faux : on ne collecte une donnée que si elle est nécessaire à l'objectif annoncé. C'est le principe de minimisation." },
    { id: "q12", kind: "truefalse", title: "Transparence sur l'IA", instruction: "Vrai ou faux ?", statement: "Une note de transparence sur l'usage de l'IA peut indiquer que les informations produites ont été vérifiées et validées par l'auteur.", answer: true, feedback: "Vrai : par exemple « L'IA générative a été utilisée pour proposer un plan initial et reformuler certains passages ; les informations ont été vérifiées, corrigées et validées par l'auteur. »" },
    { id: "q13", kind: "truefalse", title: "Ingénierie sociale", instruction: "Vrai ou faux ?", statement: "L'ingénierie sociale exploite la confiance, la peur, l'urgence ou l'autorité pour tromper la personne.", answer: true, feedback: "Vrai : les fraudes jouent sur les émotions et l'autorité, d'où l'importance de la prudence et de la vérification." },
  ],
  caseStudy: {
    title: "Étude de cas — Un livrable techniquement réussi mais à risques",
    scenario:
      "Un apprenant produit un excellent mini-cours LMS, mais il partage le dossier cloud en modification publique, laisse des noms réels dans les captures d'écran, utilise l'IA sans le mentionner et collecte des dates de naissance dans son formulaire sans justification.",
    questions: [
      "Quels éléments empêchent la validation complète du livrable ?",
      "Comment corriger le projet ?",
      "Quelle conclusion formuler au jury ?",
    ],
    corrige: [
      "Les problèmes portent sur les droits de partage (modification publique), les données personnelles visibles dans les captures, le manque de transparence sur l'usage de l'IA et la collecte excessive de données (dates de naissance non justifiées).",
      "Il faut limiter les droits de partage, anonymiser les captures, ajouter une note d'usage de l'IA et retirer les champs inutiles du formulaire.",
      "La conclusion doit reconnaître les corrections apportées et montrer que la qualité technique doit toujours être accompagnée d'une responsabilité numérique : produire bien, utilement, en sécurité, avec respect des données, des sources, des personnes et des règles de transparence.",
    ],
  },
};
