import type { N1Module } from "../niveau1/types";

/** Niveau 2 — Module 5 : Intelligence artificielle générative appliquée. */
export const MODULE_5: N1Module = {
  code: "N2-M5",
  slug: "module-5",
  num: 5,
  title: "Intelligence artificielle générative appliquée",
  subtitle: "Mobiliser l'IA générative de façon raisonnée et professionnelle : prompter, vérifier, corriger et documenter.",
  duration: "18 heures · 2 semaines",
  finalite:
    "Former un utilisateur responsable capable d'utiliser l'IA comme assistant, sans renoncer à la vérification humaine ni à l'éthique.",
  objectives: [
    "Distinguer les principaux outils d'IA générative et leurs usages appropriés.",
    "Rédiger des prompts clairs, contextualisés et itératifs.",
    "Évaluer la fiabilité d'une réponse d'IA et corriger erreurs, biais ou hallucinations.",
    "Utiliser l'IA pour produire et améliorer un support de cours, un rapport ou une activité.",
    "Adopter une posture éthique et responsable : transparence, droits, données, citation.",
    "Documenter et justifier l'usage de l'IA dans une production professionnelle.",
  ],
  competences: [
    { group: "Techniques", text: "Choisir un outil d'IA selon le besoin et construire un prompt avec rôle, contexte, tâche, format, contraintes et exemples." },
    { group: "Méthodologiques", text: "Comparer plusieurs réponses, les améliorer par itération, vérifier les informations produites avec des sources fiables et stabiliser une sortie brute en production professionnelle." },
    { group: "Sécurité & Qualité", text: "Ne pas saisir de données sensibles dans un outil non maîtrisé, repérer hallucinations et biais, et garantir la fiabilité du livrable final." },
    { group: "Transversales", text: "Adopter une posture critique, productive et responsable : transparence, citation des sources et rédaction d'une note d'usage de l'IA." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Comprendre ce que l'IA peut et ne peut pas faire",
      icon: "BrainCircuit",
      blocks: [
        { type: "text", html: "Une IA générative produit des textes, images, synthèses, plans ou idées à partir de <strong>modèles statistiques</strong> entraînés sur de grands volumes de données. Elle ne « sait » pas au sens humain : elle calcule des réponses probables selon le contexte fourni." },
        { type: "text", html: "Cette distinction est essentielle. L'IA peut produire une réponse <strong>convaincante mais fausse</strong>. Elle peut aussi refléter des biais présents dans ses données ou dans la formulation du prompt. L'utilisateur reste responsable de la vérification et de la décision." },
        { type: "callout", tone: "warn", title: "Deux excès à éviter", text: "Présenter l'IA comme une magie qui remplace l'expertise, ou la rejeter totalement. La posture attendue est critique, productive et responsable." },
        { type: "keypoints", title: "À retenir", points: [
          "L'IA est un assistant, non une autorité finale.",
          "Risque d'hallucination : une réponse plausible n'est pas forcément vraie.",
          "Nécessité de vérifier systématiquement.",
          "La responsabilité reste humaine.",
        ] },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Une IA peut proposer un plan de formation en quelques secondes, mais le formateur doit vérifier la pertinence, les sources, la progression pédagogique et l'adaptation au public." },
      ],
    },
    {
      id: "seq-2",
      title: "Anatomie d'un prompt efficace",
      icon: "FileText",
      blocks: [
        { type: "text", html: "Un prompt est une <strong>consigne</strong>. Plus il est précis, plus la réponse a des chances d'être utile. Un prompt efficace indique le rôle attendu, le contexte, la tâche, le public, le format, les contraintes et parfois un exemple." },
        { type: "text", html: "Le <strong>prompting itératif</strong> consiste à améliorer progressivement la réponse. On peut demander de simplifier, de détailler, de reformuler, de produire un tableau, de proposer une grille d'évaluation ou de vérifier la cohérence." },
        { type: "infographic", kind: "categories", title: "Les composantes d'un bon prompt", data: { columns: [
          { title: "Cadrage", accent: "#6D5DF5", items: [{ label: "Rôle", hint: "« Agis comme un formateur… »" }, { label: "Contexte", hint: "public, durée, niveau" }] },
          { title: "Commande", accent: "#0891B2", items: [{ label: "Tâche", hint: "produire, corriger, comparer, synthétiser" }, { label: "Format", hint: "tableau, plan, grille, fiche" }] },
          { title: "Cadre", accent: "#16A34A", items: [{ label: "Contraintes", hint: "nombre de lignes, style, références, niveau de langue" }, { label: "Exemple", hint: "un modèle de sortie attendue" }] },
        ] } },
        { type: "callout", tone: "warn", text: "La qualité du prompt n'élimine pas la vérification. Elle améliore la pertinence de la première réponse, mais le contrôle humain reste nécessaire." },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "« Agis comme un formateur CERTEL. Prépare une activité de 30 minutes pour des débutants sur la sécurité des mots de passe, avec objectif, consignes, corrigé et barème. »" },
      ],
    },
    {
      id: "seq-3",
      title: "Vérifier, corriger et stabiliser une réponse",
      icon: "ShieldCheck",
      blocks: [
        { type: "text", html: "La vérification d'une réponse d'IA doit être <strong>méthodique</strong>. L'apprenant repère les affirmations factuelles, vérifie les dates et les chiffres, recherche des sources fiables, corrige les formulations imprécises et signale les limites." },
        { type: "text", html: "Les <strong>hallucinations</strong> peuvent prendre la forme de références inventées, de citations inexistantes ou d'explications très sûres mais fausses. Il faut apprendre à douter intelligemment." },
        { type: "infographic", kind: "steps", title: "La démarche de vérification", data: { steps: [
          { title: "Identifier", text: "les faits à vérifier" },
          { title: "Recouper", text: "avec une source fiable" },
          { title: "Corriger", text: "les erreurs repérées" },
          { title: "Documenter", text: "ajouter une note de transparence" },
        ] } },
        { type: "text", html: "La <strong>stabilisation</strong> consiste à transformer une sortie brute en production professionnelle : correction, reformulation, adaptation au public, ajout de sources, suppression de données sensibles et note d'usage de l'IA." },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Si l'IA cite une loi ou un rapport, l'apprenant doit retrouver le document original ou une source institutionnelle avant de l'utiliser." },
      ],
    },
    {
      id: "seq-4",
      title: "L'IA au service de la préparation pédagogique et professionnelle",
      icon: "Presentation",
      blocks: [
        { type: "text", html: "L'IA peut aider à préparer un plan de cours, une grille d'évaluation, un questionnaire, une synthèse, une introduction ou des variantes d'exercices. Elle peut également améliorer la clarté d'un texte ou adapter un contenu à un public." },
        { type: "text", html: "L'usage professionnel exige de garder une <strong>trace</strong> : prompt utilisé, réponse obtenue, corrections effectuées, sources vérifiées. Cette documentation montre que l'apprenant ne copie pas passivement mais pilote le processus." },
        { type: "infographic", kind: "two-columns", title: "Ce que l'IA peut produire et ce qu'il faut garder", data: { left: { title: "Productions possibles", subtitle: "avec assistance IA", items: ["Plan de cours", "Quiz et variantes", "Résumé et reformulation", "Grille d'évaluation", "Adaptation à un public"] }, right: { title: "Trace à conserver", subtitle: "dossier avant/après IA", items: ["Prompt utilisé", "Réponse brute obtenue", "Corrections effectuées", "Sources vérifiées", "Note de transparence"] } } },
        { type: "callout", tone: "tip", title: "Idée de dispositif", text: "Le formateur peut demander un dossier « avant/après IA » pour rendre visible l'apport de l'apprenant." },
        { type: "callout", tone: "example", title: "Exemple pédagogique", text: "Un apprenant demande à l'IA de produire un QCM, puis corrige les questions trop faciles, ajoute des rétroactions et vérifie les définitions." },
      ],
    },
    {
      id: "seq-5",
      title: "Déroulement pédagogique et productions attendues",
      icon: "ListChecks",
      blocks: [
        { type: "text", html: "Le module combine démonstrations, ateliers de prompts, vérification documentaire, production professionnelle et débat éthique. Il s'étale sur <strong>six séances de trois heures</strong>, chacune débouchant sur une production concrète." },
        { type: "infographic", kind: "table", title: "Les six séances", data: { columns: ["Séance", "Objectifs dominants", "Production attendue"], rows: [
          ["1", "Comprendre l'IA générative, usages et limites", "Carte des usages possibles"],
          ["2", "Prompts structurés et itération", "Bibliothèque de prompts"],
          ["3", "Vérification et correction de réponses", "Fiche de vérification"],
          ["4", "Production d'un support assisté par IA", "Support V1"],
          ["5", "Éthique, données, citation et transparence", "Note d'usage responsable"],
          ["6", "Présentation et amélioration", "Livrable final"],
        ] } },
        { type: "keypoints", title: "Trois temps forts en travaux pratiques", points: [
          "Atelier 1 — Bibliothèque de prompts : créer dix prompts réutilisables, contextualisés et améliorés après analyse.",
          "Atelier 2 — Vérification d'une réponse IA : repérer erreurs et approximations, recouper avec des sources fiables et rédiger une note de vérification.",
          "Mini-projet — Support professionnel assisté par IA : produire un livrable corrigé, enrichi, vérifié et accompagné d'une note de transparence.",
        ] },
        { type: "callout", tone: "tip", title: "Critère central", text: "Le livrable final doit porter la marque d'un travail humain : choix, correction, contextualisation, sources et responsabilité." },
      ],
    },
    {
      id: "seq-6",
      title: "Éthique, données et transparence",
      icon: "Lock",
      blocks: [
        { type: "text", html: "L'usage responsable de l'IA repose sur trois piliers indissociables : la <strong>vérification</strong>, la <strong>transparence</strong> et la <strong>protection des données</strong>. Ces dimensions s'appuient sur les cadres UNESCO de compétences en IA, sur DigComp 2.2 pour l'usage critique des technologies émergentes et sur DigCompEdu pour la production de ressources et l'évaluation." },
        { type: "infographic", kind: "rules", title: "Les règles de l'usage responsable", data: { rules: [
          { icon: "CheckCircle", title: "Vérifier", text: "Recouper les faits, les chiffres et les références avec des sources fiables avant d'utiliser une réponse." },
          { icon: "Eye", title: "Être transparent", text: "Rédiger une note indiquant comment l'IA a été utilisée et ce qui a été corrigé par l'auteur." },
          { icon: "ShieldAlert", title: "Protéger les données", text: "Ne pas saisir de données personnelles d'apprenants dans un outil non maîtrisé ; appliquer la minimisation." },
          { icon: "BookMarked", title: "Citer", text: "Remplacer les références inventées par des sources réelles et créditer ce qui provient d'autrui." },
        ] } },
        { type: "callout", tone: "warn", title: "Données sensibles", text: "On ne maîtrise pas toujours le traitement, la conservation et la réutilisation des données transmises à un outil d'IA. Le principe de minimisation impose de ne transmettre que ce qui est nécessaire et autorisé." },
        { type: "callout", tone: "example", title: "Exemple de note de transparence", text: "« L'IA a été utilisée pour proposer un plan et une première reformulation. Les informations ont été vérifiées, corrigées et adaptées par l'auteur. »" },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "qcm", title: "Améliorer un prompt",
      instruction: "On vous donne le prompt : « Fais-moi un cours sur Excel ». Quels éléments faut-il ajouter pour l'améliorer ?",
      multiple: true,
      options: [
        { text: "Le rôle attendu (« Agis comme un formateur en bureautique »)", correct: true },
        { text: "Le public et la durée (débutants, 2 heures)", correct: true },
        { text: "Les objectifs et le format (activité, QCM, corrigé)", correct: true },
        { text: "Une couleur de fond pour la réponse", correct: false },
        { text: "Aucune précision : le prompt est déjà complet", correct: false },
      ],
      feedback: "Un prompt amélioré précise le rôle, le public, la durée, les objectifs et le format : « Agis comme un formateur en bureautique. Prépare une séance de 2 heures pour débutants sur SOMME, MOYENNE et SI dans Excel, avec objectifs, activité pratique, QCM de 5 questions et corrigé. »",
    },
    {
      id: "f2", kind: "qcm", title: "Signes d'une hallucination possible",
      instruction: "Quels signes peuvent indiquer qu'une réponse d'IA doit être vérifiée ?",
      multiple: true,
      options: [
        { text: "Des références sans lien vérifiable", correct: true },
        { text: "Des dates précises non sourcées", correct: true },
        { text: "Une affirmation très catégorique ou un chiffre surprenant", correct: true },
        { text: "Un auteur inconnu ou une contradiction avec une source fiable", correct: true },
        { text: "Une phrase bien tournée et fluide", correct: false },
      ],
      feedback: "Références sans lien, dates non sourcées, affirmations catégoriques, chiffres surprenants, auteurs inconnus ou contradictions imposent la vérification. Ces signes ne prouvent pas que la réponse est fausse, mais ils déclenchent le contrôle.",
    },
    {
      id: "f3", kind: "truefalse", title: "Données sensibles dans l'IA",
      instruction: "Vrai ou faux ?",
      statement: "On peut saisir librement les données personnelles d'apprenants dans un outil d'IA non maîtrisé.",
      answer: false,
      feedback: "Faux : on ne maîtrise pas toujours le traitement, la conservation et la réutilisation de ces données. Le principe de minimisation impose de ne transmettre que ce qui est nécessaire et autorisé.",
    },
    {
      id: "f4", kind: "categorize", title: "Trier une sortie IA à vérifier",
      instruction: "Pour chaque élément d'une réponse d'IA, indiquez s'il doit être vérifié en priorité ou s'il relève simplement du style.",
      categories: ["À vérifier en priorité", "Relève du style"],
      items: [
        { label: "Une date précise citée sans source", category: "À vérifier en priorité" },
        { label: "Un chiffre statistique surprenant", category: "À vérifier en priorité" },
        { label: "Une référence à un rapport institutionnel", category: "À vérifier en priorité" },
        { label: "La tournure fluide d'une phrase", category: "Relève du style" },
        { label: "Le choix d'un synonyme", category: "Relève du style" },
      ],
      feedback: "Une réponse d'IA doit être vérifiée surtout lorsqu'elle contient des faits, des chiffres ou des références. Le simple style de phrase ne nécessite pas de contrôle factuel.",
    },
    {
      id: "f5", kind: "order", title: "Construire un livrable assisté par IA",
      instruction: "Remettez dans le bon ordre les étapes de production d'un livrable professionnel assisté par IA.",
      items: [
        "Rédiger le besoin et le prompt initial complet",
        "Générer une première version (réponse brute)",
        "Vérifier et corriger les informations",
        "Enrichir et adapter au public",
        "Ajouter une note de transparence et les sources",
        "Présenter le livrable et le processus",
      ],
      feedback: "On part du besoin et du prompt, on génère une première version, puis on vérifie, corrige, enrichit, on documente l'usage de l'IA et enfin on présente le livrable et sa démarche.",
    },
    {
      id: "f6", kind: "match", title: "Associer chaque composante du prompt à son rôle",
      instruction: "Reliez chaque composante d'un prompt à ce qu'elle précise.",
      pairs: [
        { left: "Rôle", right: "« Agis comme un formateur… »" },
        { left: "Contexte", right: "Public, durée, niveau" },
        { left: "Tâche", right: "Produire, corriger, comparer, synthétiser" },
        { left: "Format", right: "Tableau, plan, grille, fiche" },
        { left: "Contraintes", right: "Nombre de lignes, style, références, niveau de langue" },
      ],
      feedback: "Un bon prompt précise le rôle, le contexte, la tâche, le format et les contraintes. Ces éléments améliorent la pertinence de la réponse.",
    },
    {
      id: "q1", kind: "qcm", title: "Qu'est-ce qu'un prompt ?",
      instruction: "Un prompt est :",
      options: [
        { text: "Une consigne donnée à l'IA", correct: true },
        { text: "Un virus", correct: false },
        { text: "Une formule Excel", correct: false },
        { text: "Un type de clavier", correct: false },
      ],
      feedback: "Le prompt guide la réponse du système.",
    },
    {
      id: "q2", kind: "qcm", title: "Une hallucination de l'IA",
      instruction: "Une hallucination de l'IA est :",
      options: [
        { text: "Une réponse fausse ou inventée présentée comme plausible", correct: true },
        { text: "Une image très colorée", correct: false },
        { text: "Un mot de passe", correct: false },
        { text: "Une sauvegarde", correct: false },
      ],
      feedback: "La plausibilité ne garantit pas la vérité.",
    },
    {
      id: "q3", kind: "qcm", title: "La responsabilité finale",
      instruction: "La responsabilité finale d'un livrable assisté par IA revient :",
      options: [
        { text: "À l'utilisateur qui le valide", correct: true },
        { text: "Uniquement à la machine", correct: false },
        { text: "Au hasard", correct: false },
        { text: "À la police du document", correct: false },
      ],
      feedback: "L'humain reste responsable de vérifier et d'assumer la production.",
    },
    {
      id: "q4", kind: "qcm", title: "Ce que précise un bon prompt",
      instruction: "Un bon prompt précise souvent :",
      options: [
        { text: "Rôle, contexte, tâche, format, contraintes", correct: true },
        { text: "Seulement une couleur", correct: false },
        { text: "Un mot unique", correct: false },
        { text: "Rien", correct: false },
      ],
      feedback: "Ces éléments améliorent la pertinence de la réponse.",
    },
    {
      id: "q5", kind: "qcm", title: "Avant d'utiliser une donnée personnelle",
      instruction: "Avant d'utiliser une donnée personnelle dans l'IA, il faut :",
      options: [
        { text: "Vérifier la nécessité et l'autorisation", correct: true },
        { text: "La publier librement", correct: false },
        { text: "La copier partout", correct: false },
        { text: "L'envoyer sans réfléchir", correct: false },
      ],
      feedback: "La protection des données s'applique aussi aux outils d'IA.",
    },
    {
      id: "q6", kind: "qcm", title: "La note de transparence",
      instruction: "La note de transparence sert à :",
      options: [
        { text: "Indiquer comment l'IA a été utilisée", correct: true },
        { text: "Cacher les sources", correct: false },
        { text: "Supprimer le travail humain", correct: false },
        { text: "Éviter toute correction", correct: false },
      ],
      feedback: "Elle clarifie le rôle de l'IA dans la production.",
    },
    {
      id: "q7", kind: "qcm", title: "Quand vérifier une réponse",
      instruction: "Une réponse d'IA doit être vérifiée surtout lorsqu'elle contient :",
      options: [
        { text: "Des faits, chiffres ou références", correct: true },
        { text: "Un simple style de phrase", correct: false },
        { text: "Une couleur de fond", correct: false },
        { text: "Un saut de ligne", correct: false },
      ],
      feedback: "Les faits doivent être contrôlés.",
    },
    {
      id: "q8", kind: "qcm", title: "Le prompting itératif",
      instruction: "Le prompting itératif consiste à :",
      options: [
        { text: "Améliorer la réponse par demandes successives", correct: true },
        { text: "Ne jamais lire la réponse", correct: false },
        { text: "Supprimer l'outil", correct: false },
        { text: "Répéter le même mot", correct: false },
      ],
      feedback: "On affine progressivement la réponse.",
    },
    {
      id: "q9", kind: "qcm", title: "L'utilité de l'IA",
      instruction: "L'IA est utile pour :",
      options: [
        { text: "Proposer un plan à vérifier", correct: true },
        { text: "Garantir la vérité absolue", correct: false },
        { text: "Remplacer toute expertise", correct: false },
        { text: "Supprimer les sources", correct: false },
      ],
      feedback: "Elle aide à produire, mais ne dispense pas de contrôle.",
    },
    {
      id: "q10", kind: "qcm", title: "Un usage éthique de l'IA",
      instruction: "Un usage éthique de l'IA suppose :",
      options: [
        { text: "Vérification, transparence et protection des données", correct: true },
        { text: "Copie brute sans lecture", correct: false },
        { text: "Publication de données sensibles", correct: false },
        { text: "Absence de sources", correct: false },
      ],
      feedback: "Ces trois dimensions sont indispensables.",
    },
    {
      id: "q11", kind: "truefalse", title: "IA et autorité finale",
      instruction: "Vrai ou faux ?",
      statement: "L'IA générative est une autorité finale qui dispense l'utilisateur de toute vérification.",
      answer: false,
      feedback: "Faux : l'IA est un assistant, non une autorité finale. La responsabilité de la vérification et de la décision reste humaine.",
    },
  ],
  caseStudy: {
    title: "Étude de cas — Un rapport assisté par IA",
    scenario:
      "Un apprenant demande à l'IA de rédiger un rapport, copie le texte sans le lire, ajoute de fausses références générées par l'IA et transmet le rapport avec des noms réels d'apprenants.",
    questions: [
      "Quels problèmes éthiques et professionnels observez-vous ?",
      "Comment corriger la démarche ?",
      "Quelle note de transparence proposer ?",
    ],
    corrige: [
      "Les problèmes sont le manque de vérification, les références fictives, le plagiat possible et l'exposition de données personnelles.",
      "La démarche corrigée consiste à anonymiser, vérifier chaque fait, remplacer les références inventées par des sources réelles, reformuler et assumer la production.",
      "Exemple de note : « L'IA a été utilisée pour proposer un plan et une première reformulation. Les informations ont été vérifiées, corrigées et adaptées par l'auteur. »",
    ],
  },
};
