// Pays membres de l'ONU : nom courant français, code ISO 3166-1 alpha-2, et nom officiel de l'État.
export interface Country {
  code: string;
  name: string;
  official: string;
}

/** Drapeau emoji à partir du code ISO2 (conservé pour compatibilité ; l'UI utilise des images SVG). */
export function flagEmoji(code: string): string {
  if (!code || code.length !== 2) return "🏳️";
  return String.fromCodePoint(...[...code.toUpperCase()].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", official: "République islamique d'Afghanistan" },
  { code: "ZA", name: "Afrique du Sud", official: "République d'Afrique du Sud" },
  { code: "AL", name: "Albanie", official: "République d'Albanie" },
  { code: "DZ", name: "Algérie", official: "République algérienne démocratique et populaire" },
  { code: "DE", name: "Allemagne", official: "République fédérale d'Allemagne" },
  { code: "AD", name: "Andorre", official: "Principauté d'Andorre" },
  { code: "AO", name: "Angola", official: "République d'Angola" },
  { code: "AG", name: "Antigua-et-Barbuda", official: "Antigua-et-Barbuda" },
  { code: "SA", name: "Arabie saoudite", official: "Royaume d'Arabie saoudite" },
  { code: "AR", name: "Argentine", official: "République argentine" },
  { code: "AM", name: "Arménie", official: "République d'Arménie" },
  { code: "AU", name: "Australie", official: "Commonwealth d'Australie" },
  { code: "AT", name: "Autriche", official: "République d'Autriche" },
  { code: "AZ", name: "Azerbaïdjan", official: "République d'Azerbaïdjan" },
  { code: "BS", name: "Bahamas", official: "Commonwealth des Bahamas" },
  { code: "BH", name: "Bahreïn", official: "Royaume de Bahreïn" },
  { code: "BD", name: "Bangladesh", official: "République populaire du Bangladesh" },
  { code: "BB", name: "Barbade", official: "Barbade" },
  { code: "BE", name: "Belgique", official: "Royaume de Belgique" },
  { code: "BZ", name: "Belize", official: "Belize" },
  { code: "BJ", name: "Bénin", official: "République du Bénin" },
  { code: "BT", name: "Bhoutan", official: "Royaume du Bhoutan" },
  { code: "BY", name: "Biélorussie", official: "République de Biélorussie" },
  { code: "MM", name: "Birmanie (Myanmar)", official: "République de l'Union du Myanmar" },
  { code: "BO", name: "Bolivie", official: "État plurinational de Bolivie" },
  { code: "BA", name: "Bosnie-Herzégovine", official: "Bosnie-Herzégovine" },
  { code: "BW", name: "Botswana", official: "République du Botswana" },
  { code: "BR", name: "Brésil", official: "République fédérative du Brésil" },
  { code: "BN", name: "Brunei", official: "Brunei Darussalam" },
  { code: "BG", name: "Bulgarie", official: "République de Bulgarie" },
  { code: "BF", name: "Burkina Faso", official: "Burkina Faso" },
  { code: "BI", name: "Burundi", official: "République du Burundi" },
  { code: "KH", name: "Cambodge", official: "Royaume du Cambodge" },
  { code: "CM", name: "Cameroun", official: "République du Cameroun" },
  { code: "CA", name: "Canada", official: "Canada" },
  { code: "CV", name: "Cap-Vert", official: "République du Cap-Vert" },
  { code: "CF", name: "République centrafricaine", official: "République centrafricaine" },
  { code: "CL", name: "Chili", official: "République du Chili" },
  { code: "CN", name: "Chine", official: "République populaire de Chine" },
  { code: "CY", name: "Chypre", official: "République de Chypre" },
  { code: "CO", name: "Colombie", official: "République de Colombie" },
  { code: "KM", name: "Comores", official: "Union des Comores" },
  { code: "CG", name: "Congo", official: "République du Congo" },
  { code: "CD", name: "République démocratique du Congo", official: "République démocratique du Congo" },
  { code: "KR", name: "Corée du Sud", official: "République de Corée" },
  { code: "KP", name: "Corée du Nord", official: "République populaire démocratique de Corée" },
  { code: "CR", name: "Costa Rica", official: "République du Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire", official: "République de Côte d'Ivoire" },
  { code: "HR", name: "Croatie", official: "République de Croatie" },
  { code: "CU", name: "Cuba", official: "République de Cuba" },
  { code: "DK", name: "Danemark", official: "Royaume du Danemark" },
  { code: "DJ", name: "Djibouti", official: "République de Djibouti" },
  { code: "DM", name: "Dominique", official: "Commonwealth de Dominique" },
  { code: "EG", name: "Égypte", official: "République arabe d'Égypte" },
  { code: "AE", name: "Émirats arabes unis", official: "Émirats arabes unis" },
  { code: "EC", name: "Équateur", official: "République de l'Équateur" },
  { code: "ER", name: "Érythrée", official: "État d'Érythrée" },
  { code: "ES", name: "Espagne", official: "Royaume d'Espagne" },
  { code: "EE", name: "Estonie", official: "République d'Estonie" },
  { code: "SZ", name: "Eswatini", official: "Royaume d'Eswatini" },
  { code: "US", name: "États-Unis", official: "États-Unis d'Amérique" },
  { code: "ET", name: "Éthiopie", official: "République fédérale démocratique d'Éthiopie" },
  { code: "FJ", name: "Fidji", official: "République des Fidji" },
  { code: "FI", name: "Finlande", official: "République de Finlande" },
  { code: "FR", name: "France", official: "République française" },
  { code: "GA", name: "Gabon", official: "République gabonaise" },
  { code: "GM", name: "Gambie", official: "République de Gambie" },
  { code: "GE", name: "Géorgie", official: "Géorgie" },
  { code: "GH", name: "Ghana", official: "République du Ghana" },
  { code: "GR", name: "Grèce", official: "République hellénique" },
  { code: "GD", name: "Grenade", official: "Grenade" },
  { code: "GT", name: "Guatemala", official: "République du Guatemala" },
  { code: "GN", name: "Guinée", official: "République de Guinée" },
  { code: "GW", name: "Guinée-Bissau", official: "République de Guinée-Bissau" },
  { code: "GQ", name: "Guinée équatoriale", official: "République de Guinée équatoriale" },
  { code: "GY", name: "Guyana", official: "République coopérative du Guyana" },
  { code: "HT", name: "Haïti", official: "République d'Haïti" },
  { code: "HN", name: "Honduras", official: "République du Honduras" },
  { code: "HU", name: "Hongrie", official: "Hongrie" },
  { code: "IN", name: "Inde", official: "République de l'Inde" },
  { code: "ID", name: "Indonésie", official: "République d'Indonésie" },
  { code: "IQ", name: "Irak", official: "République d'Irak" },
  { code: "IR", name: "Iran", official: "République islamique d'Iran" },
  { code: "IE", name: "Irlande", official: "Irlande" },
  { code: "IS", name: "Islande", official: "République d'Islande" },
  { code: "IL", name: "Israël", official: "État d'Israël" },
  { code: "IT", name: "Italie", official: "République italienne" },
  { code: "JM", name: "Jamaïque", official: "Jamaïque" },
  { code: "JP", name: "Japon", official: "Japon" },
  { code: "JO", name: "Jordanie", official: "Royaume hachémite de Jordanie" },
  { code: "KZ", name: "Kazakhstan", official: "République du Kazakhstan" },
  { code: "KE", name: "Kenya", official: "République du Kenya" },
  { code: "KG", name: "Kirghizistan", official: "République kirghize" },
  { code: "KI", name: "Kiribati", official: "République de Kiribati" },
  { code: "KW", name: "Koweït", official: "État du Koweït" },
  { code: "LA", name: "Laos", official: "République démocratique populaire lao" },
  { code: "LS", name: "Lesotho", official: "Royaume du Lesotho" },
  { code: "LV", name: "Lettonie", official: "République de Lettonie" },
  { code: "LB", name: "Liban", official: "République libanaise" },
  { code: "LR", name: "Liberia", official: "République du Liberia" },
  { code: "LY", name: "Libye", official: "État de Libye" },
  { code: "LI", name: "Liechtenstein", official: "Principauté de Liechtenstein" },
  { code: "LT", name: "Lituanie", official: "République de Lituanie" },
  { code: "LU", name: "Luxembourg", official: "Grand-Duché de Luxembourg" },
  { code: "MK", name: "Macédoine du Nord", official: "République de Macédoine du Nord" },
  { code: "MG", name: "Madagascar", official: "République de Madagascar" },
  { code: "MY", name: "Malaisie", official: "Malaisie" },
  { code: "MW", name: "Malawi", official: "République du Malawi" },
  { code: "MV", name: "Maldives", official: "République des Maldives" },
  { code: "ML", name: "Mali", official: "République du Mali" },
  { code: "MT", name: "Malte", official: "République de Malte" },
  { code: "MA", name: "Maroc", official: "Royaume du Maroc" },
  { code: "MH", name: "Îles Marshall", official: "République des Îles Marshall" },
  { code: "MU", name: "Maurice", official: "République de Maurice" },
  { code: "MR", name: "Mauritanie", official: "République islamique de Mauritanie" },
  { code: "MX", name: "Mexique", official: "États-Unis mexicains" },
  { code: "FM", name: "Micronésie", official: "États fédérés de Micronésie" },
  { code: "MD", name: "Moldavie", official: "République de Moldavie" },
  { code: "MC", name: "Monaco", official: "Principauté de Monaco" },
  { code: "MN", name: "Mongolie", official: "Mongolie" },
  { code: "ME", name: "Monténégro", official: "Monténégro" },
  { code: "MZ", name: "Mozambique", official: "République du Mozambique" },
  { code: "NA", name: "Namibie", official: "République de Namibie" },
  { code: "NR", name: "Nauru", official: "République de Nauru" },
  { code: "NP", name: "Népal", official: "République fédérale démocratique du Népal" },
  { code: "NI", name: "Nicaragua", official: "République du Nicaragua" },
  { code: "NE", name: "Niger", official: "République du Niger" },
  { code: "NG", name: "Nigeria", official: "République fédérale du Nigeria" },
  { code: "NO", name: "Norvège", official: "Royaume de Norvège" },
  { code: "NZ", name: "Nouvelle-Zélande", official: "Nouvelle-Zélande" },
  { code: "OM", name: "Oman", official: "Sultanat d'Oman" },
  { code: "UG", name: "Ouganda", official: "République d'Ouganda" },
  { code: "UZ", name: "Ouzbékistan", official: "République d'Ouzbékistan" },
  { code: "PK", name: "Pakistan", official: "République islamique du Pakistan" },
  { code: "PW", name: "Palaos", official: "République des Palaos" },
  { code: "PA", name: "Panama", official: "République du Panama" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée", official: "État indépendant de Papouasie-Nouvelle-Guinée" },
  { code: "PY", name: "Paraguay", official: "République du Paraguay" },
  { code: "NL", name: "Pays-Bas", official: "Royaume des Pays-Bas" },
  { code: "PE", name: "Pérou", official: "République du Pérou" },
  { code: "PH", name: "Philippines", official: "République des Philippines" },
  { code: "PL", name: "Pologne", official: "République de Pologne" },
  { code: "PT", name: "Portugal", official: "République portugaise" },
  { code: "QA", name: "Qatar", official: "État du Qatar" },
  { code: "RO", name: "Roumanie", official: "Roumanie" },
  { code: "GB", name: "Royaume-Uni", official: "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord" },
  { code: "RU", name: "Russie", official: "Fédération de Russie" },
  { code: "RW", name: "Rwanda", official: "République du Rwanda" },
  { code: "KN", name: "Saint-Kitts-et-Nevis", official: "Fédération de Saint-Kitts-et-Nevis" },
  { code: "SM", name: "Saint-Marin", official: "République de Saint-Marin" },
  { code: "VC", name: "Saint-Vincent-et-les-Grenadines", official: "Saint-Vincent-et-les-Grenadines" },
  { code: "LC", name: "Sainte-Lucie", official: "Sainte-Lucie" },
  { code: "SB", name: "Îles Salomon", official: "Îles Salomon" },
  { code: "SV", name: "Salvador", official: "République du Salvador" },
  { code: "WS", name: "Samoa", official: "État indépendant du Samoa" },
  { code: "ST", name: "Sao Tomé-et-Principe", official: "République démocratique de Sao Tomé-et-Principe" },
  { code: "SN", name: "Sénégal", official: "République du Sénégal" },
  { code: "RS", name: "Serbie", official: "République de Serbie" },
  { code: "SC", name: "Seychelles", official: "République des Seychelles" },
  { code: "SL", name: "Sierra Leone", official: "République de Sierra Leone" },
  { code: "SG", name: "Singapour", official: "République de Singapour" },
  { code: "SK", name: "Slovaquie", official: "République slovaque" },
  { code: "SI", name: "Slovénie", official: "République de Slovénie" },
  { code: "SO", name: "Somalie", official: "République fédérale de Somalie" },
  { code: "SD", name: "Soudan", official: "République du Soudan" },
  { code: "SS", name: "Soudan du Sud", official: "République du Soudan du Sud" },
  { code: "LK", name: "Sri Lanka", official: "République socialiste démocratique du Sri Lanka" },
  { code: "SE", name: "Suède", official: "Royaume de Suède" },
  { code: "CH", name: "Suisse", official: "Confédération suisse" },
  { code: "SR", name: "Suriname", official: "République du Suriname" },
  { code: "SY", name: "Syrie", official: "République arabe syrienne" },
  { code: "TJ", name: "Tadjikistan", official: "République du Tadjikistan" },
  { code: "TZ", name: "Tanzanie", official: "République-Unie de Tanzanie" },
  { code: "TD", name: "Tchad", official: "République du Tchad" },
  { code: "CZ", name: "Tchéquie", official: "République tchèque" },
  { code: "TH", name: "Thaïlande", official: "Royaume de Thaïlande" },
  { code: "TL", name: "Timor oriental", official: "République démocratique du Timor oriental" },
  { code: "TG", name: "Togo", official: "République togolaise" },
  { code: "TO", name: "Tonga", official: "Royaume des Tonga" },
  { code: "TT", name: "Trinité-et-Tobago", official: "République de Trinité-et-Tobago" },
  { code: "TN", name: "Tunisie", official: "République tunisienne" },
  { code: "TM", name: "Turkménistan", official: "Turkménistan" },
  { code: "TR", name: "Turquie", official: "République de Turquie" },
  { code: "TV", name: "Tuvalu", official: "Tuvalu" },
  { code: "UA", name: "Ukraine", official: "Ukraine" },
  { code: "UY", name: "Uruguay", official: "République orientale de l'Uruguay" },
  { code: "VU", name: "Vanuatu", official: "République de Vanuatu" },
  { code: "VE", name: "Venezuela", official: "République bolivarienne du Venezuela" },
  { code: "VN", name: "Viêt Nam", official: "République socialiste du Viêt Nam" },
  { code: "YE", name: "Yémen", official: "République du Yémen" },
  { code: "ZM", name: "Zambie", official: "République de Zambie" },
  { code: "ZW", name: "Zimbabwe", official: "République du Zimbabwe" },
];
