import type { N1Module } from "./types";

/** Niveau 1 — Module 2 : Traitement de texte professionnel avec Word. */
export const MODULE_2: N1Module = {
  code: "N1-M2",
  slug: "module-2",
  num: 2,
  title: "Traitement de texte professionnel avec Word",
  subtitle: "Saisir, structurer, mettre en forme, enrichir et exporter un document conforme aux usages professionnels.",
  duration: "21 heures · 2 semaines",
  finalite:
    "Rendre l'apprenant capable de saisir, structurer, mettre en forme, enrichir, exporter et présenter un document Word conforme aux usages professionnels et académiques.",
  objectives: [
    "Saisir et corriger un texte en utilisant les fonctions d'édition essentielles.",
    "Appliquer une mise en forme professionnelle aux caractères et aux paragraphes.",
    "Utiliser les styles pour structurer un document long.",
    "Créer une hiérarchie de titres et générer un sommaire automatique.",
    "Insérer et mettre en forme un tableau.",
    "Insérer une image, l'habiller avec le texte et ajouter une légende.",
    "Créer un en-tête, un pied de page et une numérotation.",
    "Préparer le document pour l'impression.",
    "Exporter le document en PDF.",
    "Vérifier la conformité du document à l'aide d'une check-list.",
  ],
  competences: [
    { group: "Saisie et édition", text: "Saisir, sélectionner, déplacer, copier, corriger et enregistrer un texte ; le texte est complet, corrigé et enregistré au bon format." },
    { group: "Mise en forme", text: "Appliquer police, taille, couleur, alignement, interligne, listes et retraits ; la présentation est homogène, lisible et sobre." },
    { group: "Structuration", text: "Créer des titres hiérarchisés, appliquer des styles et générer un sommaire ; le document possède une structure visible et un sommaire cohérent." },
    { group: "Insertion d'objets", text: "Insérer tableau, image, légende, en-tête et pied de page sans désorganiser la mise en page." },
    { group: "Diffusion", text: "Exporter en PDF et vérifier le rendu avant partage ; le PDF est lisible, nommé correctement et conforme aux consignes." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Comprendre l'environnement de Word",
      icon: "FileText",
      blocks: [
        { type: "text", html: "Word est un logiciel de <strong>traitement de texte</strong>. Son rôle est de permettre la création, la modification, la mise en forme et la diffusion de documents écrits. Avant de saisir du texte, l'apprenant doit comprendre l'organisation de l'interface : le ruban, les onglets, les groupes de commandes, la barre d'accès rapide, la zone de travail, la règle, les marges et la barre d'état." },
        { type: "text", html: "Le <strong>ruban</strong> est organisé par onglets. L'onglet <em>Accueil</em> regroupe les commandes les plus fréquentes ; l'onglet <em>Insertion</em> permet d'ajouter des objets ; l'onglet <em>Mise en page</em> règle les marges et l'orientation ; l'onglet <em>Références</em> insère une table des matières et des légendes. Cette logique par onglets doit être découverte progressivement pour ne pas se perdre dans la quantité de boutons." },
        { type: "infographic", kind: "table", title: "Les onglets essentiels du ruban", data: { columns: ["Onglet", "À quoi il sert"], rows: [
          ["Accueil", "Police, taille, gras, italique, souligné, couleur, alignement, listes, styles"],
          ["Insertion", "Tableaux, images, formes, en-têtes, pieds de page, numéros de page"],
          ["Mise en page", "Marges, orientation, taille du papier, espacements"],
          ["Références", "Table des matières, notes, légendes"],
        ] } },
        { type: "callout", tone: "info", title: "Un fichier vivant", text: "Un document Word peut être modifié, corrigé, réorganisé et enrichi. Pour cette raison, on enregistre régulièrement son travail et on choisit un nom de fichier explicite : le .docx sert au travail, le .pdf sert à la diffusion." },
      ],
    },
    {
      id: "seq-2",
      title: "Saisir, sélectionner, corriger et éditer le texte",
      icon: "Type",
      blocks: [
        { type: "text", html: "La saisie professionnelle commence par une posture simple : <strong>écrire d'abord le contenu, puis le mettre en forme</strong>. Beaucoup de débutants modifient la couleur, la police ou la taille à chaque ligne, ce qui rend le document incohérent. Il faut séparer deux moments : la rédaction du texte et la mise en forme du document." },
        { type: "text", html: "L'<strong>édition</strong> consiste à agir sur le texte déjà saisi : sélectionner une lettre, un mot, une phrase, un paragraphe ou tout le document, puis manipuler les commandes couper, copier, coller et annuler." },
        { type: "infographic", kind: "table", title: "Les raccourcis qui font gagner du temps", data: { columns: ["Raccourci", "Action"], rows: [
          ["Ctrl + C", "Copier (l'original reste)"],
          ["Ctrl + X", "Couper (retire le texte de l'emplacement)"],
          ["Ctrl + V", "Coller"],
          ["Ctrl + Z", "Annuler la dernière action"],
        ] } },
        { type: "callout", tone: "warn", title: "La relecture reste humaine", text: "La correction orthographique de Word est une aide, mais elle ne remplace pas la relecture. Word peut signaler une erreur, proposer une correction ou ignorer un mot spécialisé. C'est à l'apprenant de vérifier le sens, les accords, la ponctuation, les majuscules et les noms propres." },
      ],
    },
    {
      id: "seq-3",
      title: "Mettre en forme caractères et paragraphes",
      icon: "Bold",
      blocks: [
        { type: "text", html: "La mise en forme des <strong>caractères</strong> concerne l'apparence des lettres : police, taille, gras, italique, souligné, couleur, exposant, indice ou surbrillance. La règle professionnelle est de <strong>rester sobre</strong> : une police lisible, des titres visibles et des espacements réguliers suffisent souvent à produire un document élégant." },
        { type: "text", html: "La mise en forme des <strong>paragraphes</strong> concerne l'organisation des blocs de texte : alignement, retrait, interligne, espacement avant et après, listes à puces, listes numérotées. L'usage excessif de la touche <em>Entrée</em> pour créer de l'espace est une mauvaise pratique : l'espacement doit être réglé par les paramètres de paragraphe pour une mise en page plus stable." },
        { type: "infographic", kind: "two-columns", title: "Quelle liste choisir ?", data: { left: { title: "Liste à puces", subtitle: "éléments non hiérarchisés", items: ["Documents à apporter", "Matériel nécessaire", "Idées sans ordre particulier"] }, right: { title: "Liste numérotée", subtitle: "ordre ou classement", items: ["Étapes d'une procédure", "Arguments classés", "Instructions à suivre dans l'ordre"] } } },
        { type: "callout", tone: "tip", title: "Alignement", text: "Le justifié donne un aspect ordonné mais peut créer des espaces irréguliers entre les mots. Pour les textes longs, l'alignement à gauche est souvent plus sûr pour les débutants." },
      ],
    },
    {
      id: "seq-4",
      title: "Structurer un document avec les styles",
      icon: "Heading",
      blocks: [
        { type: "text", html: "Les <strong>styles</strong> sont au cœur de la production documentaire professionnelle. Un style est un ensemble de mises en forme appliquées automatiquement à un type de texte : titre principal, sous-titre, paragraphe normal, citation ou légende. Utiliser les styles évite de modifier manuellement chaque titre, permet de générer un sommaire automatique et maintient la cohérence du document." },
        { type: "callout", tone: "warn", title: "La distinction fondamentale", text: "Agrandir manuellement un titre ne suffit pas : le texte semble être un titre, mais Word ne le reconnaît pas comme un niveau de structure. Appliquer le style « Titre 1 » indique à Word que ce texte appartient à la hiérarchie du document." },
        { type: "infographic", kind: "tree", title: "Une hiérarchie de titres simple", data: { root: "Rapport", nodes: [
          { label: "Titre 1 — Contexte de la formation" },
          { label: "Titre 1 — Objectifs visés", children: [{ label: "Titre 2 — Objectif général" }, { label: "Titre 2 — Objectifs spécifiques" }] },
          { label: "Titre 1 — Organisation pratique", children: [{ label: "Titre 2 — Calendrier" }, { label: "Titre 3 — Détail des séances" }] },
        ] } },
        { type: "keypoints", title: "À retenir sur les styles", points: [
          "Titre 1 pour les grandes parties, Titre 2 pour les sous-parties, Titre 3 pour les subdivisions.",
          "Un document de niveau 1 n'a pas besoin d'une structure trop profonde.",
          "Microsoft recommande l'usage des styles et un ordre logique des titres pour l'accessibilité.",
        ] },
      ],
    },
    {
      id: "seq-5",
      title: "Insérer et mettre en forme un tableau",
      icon: "Table",
      blocks: [
        { type: "text", html: "Un <strong>tableau</strong> organise des informations en lignes et en colonnes. Il est utile pour présenter un calendrier, une liste de participants, une grille d'évaluation, un budget simple ou une comparaison. L'apprenant doit savoir insérer un tableau, définir le nombre de lignes et de colonnes, saisir des informations, ajouter ou supprimer une ligne, fusionner des cellules et appliquer une présentation sobre." },
        { type: "infographic", kind: "rules", title: "Un tableau lisible : les bons réflexes", data: { rules: [
          { icon: "Check", title: "Une ligne d'en-tête", text: "La première ligne explique le sens des colonnes." },
          { icon: "FileText", title: "Une introduction", text: "Le tableau porte un titre ou est annoncé par une phrase." },
          { icon: "Eye", title: "L'essentiel seulement", text: "Un tableau trop chargé devient illisible ; on choisit les informations utiles." },
          { icon: "X", title: "Pas de calculs complexes", text: "Word n'est pas un tableur : les calculs avancés se font dans Excel." },
        ] } },
        { type: "callout", tone: "example", title: "Exemple", text: "Un tableau de calendrier peut présenter trois colonnes : période, activité, responsable. La première ligne sert d'en-tête." },
      ],
    },
    {
      id: "seq-6",
      title: "Insérer une image, une légende et gérer l'habillage",
      icon: "Image",
      blocks: [
        { type: "text", html: "L'<strong>image</strong> enrichit le document lorsqu'elle apporte une information utile : photo d'activité, schéma, logo, illustration, capture d'écran ou infographie. L'apprenant doit savoir insérer une image depuis l'ordinateur, la redimensionner sans la déformer, la positionner et choisir un <strong>habillage</strong> adapté, c'est-à-dire la manière dont le texte se place autour de l'image." },
        { type: "callout", tone: "warn", title: "Erreur fréquente", text: "Agrandir une image en tirant sur un côté la déforme. Le redimensionnement doit se faire par les coins pour conserver les proportions. On évite aussi les images floues, trop lourdes ou sans lien avec le contenu." },
        { type: "keypoints", title: "Une image professionnelle", points: [
          "Elle est nette, pertinente et correctement placée.",
          "Elle est citée dans le texte, et non posée comme simple décoration.",
          "Elle porte une légende qui indique le titre, la source ou l'explication.",
          "Un texte alternatif peut être ajouté pour l'accessibilité lorsque c'est utile.",
        ] },
      ],
    },
    {
      id: "seq-7",
      title: "En-tête, pied de page et identité documentaire",
      icon: "Layout",
      blocks: [
        { type: "text", html: "L'<strong>en-tête</strong> et le <strong>pied de page</strong> contiennent des informations répétées sur plusieurs pages : nom de la structure, titre du document, auteur, date, logo, coordonnées ou numéro de page. Ces éléments renforcent l'identité documentaire et facilitent la lecture. La <strong>numérotation automatique</strong> évite les confusions lorsqu'un document est imprimé ou partagé." },
        { type: "infographic", kind: "two-columns", title: "Où placer l'information répétée ?", data: { left: { title: "En-tête", subtitle: "haut de page", items: ["Nom de la structure ou du programme", "Titre du document", "Logo (sobre, pas trop grand)"] }, right: { title: "Pied de page", subtitle: "bas de page", items: ["Numéro de page", "Date ou version", "Auteur ou coordonnées"] } } },
        { type: "callout", tone: "tip", title: "Sobriété et traçabilité", text: "Un en-tête trop chargé ou un logo trop grand perturbe la lecture. L'identité documentaire comprend aussi le nom du fichier, la date, la version et le statut : brouillon, version corrigée, version finale." },
      ],
    },
    {
      id: "seq-8",
      title: "Mise en page, impression et export PDF",
      icon: "Printer",
      blocks: [
        { type: "text", html: "La <strong>mise en page</strong> prépare le document à la lecture, à l'impression et à la diffusion : marges, orientation, format de papier, sauts de page, espacements et aperçu avant impression. Ce qu'on voit à l'écran n'est pas toujours exactement ce qui sera imprimé : l'<strong>aperçu avant impression</strong> est donc une étape de contrôle." },
        { type: "text", html: "L'<strong>export PDF</strong> est une compétence essentielle. Le fichier .docx reste modifiable ; le fichier .pdf est plus stable pour la diffusion, car il réduit les risques de modification involontaire et préserve la mise en forme sur différents ordinateurs." },
        { type: "infographic", kind: "steps", title: "Finaliser et diffuser un document", data: { steps: [
          { title: "Relire", text: "vérifier le contenu et la langue" },
          { title: "Vérifier la mise en page", text: "marges, sauts, pagination" },
          { title: "Contrôler le nom du fichier", text: "explicite et daté" },
          { title: "Exporter en PDF" },
          { title: "Ouvrir le PDF", text: "contrôler pages, images, tableaux et coupures" },
        ] } },
        { type: "callout", tone: "warn", title: "Toujours vérifier après export", text: "Après l'export, on ouvre le PDF et on contrôle les pages, les images, les tableaux, la pagination et les coupures. Cette étape de contrôle qualité est aussi importante que la rédaction elle-même." },
      ],
    },
    {
      id: "seq-9",
      title: "Accessibilité, lisibilité et qualité professionnelle",
      icon: "Eye",
      blocks: [
        { type: "text", html: "Un document professionnel doit être <strong>lisible pour le plus grand nombre</strong>. La lisibilité dépend de la taille de police, du contraste, de l'espacement, de la clarté des titres, de la sobriété des couleurs et de la logique de lecture. Un document très décoré peut être moins efficace qu'un document simple et bien structuré." },
        { type: "text", html: "L'<strong>accessibilité documentaire</strong> consiste à rendre le document utilisable par des personnes ayant des besoins variés. Microsoft recommande l'usage de titres intégrés, d'un ordre logique, d'en-têtes de tableaux et de descriptions utiles pour les images." },
        { type: "infographic", kind: "rules", title: "Check-list qualité avant diffusion", data: { rules: [
          { icon: "FileText", title: "Titre clair", text: "Le document porte-t-il un titre clair et des titres hiérarchisés ?" },
          { icon: "Eye", title: "Police lisible", text: "La police est-elle lisible et les paragraphes espacés ?" },
          { icon: "Table", title: "Tableau et image", text: "Le tableau a-t-il un en-tête ? L'image est-elle nette et légendée ?" },
          { icon: "Check", title: "PDF vérifié", text: "Les pages sont-elles numérotées ? Le fichier est-il bien nommé et le PDF ouvert et vérifié ?" },
        ] } },
        { type: "callout", tone: "tip", title: "Le principe à retenir", text: "Dans Word, la bonne pratique consiste à structurer avant de décorer. Un document bien structuré sera plus facile à corriger, à exporter, à lire et à réutiliser." },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "categorize", title: "Reconnaître les onglets de Word",
      instruction: "Classez chaque commande sous l'onglet où on la trouve habituellement.",
      categories: ["Accueil", "Insertion", "Mise en page", "Références"],
      items: [
        { label: "Gras et italique", category: "Accueil" },
        { label: "Couleur du texte", category: "Accueil" },
        { label: "Insérer un tableau", category: "Insertion" },
        { label: "Insérer une image", category: "Insertion" },
        { label: "Marges et orientation", category: "Mise en page" },
        { label: "Table des matières", category: "Références" },
      ],
      feedback: "Accueil regroupe la mise en forme courante, Insertion les objets (tableau, image, en-tête), Mise en page les marges et l'orientation, Références la table des matières et les légendes.",
    },
    {
      id: "f2", kind: "match", title: "Associer le raccourci à son action",
      instruction: "Reliez chaque raccourci clavier à l'action qu'il déclenche.",
      pairs: [
        { left: "Ctrl + C", right: "Copier" },
        { left: "Ctrl + X", right: "Couper" },
        { left: "Ctrl + V", right: "Coller" },
        { left: "Ctrl + Z", right: "Annuler" },
      ],
      feedback: "Ctrl+C copie sans retirer l'original, Ctrl+X coupe (retire le texte), Ctrl+V colle, Ctrl+Z annule la dernière action.",
    },
    {
      id: "f3", kind: "order", title: "Produire et diffuser un document",
      instruction: "Remettez les étapes dans le bon ordre pour finaliser et diffuser un document Word.",
      items: ["Rédiger le contenu", "Appliquer une mise en forme sobre", "Relire et vérifier la mise en page", "Exporter en PDF", "Ouvrir le PDF pour vérifier le rendu"],
      feedback: "On écrit d'abord le contenu, puis on met en forme, on relit et vérifie, on exporte en PDF et on ouvre toujours le PDF pour contrôler le rendu avant de le partager.",
    },
    {
      id: "f4", kind: "categorize", title: "Liste à puces ou liste numérotée ?",
      instruction: "Pour chaque cas, choisissez le type de liste adapté.",
      categories: ["Liste à puces", "Liste numérotée"],
      items: [
        { label: "Les étapes d'une procédure d'installation", category: "Liste numérotée" },
        { label: "Les arguments classés par ordre d'importance", category: "Liste numérotée" },
        { label: "Le matériel à apporter en formation", category: "Liste à puces" },
        { label: "Des idées sans ordre particulier", category: "Liste à puces" },
      ],
      feedback: "Les listes numérotées conviennent aux étapes, procédures ou arguments classés ; les listes à puces conviennent aux éléments non hiérarchisés.",
    },
    {
      id: "f5", kind: "truefalse", title: "Écran et impression",
      instruction: "Vrai ou faux ?",
      statement: "Ce que l'on voit à l'écran correspond toujours exactement à ce qui sera imprimé.",
      answer: false,
      feedback: "Faux : l'aperçu avant impression sert justement à contrôler le rendu, car l'affichage à l'écran peut différer de l'impression.",
    },
    { id: "q1", kind: "qcm", title: "Le rôle de Word", instruction: "Quel est le rôle principal de Word ?", options: [{ text: "Naviguer sur Internet", correct: false }, { text: "Créer et modifier des documents texte", correct: true }, { text: "Faire des calculs avancés", correct: false }, { text: "Lire uniquement des vidéos", correct: false }], feedback: "Word est un logiciel de traitement de texte." },
    { id: "q2", kind: "qcm", title: "L'onglet des commandes courantes", instruction: "Quel onglet contient généralement les commandes de police et de paragraphe ?", options: [{ text: "Accueil", correct: true }, { text: "Insertion", correct: false }, { text: "Références", correct: false }, { text: "Affichage", correct: false }], feedback: "L'onglet Accueil regroupe les commandes courantes de mise en forme." },
    { id: "q3", kind: "qcm", title: "Copier un élément", instruction: "Quelle combinaison permet de copier un élément sélectionné ?", options: [{ text: "Ctrl+X", correct: false }, { text: "Ctrl+C", correct: true }, { text: "Ctrl+V", correct: false }, { text: "Ctrl+Z", correct: false }], feedback: "Ctrl+C copie sans retirer l'original." },
    { id: "q4", kind: "qcm", title: "Annuler une action", instruction: "Quelle combinaison permet d'annuler la dernière action ?", options: [{ text: "Ctrl+A", correct: false }, { text: "Ctrl+P", correct: false }, { text: "Ctrl+Z", correct: true }, { text: "Ctrl+B", correct: false }], feedback: "Ctrl+Z annule l'action précédente." },
    { id: "q5", kind: "qcm", title: "Enregistrer régulièrement", instruction: "Pourquoi faut-il enregistrer régulièrement un document ?", options: [{ text: "Pour changer la couleur", correct: false }, { text: "Pour éviter la perte du travail", correct: true }, { text: "Pour imprimer plus vite", correct: false }, { text: "Pour fermer Word", correct: false }], feedback: "L'enregistrement protège contre les pertes accidentelles." },
    { id: "q6", kind: "qcm", title: "Le format Word", instruction: "Quelle extension correspond au document Word moderne ?", options: [{ text: ".docx", correct: true }, { text: ".xlsx", correct: false }, { text: ".pptx", correct: false }, { text: ".jpg", correct: false }], feedback: ".docx est le format courant des documents Word." },
    { id: "q7", kind: "qcm", title: "La fonction Gras", instruction: "Que permet la fonction Gras ?", options: [{ text: "Agrandir la page", correct: false }, { text: "Mettre un texte en évidence", correct: true }, { text: "Créer un tableau", correct: false }, { text: "Exporter en PDF", correct: false }], feedback: "Le gras attire l'attention sur une information importante." },
    { id: "q8", kind: "qcm", title: "Créer une hiérarchie", instruction: "Quelle fonction permet de créer une hiérarchie reconnue par Word ?", options: [{ text: "La couleur", correct: false }, { text: "Les styles de titres", correct: true }, { text: "Le zoom", correct: false }, { text: "La correction automatique", correct: false }], feedback: "Les styles de titres structurent le document et sont reconnus par Word." },
    { id: "q9", kind: "qcm", title: "Pourquoi les styles ?", instruction: "Pourquoi utiliser les styles plutôt qu'une mise en forme manuelle ?", options: [{ text: "Pour la cohérence et le sommaire automatique", correct: true }, { text: "Pour supprimer le texte", correct: false }, { text: "Pour bloquer le fichier", correct: false }, { text: "Pour éteindre l'ordinateur", correct: false }], feedback: "Les styles uniformisent le document et permettent de générer le sommaire." },
    { id: "q10", kind: "qcm", title: "Le sommaire automatique", instruction: "Un sommaire automatique dépend principalement de :", options: [{ text: "La couleur du texte", correct: false }, { text: "La taille des images", correct: false }, { text: "L'usage des styles de titres", correct: true }, { text: "La présence d'une imprimante", correct: false }], feedback: "Word utilise les niveaux de titres pour générer le sommaire." },
    { id: "q11", kind: "qcm", title: "Insérer un tableau", instruction: "Quel onglet permet généralement d'insérer un tableau ?", options: [{ text: "Accueil", correct: false }, { text: "Insertion", correct: true }, { text: "Révision", correct: false }, { text: "Aide", correct: false }], feedback: "Les objets comme les tableaux et les images se trouvent dans l'onglet Insertion." },
    { id: "q12", kind: "qcm", title: "Un tableau compréhensible", instruction: "Quel élément rend un tableau plus compréhensible ?", options: [{ text: "Une première ligne d'en-têtes", correct: true }, { text: "Des cellules vides partout", correct: false }, { text: "Beaucoup de couleurs", correct: false }, { text: "Une police minuscule", correct: false }], feedback: "Les en-têtes indiquent le sens des colonnes." },
    { id: "q13", kind: "qcm", title: "Redimensionner une image", instruction: "Que faut-il éviter en redimensionnant une image ?", options: [{ text: "Utiliser les coins", correct: false }, { text: "Conserver les proportions", correct: false }, { text: "Déformer l'image", correct: true }, { text: "Vérifier la netteté", correct: false }], feedback: "Une image déformée paraît non professionnelle : on redimensionne par les coins pour garder les proportions." },
    { id: "q14", kind: "qcm", title: "La légende d'image", instruction: "À quoi sert une légende sous une image ?", options: [{ text: "Donner un sens ou une source", correct: true }, { text: "Supprimer l'image", correct: false }, { text: "Modifier le clavier", correct: false }, { text: "Lancer l'impression", correct: false }], feedback: "La légende explique ou identifie l'image." },
    { id: "q15", kind: "qcm", title: "Le pied de page", instruction: "Que contient souvent un pied de page ?", options: [{ text: "Le numéro de page", correct: true }, { text: "Un mot de passe", correct: false }, { text: "Le système d'exploitation", correct: false }, { text: "La liste des polices", correct: false }], feedback: "Le pied de page accueille souvent la pagination." },
    { id: "q16", kind: "qcm", title: "Vérifier avant impression", instruction: "Quel outil permet de vérifier la mise en page avant impression ?", options: [{ text: "L'aperçu avant impression", correct: true }, { text: "La corbeille", correct: false }, { text: "L'explorateur", correct: false }, { text: "Le gestionnaire de tâches", correct: false }], feedback: "L'aperçu montre le rendu final prévu et aide à repérer les pages vides et les coupures." },
    { id: "q17", kind: "qcm", title: "Pourquoi le PDF", instruction: "Pourquoi exporter en PDF ?", options: [{ text: "Pour stabiliser la mise en forme à la diffusion", correct: true }, { text: "Pour perdre les images", correct: false }, { text: "Pour supprimer le document", correct: false }, { text: "Pour empêcher toute lecture", correct: false }], feedback: "Le PDF facilite le partage tout en conservant le rendu sur différents ordinateurs." },
    { id: "q18", kind: "truefalse", title: "Après l'export PDF", instruction: "Vrai ou faux ?", statement: "Après avoir exporté un PDF, il faut l'ouvrir pour vérifier le rendu.", answer: true, feedback: "Vrai : le contrôle du PDF permet de repérer les erreurs de rendu (pages, images, tableaux, coupures) avant de partager." },
  ],
  caseStudy: {
    title: "Étude de cas — Le rapport de Koffi",
    scenario:
      "Koffi a rédigé un rapport de 4 pages dans Word. Il a écrit les titres en rouge et en taille 18, mais il n'a pas utilisé les styles. Il a ajouté un tableau sans en-têtes, une image très grande qui coupe le texte, aucun numéro de page, et il a envoyé uniquement le fichier .docx par e-mail. Le destinataire lui répond que le document est difficile à lire et que la mise en page a changé sur son ordinateur.",
    questions: [
      "Identifiez au moins cinq erreurs commises par Koffi.",
      "Proposez une méthode de correction du document.",
      "Expliquez pourquoi le PDF aurait été préférable pour la diffusion.",
      "Proposez un nom de fichier professionnel pour la version finale.",
    ],
    corrige: [
      "Cinq erreurs : titres mis en forme manuellement sans styles ; tableau sans en-têtes ; image trop grande et mal habillée qui coupe le texte ; absence de pagination ; absence de vérification du rendu et diffusion uniquement en .docx, d'où une mise en forme instable sur un autre ordinateur.",
      "Méthode de correction : appliquer les styles de titres (Titre 1, Titre 2), générer un sommaire, ajouter des en-têtes au tableau, redimensionner l'image par les coins et ajouter une légende, insérer une pagination en pied de page, puis exporter en PDF.",
      "Le PDF est préférable car il stabilise le rendu et préserve la mise en forme sur tous les ordinateurs ; il évite les modifications involontaires et facilite la lecture par le destinataire. Il faut ensuite ouvrir le PDF pour le vérifier.",
      "Nom possible : Rapport_FormationNumerique_Koffi_2026-06-29_VF.pdf.",
    ],
  },
};
