import type { N1Module } from "./types";

/** Niveau 1 — Module 3 : Tableur Excel et calculs simples. */
export const MODULE_3: N1Module = {
  code: "N1-M3",
  slug: "module-3",
  num: 3,
  title: "Tableur Excel et calculs simples",
  subtitle: "Construire un tableau lisible, saisir des données fiables, calculer avec SOMME, MOYENNE et SI, puis produire un premier graphique.",
  duration: "21 heures · 2 semaines",
  finalite:
    "Installer l'autonomie minimale en tableur : construire une table lisible, saisir et formater des données, réaliser des calculs élémentaires avec SOMME, MOYENNE et SI, recopier correctement les formules, puis produire un premier graphique pour visualiser l'information.",
  objectives: [
    "Ouvrir, enregistrer et retrouver un classeur Excel au format .xlsx.",
    "Identifier un classeur, une feuille, une ligne, une colonne, une cellule et une plage de cellules.",
    "Saisir des données textuelles, numériques et des dates dans un tableau.",
    "Mettre en forme un tableau lisible : titres, bordures, alignements, largeurs, formats numériques.",
    "Trier et filtrer des données simples.",
    "Écrire une formule élémentaire en respectant la syntaxe du tableur.",
    "Utiliser les fonctions SOMME, MOYENNE et SI dans des situations courantes.",
    "Distinguer une référence relative d'une référence absolue de base.",
    "Recopier une formule avec la poignée de recopie.",
    "Produire un graphique simple, titré et légendé, à partir d'une plage de données.",
    "Préparer une feuille pour l'impression ou l'export PDF.",
    "Vérifier la cohérence des résultats obtenus avant diffusion.",
  ],
  competences: [
    { group: "Techniques", text: "Créer un tableau structuré, saisir des données, appliquer une mise en forme, utiliser des formules simples, recopier une formule et produire un graphique élémentaire." },
    { group: "Méthodologiques", text: "Organiser l'information avant de calculer : une ligne représente une observation ou un enregistrement, une colonne représente une variable, et un bon tableau commence par des en-têtes clairs." },
    { group: "Vérification", text: "Ne pas se contenter de voir un résultat apparaître : se demander s'il est logique, si la formule utilise la bonne plage, si les nombres sont bien saisis et si les formats ne masquent pas une erreur." },
    { group: "Communication", text: "Transformer des données en information visuelle simple : un graphique correctement titré et légendé aide le lecteur à comprendre sans lire toutes les lignes du tableau." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Découvrir l'environnement du tableur",
      icon: "Table",
      blocks: [
        { type: "text", html: "Un <strong>tableur</strong> est un logiciel qui présente l'information sous forme de grille. Cette grille est composée de <strong>lignes</strong> numérotées et de <strong>colonnes</strong> identifiées par des lettres. L'intersection d'une ligne et d'une colonne forme une <strong>cellule</strong>. Par exemple, la cellule <em>B3</em> se trouve à l'intersection de la colonne B et de la ligne 3 : cette adresse permet de désigner précisément un emplacement dans la feuille." },
        { type: "text", html: "Un fichier Excel est appelé <strong>classeur</strong>. Un classeur peut contenir une ou plusieurs <strong>feuilles</strong> : une feuille peut contenir les données brutes, une autre les calculs, une autre encore les graphiques ou la synthèse. L'apprenant doit comprendre dès le départ que le tableur est organisé en niveaux : classeur, feuille, ligne, colonne, cellule et plage." },
        { type: "infographic", kind: "tree", title: "Le tableur est organisé en niveaux", data: { root: "Classeur (.xlsx)", nodes: [
          { label: "Feuille 1 — Données", children: [{ label: "Lignes (1, 2, 3…)" }, { label: "Colonnes (A, B, C…)" }, { label: "Cellule (ex. B3)" }, { label: "Plage (ex. A1:D10)" }] },
          { label: "Feuille 2 — Calculs" },
          { label: "Feuille 3 — Graphique" },
        ] } },
        { type: "text", html: "La <strong>cellule active</strong> est la cellule sélectionnée à un moment donné : c'est dans cette cellule que la saisie sera effectuée. Une <strong>plage</strong> est un ensemble de cellules voisines, par exemple <em>A1:D10</em>. Les plages sont indispensables pour les calculs : on additionne rarement une seule cellule, on additionne plutôt une série de valeurs." },
        { type: "keypoints", title: "Les éléments de l'interface", points: [
          "Le ruban regroupe les commandes, organisées par onglets.",
          "La barre de formule affiche le contenu réel de la cellule active.",
          "La zone Nom indique l'adresse de la cellule active.",
          "La grille, les onglets de feuille et la barre d'état complètent l'écran.",
        ] },
        { type: "callout", tone: "info", title: "Affichage et contenu réel", text: "Une cellule peut afficher un résultat, tandis que la barre de formule montre la formule qui produit ce résultat. Cette distinction est essentielle pour vérifier ses calculs." },
        { type: "callout", tone: "example", title: "Analogie pédagogique", text: "Le tableur ressemble à un cahier de registre. Chaque ligne correspond à une personne, une opération ou une observation ; chaque colonne correspond à une information : nom, date, montant, note, présence, statut. La différence est que le tableur calcule automatiquement et permet de visualiser rapidement les résultats." },
      ],
    },
    {
      id: "seq-2",
      title: "Saisir et organiser les données",
      icon: "Keyboard",
      blocks: [
        { type: "text", html: "La saisie des données est une étape plus importante qu'elle n'y paraît : un calcul correct dépend d'abord de données correctement saisies. Si un nombre est saisi comme du texte, le tableur peut ne pas le calculer correctement. Si une date est écrite de manière incohérente, elle peut être mal interprétée. Si une colonne mélange des noms, des montants et des commentaires, le tableau devient difficile à exploiter." },
        { type: "text", html: "Il faut donc distinguer les principaux <strong>types de données</strong> : le texte, les nombres, les dates, les pourcentages et les formules. Un nom d'élève est un texte. Une note sur 20 est un nombre. Une date de présence est une date. Un taux de réussite est un pourcentage. Une cellule commençant par le signe <em>égal</em> contient une formule." },
        { type: "infographic", kind: "table", title: "Cinq types de données à reconnaître", data: { columns: ["Exemple", "Type", "Pourquoi"], rows: [
          ["Kouassi Amani", "Texte", "C'est un nom : il ne doit pas être calculé."],
          ["15,5", "Nombre", "Valeur numérique pouvant entrer dans une moyenne."],
          ["29/06/2026", "Date", "Le format date permet de trier chronologiquement."],
          ["75 %", "Pourcentage", "Le format pourcentage convient à un taux."],
          ["=SOMME(B2:B10)", "Formule", "La cellule contient une instruction de calcul."],
        ] } },
        { type: "callout", tone: "tip", title: "Des en-têtes clairs", text: "La première ligne doit contenir des en-têtes explicites. « Note 1 » est préférable à « N1 » si le public risque de ne pas comprendre l'abréviation. Évitez aussi les cellules vides dans une colonne importante : elles perturbent le tri, le filtrage et l'interprétation." },
        { type: "callout", tone: "info", title: "La recopie incrémentée", text: "Si l'on saisit Janvier puis Février, le tableur peut proposer la suite des mois ; si l'on saisit 1 puis 2, il peut continuer 3, 4, 5. Cette fonction fait gagner du temps, mais il faut vérifier que la suite produite correspond bien à l'intention." },
      ],
    },
    {
      id: "seq-3",
      title: "Mettre en forme un tableau lisible",
      icon: "Paintbrush",
      blocks: [
        { type: "text", html: "La mise en forme n'a pas seulement une fonction esthétique : elle sert d'abord à rendre l'information <strong>lisible</strong>. Un tableau professionnel doit permettre d'identifier rapidement le titre, les colonnes, les données, les totaux et les résultats importants. Une mauvaise mise en forme peut conduire à des confusions, même lorsque les calculs sont corrects." },
        { type: "keypoints", title: "Les gestes de mise en forme essentiels", points: [
          "Ajuster la largeur des colonnes et la hauteur des lignes.",
          "Aligner les titres et mettre les en-têtes en gras.",
          "Appliquer des bordures sobres pour délimiter le tableau.",
          "Utiliser les couleurs avec modération.",
          "Choisir un format numérique adapté à chaque colonne.",
        ] },
        { type: "callout", tone: "warn", title: "Le signe ####", text: "Une colonne trop étroite affiche parfois des signes comme ####. Cela signifie généralement que la cellule n'a pas assez d'espace pour afficher la valeur : il suffit d'élargir la colonne." },
        { type: "text", html: "Le <strong>format des nombres</strong> est essentiel. Un montant d'argent doit être affiché avec le format monétaire ou comptable ; un taux doit être affiché en pourcentage ; une note peut être affichée avec une ou deux décimales ; une date doit avoir un format cohérent. Le format n'est pas qu'une apparence : il aide le lecteur à comprendre la nature de la donnée." },
        { type: "infographic", kind: "table", title: "Choisir le bon format selon la donnée", data: { columns: ["Donnée", "Format recommandé"], rows: [
          ["Montant d'argent", "Monétaire ou comptable"],
          ["Taux de réussite", "Pourcentage"],
          ["Note sur 20", "Nombre à une ou deux décimales"],
          ["Date de présence", "Date (format cohérent)"],
          ["Nom, fonction", "Texte (standard)"],
        ] } },
        { type: "callout", tone: "warn", title: "Éviter les excès", text: "Trop de couleurs, trop de polices, trop de cellules fusionnées ou des bordures trop lourdes nuisent à la lecture. Les cellules fusionnées compliquent le tri, le filtrage et l'exportation : dans une logique de données, la simplicité est souvent plus efficace que la décoration." },
      ],
    },
    {
      id: "seq-4",
      title: "Comprendre la logique des formules",
      icon: "Calculator",
      blocks: [
        { type: "text", html: "Une <strong>formule</strong> est une instruction demandant au tableur de calculer un résultat. Dans Excel, une formule commence toujours par le signe <strong>égal</strong>. Par exemple, <em>=B2+C2</em> additionne le contenu de B2 et de C2. La formule ne s'écrit pas comme une phrase : elle doit respecter une <strong>syntaxe précise</strong>." },
        { type: "callout", tone: "tip", title: "Une formule reste dynamique", text: "Si la valeur de B2 change, le résultat de =B2+C2 change automatiquement. C'est ce qui fait du tableur un outil puissant pour suivre des notes, des dépenses, des présences ou des indicateurs." },
        { type: "text", html: "Les <strong>opérateurs de base</strong> sont l'addition (+), la soustraction (-), la multiplication (*) et la division (/). Les <strong>parenthèses</strong> permettent de contrôler l'ordre des calculs. Par exemple, <em>=(B2+C2)/2</em> ne donne pas le même résultat que <em>=B2+C2/2</em>, car la division est traitée avant l'addition." },
        { type: "infographic", kind: "table", title: "Exemples de formules simples", data: { columns: ["Formule", "Calcul effectué"], rows: [
          ["=B2+C2", "Addition de deux cellules"],
          ["=B2-C2", "Différence entre deux cellules"],
          ["=B2*C2", "Multiplication"],
          ["=B2/C2", "Division"],
          ["=(B2+C2+D2)/3", "Moyenne manuelle de trois notes"],
        ] } },
        { type: "callout", tone: "example", title: "L'ordre des calculs", text: "=B2+C2/2 calcule d'abord C2/2 puis ajoute B2. Pour faire la moyenne de B2 et C2, il faut écrire =(B2+C2)/2 avec des parenthèses." },
      ],
    },
    {
      id: "seq-5",
      title: "Utiliser SOMME, MOYENNE et SI",
      icon: "Sigma",
      blocks: [
        { type: "text", html: "Les <strong>fonctions</strong> sont des formules prédéfinies : elles font gagner du temps et limitent les erreurs. La fonction <strong>SOMME</strong> additionne les valeurs d'une plage (total de dépenses, total de points, effectif, quantité). La fonction <strong>MOYENNE</strong> calcule la moyenne arithmétique de plusieurs valeurs. La fonction <strong>SI</strong> produit un résultat selon une condition." },
        { type: "infographic", kind: "table", title: "Trois fonctions essentielles", data: { columns: ["Fonction", "Exemple", "Résultat"], rows: [
          ["SOMME", "=SOMME(B2:D2)", "Total des cellules B2 à D2"],
          ["MOYENNE", "=MOYENNE(B2:D2)", "Moyenne des cellules B2 à D2"],
          ["SI", "=SI(E2>=10;\"Admis\";\"Refuse\")", "Décision selon la moyenne"],
        ] } },
        { type: "text", html: "La fonction SI est essentielle pour <strong>automatiser une décision</strong> simple. Par exemple, si la moyenne (en E2) est supérieure ou égale à 10, on affiche « Admis » ; sinon, on affiche « Refuse ». La fonction teste la condition, puis renvoie la première valeur si elle est vraie et la seconde si elle est fausse." },
        { type: "callout", tone: "warn", title: "Séparateur et langue", text: "Selon les versions et les langues, le séparateur d'arguments peut être le point-virgule (;) ou la virgule (,), et les noms de fonctions peuvent être traduits (SUM/SOMME, AVERAGE/MOYENNE, IF/SI)." },
        { type: "keypoints", title: "Pourquoi préférer une fonction à un calcul manuel", points: [
          "SOMME évite d'oublier une cellule sur une longue plage.",
          "MOYENNE évite d'écrire =(B2+C2+D2)/3 à la main.",
          "SI applique automatiquement la même règle de décision à chaque ligne.",
        ] },
      ],
    },
    {
      id: "seq-6",
      title: "Références relatives et absolues",
      icon: "Lock",
      blocks: [
        { type: "text", html: "Lorsque l'on recopie une formule vers le bas ou vers la droite, Excel adapte automatiquement les références : c'est une <strong>référence relative</strong>. Par exemple, si la formule <em>=B2+C2</em> est recopiée de la ligne 2 vers la ligne 3, elle devient <em>=B3+C3</em>. Ce comportement est très utile pour calculer les moyennes de plusieurs élèves." },
        { type: "text", html: "Dans certains cas, il faut <strong>bloquer une référence</strong> : on utilise alors le signe dollar. Si un taux de TVA se trouve en F1 et que l'on veut l'utiliser dans plusieurs lignes, on écrit <em>=B2*$F$1</em>. Le signe dollar indique que la référence F1 ne doit pas changer pendant la recopie : c'est une <strong>référence absolue</strong>." },
        { type: "infographic", kind: "two-columns", title: "Deux comportements à la recopie", data: { left: { title: "Référence relative", subtitle: "elle s'adapte", items: ["=B2+C2 → =B3+C3 (ligne suivante)", "Sert à répéter un même calcul sur chaque ligne", "Comportement par défaut"] }, right: { title: "Référence absolue", subtitle: "elle reste fixe", items: ["=B2*$F$1 garde toujours F1", "Sert à pointer une valeur unique (taux, constante)", "Se note avec le signe dollar $"] } } },
        { type: "callout", tone: "info", title: "Au niveau 1", text: "Il n'est pas nécessaire de maîtriser toutes les subtilités des références absolues. L'essentiel est de comprendre le principe : certaines références bougent pendant la recopie, d'autres doivent rester fixes." },
      ],
    },
    {
      id: "seq-7",
      title: "Trier, filtrer et vérifier les données",
      icon: "Filter",
      blocks: [
        { type: "text", html: "<strong>Trier</strong> des données consiste à les classer selon un critère : ordre alphabétique, ordre croissant, ordre décroissant, date la plus ancienne ou la plus récente. <strong>Filtrer</strong> consiste à n'afficher que les lignes répondant à un critère : par exemple les admis, les absents, les dépenses supérieures à un montant, ou les élèves d'une classe donnée." },
        { type: "callout", tone: "warn", title: "Ne jamais trier une seule colonne", text: "Avant de trier, sélectionnez tout le tableau ou utilisez les outils prévus par Excel, afin de ne pas séparer une ligne de ses données. Trier seulement une colonne de noms sans les notes correspondantes rend les informations fausses." },
        { type: "text", html: "La <strong>vérification</strong> fait partie de la compétence tableur. L'apprenant ne fait pas confiance aveuglément à l'outil : il contrôle la plage utilisée par une formule, compare le résultat à un calcul mental approximatif et repère les cellules vides ou incohérentes." },
        { type: "infographic", kind: "rules", title: "Les bons réflexes de vérification", data: { rules: [
          { icon: "Search", title: "Vérifier la plage", text: "Regarder dans la barre de formule si la plage utilisée est la bonne." },
          { icon: "Calculator", title: "Estimer mentalement", text: "Comparer le résultat affiché à un ordre de grandeur attendu." },
          { icon: "Eye", title: "Repérer les vides", text: "Chercher les cellules vides ou incohérentes qui faussent le calcul." },
          { icon: "AlertTriangle", title: "Se méfier des formats", text: "Un format peut masquer une erreur de saisie ; vérifier le contenu réel." },
        ] } },
      ],
    },
    {
      id: "seq-8",
      title: "Produire un graphique simple",
      icon: "BarChart3",
      blocks: [
        { type: "text", html: "Un <strong>graphique</strong> sert à représenter visuellement des données pour mieux les communiquer. Un <strong>histogramme</strong> permet de comparer des quantités entre catégories. Un <strong>graphique en secteurs</strong> peut montrer la répartition d'un total, mais il doit être utilisé avec prudence lorsque les catégories sont nombreuses." },
        { type: "infographic", kind: "steps", title: "Créer un graphique, étape par étape", data: { steps: [
          { title: "Sélectionner", text: "une plage de données pertinente" },
          { title: "Choisir le type", text: "histogramme ou secteurs selon le besoin" },
          { title: "Ajouter un titre", text: "clair et explicite" },
          { title: "Vérifier la légende", text: "et, si utile, les étiquettes de données" },
        ] } },
        { type: "callout", tone: "warn", title: "Rester sobre", text: "Un effet 3D inutile, trop de couleurs ou une échelle mal choisie peut tromper le lecteur. L'objectif n'est pas de décorer, mais de rendre l'information plus compréhensible." },
        { type: "callout", tone: "tip", title: "Titre et unité", text: "Un graphique sans titre ni unité est difficile à comprendre. Un titre comme « Moyennes des apprenants — Diagnostic CERTEL » permet de saisir immédiatement ce qui est représenté." },
      ],
    },
    {
      id: "seq-9",
      title: "Mise en page, impression et export PDF",
      icon: "FileText",
      blocks: [
        { type: "text", html: "Une feuille de calcul peut être correcte à l'écran et mal sortir à l'impression. Il faut donc utiliser l'<strong>aperçu avant impression</strong>, définir l'orientation de la page, les marges, la zone d'impression et l'ajustement à une page si nécessaire. L'<strong>export PDF</strong> est utile lorsque le document doit être partagé sans modification." },
        { type: "keypoints", title: "Vérifier avant de diffuser", points: [
          "Le titre du document est présent et lisible.",
          "Les en-têtes de colonnes sont clairs.",
          "Les totaux et les résultats sont corrects.",
          "Le graphique est titré et légendé.",
          "La date figure sur la feuille.",
        ] },
        { type: "callout", tone: "info", title: "Excel ou PDF ?", text: "Le fichier Excel sert souvent au travail modifiable ; le PDF sert à la communication ou à l'archivage, car il fige la mise en forme et empêche les modifications accidentelles." },
        { type: "callout", tone: "example", title: "À retenir", text: "Un tableur sert à organiser, calculer et visualiser des données. Un bon tableau commence par des en-têtes clairs, des données bien saisies et une organisation continue. Une formule commence par le signe égal ; SOMME, MOYENNE et SI calculent rapidement totaux, moyennes et décisions. Avant de partager un fichier, je vérifie les formules, les résultats, la mise en page et le graphique." },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "match", title: "Vocabulaire du tableur",
      instruction: "Associez chaque terme à sa définition.",
      pairs: [
        { left: "Classeur", right: "Fichier Excel contenant une ou plusieurs feuilles" },
        { left: "Feuille", right: "Page de calcul contenue dans un classeur" },
        { left: "Cellule", right: "Intersection entre une ligne et une colonne" },
        { left: "Plage", right: "Ensemble de cellules voisines (ex. A1:D10)" },
        { left: "Formule", right: "Instruction de calcul commençant par =" },
      ],
      feedback: "Le classeur est le fichier global (.xlsx) ; la feuille en est une page ; la cellule (ex. B3) est l'intersection colonne/ligne ; la plage regroupe plusieurs cellules ; la formule produit un résultat dynamique.",
    },
    {
      id: "f2", kind: "categorize", title: "Saisie et types de données",
      instruction: "Indiquez le type de donnée le plus approprié pour chaque exemple.",
      categories: ["Texte", "Nombre", "Date", "Pourcentage", "Formule"],
      items: [
        { label: "Kouassi Amani", category: "Texte" },
        { label: "15,5", category: "Nombre" },
        { label: "29/06/2026", category: "Date" },
        { label: "75 %", category: "Pourcentage" },
        { label: "=SOMME(B2:B10)", category: "Formule" },
      ],
      feedback: "Un nom est un texte (il ne se calcule pas) ; une note est un nombre ; une date se trie chronologiquement ; un taux s'affiche en pourcentage ; une cellule commençant par = contient une instruction de calcul.",
    },
    {
      id: "f3", kind: "match", title: "Choisir la bonne formule",
      instruction: "Associez chaque besoin à la formule adaptée (notes en B2:D2, moyenne en E2).",
      pairs: [
        { left: "Total des notes B2 à D2", right: "=SOMME(B2:D2)" },
        { left: "Moyenne des notes B2 à D2", right: "=MOYENNE(B2:D2)" },
        { left: "Afficher Admis si E2>=10, sinon Refuse", right: "=SI(E2>=10;\"Admis\";\"Refuse\")" },
        { left: "Multiplier la quantité B2 par le prix C2", right: "=B2*C2" },
      ],
      feedback: "SOMME additionne automatiquement toute la plage ; MOYENNE évite d'écrire =(B2+C2+D2)/3 ; SI teste une condition et renvoie un texte selon le résultat ; l'astérisque est l'opérateur de multiplication.",
    },
    {
      id: "f4", kind: "qcm", multiple: true, title: "Corriger un tableau",
      instruction: "Un tableau de notes contient des défauts. Quelles pratiques sont des erreurs à corriger ?",
      options: [
        { text: "Fusionner des cellules dans la zone de données", correct: true },
        { text: "Laisser des lignes vides au milieu du tableau", correct: true },
        { text: "Utiliser des en-têtes incompréhensibles comme « N1 »", correct: true },
        { text: "Calculer la moyenne avec une plage incorrecte", correct: true },
        { text: "Mettre la première ligne d'en-têtes en gras", correct: false },
      ],
      feedback: "La fusion dans la zone de données complique tri et filtre ; les lignes vides fragmentent le tableau ; des en-têtes obscurs nuisent à la lecture ; une mauvaise plage donne un résultat faux. Mettre les en-têtes en gras est, au contraire, une bonne pratique.",
    },
    {
      id: "f5", kind: "order", title: "Construire un graphique",
      instruction: "Remettez dans le bon ordre les étapes pour produire un graphique correct.",
      items: ["Sélectionner une plage de données pertinente", "Choisir un type de graphique adapté", "Ajouter un titre clair", "Vérifier la légende et les étiquettes", "Relire la sobriété du graphique avant diffusion"],
      feedback: "On sélectionne d'abord les données utiles, on choisit le type adapté, puis on titre, on vérifie la légende et on contrôle enfin la sobriété de l'ensemble.",
    },
    { id: "q1", kind: "qcm", title: "Qu'est-ce qu'un classeur ?", instruction: "Dans Excel, un classeur est :", options: [{ text: "Une cellule", correct: false }, { text: "Un fichier contenant une ou plusieurs feuilles", correct: true }, { text: "Une formule", correct: false }, { text: "Une imprimante", correct: false }], feedback: "Le classeur est le fichier Excel, généralement enregistré au format .xlsx." },
    { id: "q2", kind: "qcm", title: "Adresse d'une cellule", instruction: "La cellule C5 se trouve :", options: [{ text: "Colonne C, ligne 5", correct: true }, { text: "Colonne 5, ligne C", correct: false }, { text: "Feuille C, classeur 5", correct: false }, { text: "Page 5, tableau C", correct: false }], feedback: "L'adresse d'une cellule commence par la lettre de la colonne, puis le numéro de la ligne." },
    { id: "q3", kind: "qcm", title: "Additionner une plage", instruction: "Quelle formule additionne les cellules B2 à B10 ?", options: [{ text: "=MOYENNE(B2:B10)", correct: false }, { text: "=SOMME(B2:B10)", correct: true }, { text: "=SI(B2:B10)", correct: false }, { text: "=TEXTE(B2:B10)", correct: false }], feedback: "SOMME sert à additionner les valeurs d'une plage." },
    { id: "q4", kind: "qcm", title: "Le début d'une formule", instruction: "Une formule Excel commence généralement par :", options: [{ text: "+", correct: false }, { text: "@", correct: false }, { text: "=", correct: true }, { text: "#", correct: false }], feedback: "Le signe égal indique au tableur que la cellule contient un calcul." },
    { id: "q5", kind: "qcm", title: "Calculer une moyenne", instruction: "Quelle fonction permet de calculer une moyenne ?", options: [{ text: "SOMME", correct: false }, { text: "MOYENNE", correct: true }, { text: "SI", correct: false }, { text: "TRI", correct: false }], feedback: "MOYENNE calcule la moyenne arithmétique des valeurs d'une plage." },
    { id: "q6", kind: "qcm", title: "Rôle de la fonction SI", instruction: "La formule =SI(E2>=10;\"Admis\";\"Refuse\") sert à :", options: [{ text: "Additionner les notes", correct: false }, { text: "Trier les noms", correct: false }, { text: "Afficher une décision selon une condition", correct: true }, { text: "Insérer un graphique", correct: false }], feedback: "La fonction SI renvoie une valeur si la condition est vraie et une autre si elle est fausse." },
    { id: "q7", kind: "qcm", title: "Recopier une formule", instruction: "Que devient souvent =B2+C2 recopiée de la ligne 2 vers la ligne 3 ?", options: [{ text: "=B3+C3", correct: true }, { text: "La formule disparaît", correct: false }, { text: "Excel imprime la feuille", correct: false }, { text: "Le fichier se ferme", correct: false }], feedback: "Les références relatives s'adaptent automatiquement pendant la recopie." },
    { id: "q8", kind: "qcm", title: "Afficher certaines lignes", instruction: "Quel outil permet d'afficher uniquement certaines lignes d'un tableau ?", options: [{ text: "Filtre", correct: true }, { text: "Bordure", correct: false }, { text: "Police", correct: false }, { text: "Zoom", correct: false }], feedback: "Le filtre masque temporairement les lignes ne correspondant pas au critère." },
    { id: "q9", kind: "qcm", title: "Titrer un graphique", instruction: "Pourquoi ajouter un titre à un graphique ?", options: [{ text: "Pour ralentir le fichier", correct: false }, { text: "Pour expliquer ce que représente le graphique", correct: true }, { text: "Pour supprimer les données", correct: false }, { text: "Pour empêcher l'impression", correct: false }], feedback: "Un titre rend le graphique compréhensible pour le lecteur." },
    { id: "q10", kind: "qcm", title: "Avant d'imprimer", instruction: "Avant d'imprimer une feuille Excel, il est recommandé de :", options: [{ text: "Supprimer toutes les formules", correct: false }, { text: "Vérifier l'aperçu avant impression", correct: true }, { text: "Changer tous les nombres en texte", correct: false }, { text: "Fermer le classeur sans enregistrer", correct: false }], feedback: "L'aperçu permet de vérifier les pages, les marges et la lisibilité." },
    { id: "q11", kind: "truefalse", title: "Une formule dynamique", instruction: "Vrai ou faux ?", statement: "Si la valeur d'une cellule utilisée par une formule change, le résultat de la formule se met à jour automatiquement.", answer: true, feedback: "Vrai : une formule reste dynamique. Si B2 change, le résultat de =B2+C2 est recalculé automatiquement." },
    { id: "q12", kind: "truefalse", title: "Référence absolue", instruction: "Vrai ou faux ?", statement: "Le signe dollar dans =B2*$F$1 sert à bloquer la référence F1 pour qu'elle ne change pas pendant la recopie.", answer: true, feedback: "Vrai : $F$1 est une référence absolue ; elle reste fixe alors que B2 s'adapte d'une ligne à l'autre." },
    { id: "q13", kind: "truefalse", title: "Trier une seule colonne", instruction: "Vrai ou faux ?", statement: "On peut trier en toute sécurité une seule colonne de noms sans sélectionner les données associées.", answer: false, feedback: "Faux : trier une seule colonne sépare les noms de leurs données et rend les informations fausses. Il faut sélectionner tout le tableau." },
    { id: "q14", kind: "truefalse", title: "Le signe ####", instruction: "Vrai ou faux ?", statement: "Quand une cellule affiche ####, cela signifie généralement que la colonne est trop étroite pour afficher la valeur.", answer: true, feedback: "Vrai : il suffit le plus souvent d'élargir la colonne pour que la valeur s'affiche." },
    { id: "q15", kind: "qcm", title: "Cellules fusionnées", instruction: "Pourquoi éviter de fusionner des cellules dans la zone de données ?", options: [{ text: "Cela complique le tri, le filtrage et l'exportation", correct: true }, { text: "Cela supprime les formules", correct: false }, { text: "Cela change la langue d'Excel", correct: false }, { text: "Cela imprime automatiquement la feuille", correct: false }], feedback: "Les cellules fusionnées perturbent les opérations sur les données ; on réserve la fusion au titre, pas à la zone de données." },
    { id: "q16", kind: "qcm", title: "L'ordre des calculs", instruction: "Quelle formule calcule correctement la moyenne de B2 et C2 ?", options: [{ text: "=B2+C2/2", correct: false }, { text: "=(B2+C2)/2", correct: true }, { text: "=B2+C2*2", correct: false }, { text: "=B2/C2", correct: false }], feedback: "Sans parenthèses, =B2+C2/2 divise d'abord C2 par 2. Les parenthèses =(B2+C2)/2 imposent d'additionner avant de diviser." },
  ],
  caseStudy: {
    title: "Étude de cas — Budget mensuel d'un club scolaire",
    scenario:
      "Le responsable d'un club scolaire vous transmet les dépenses suivantes : transport 12 000 F, communication 5 000 F, impression 8 000 F, collation 15 000 F, fournitures 10 000 F. Il souhaite connaître le total des dépenses, la moyenne par catégorie et la part de chaque dépense dans le total. Les montants seront saisis en B2:B6.",
    questions: [
      "Quelle formule écrire en B7 pour obtenir le total des dépenses, et en B8 pour la moyenne par catégorie ?",
      "Comment calculer en C2 la part de la dépense Transport dans le total, puis la recopier jusqu'à C6 ? Quel format appliquer ?",
      "Quels sont le total, la moyenne et la part de chaque catégorie ?",
      "Quel type de graphique proposeriez-vous, et pourquoi ?",
    ],
    corrige: [
      "B7 : =SOMME(B2:B6) pour le total ; B8 : =MOYENNE(B2:B6) pour la moyenne par catégorie.",
      "C2 : =B2/$B$7 (référence absolue sur le total B7), puis recopier jusqu'à C6. On applique ensuite le format Pourcentage à la plage C2:C6.",
      "Total = 50 000 F ; moyenne = 10 000 F (cinq catégories totalisant 50 000 F). Parts : Transport 24 %, Communication 10 %, Impression 16 %, Collation 30 %, Fournitures 20 %. La plus grande dépense est la collation, avec 30 % du total.",
      "Un graphique en secteurs convient pour représenter les parts d'un total ; un histogramme conviendrait aussi pour comparer les montants entre catégories. Dans les deux cas, le graphique doit être titré et légendé.",
    ],
  },
};
