import type { N1Module } from "./types";

/** Niveau 1 — Module 6 : Sécurité numérique et initiation à l'IA générative. */
export const MODULE_6: N1Module = {
  code: "N1-M6",
  slug: "module-6",
  num: 6,
  title: "Sécurité numérique et initiation à l'IA générative",
  subtitle:
    "Sécuriser ses usages numériques de base et utiliser une IA générative avec méthode, prudence et esprit critique.",
  duration: "18 heures · 2 semaines",
  finalite:
    "Sécuriser les usages numériques de base — mots de passe, menaces, données personnelles — et utiliser une IA générative avec méthode, prudence et esprit critique.",
  objectives: [
    "Créer et gérer des mots de passe robustes.",
    "Comprendre l'authentification à deux facteurs (2FA) et verrouiller sa session.",
    "Identifier un message frauduleux : hameçonnage, arnaque, usurpation d'identité.",
    "Expliquer les risques liés aux données personnelles et adopter les bons réflexes.",
    "Régler les paramètres de confidentialité et limiter la surexposition.",
    "Comprendre ce qu'est une IA générative, ses possibilités et ses limites.",
    "Utiliser une IA générative pour produire un premier texte utile.",
    "Rédiger une consigne (prompt) claire selon la formule Rôle-Tâche-Contexte-Format.",
    "Vérifier et corriger une réponse de l'IA à partir d'une source fiable.",
  ],
  competences: [
    { group: "Sécurité", text: "Protéger ses comptes : créer un mot de passe robuste, ne pas le partager, activer une protection renforcée (2FA) et verrouiller sa session." },
    { group: "Vigilance", text: "Repérer les indices d'hameçonnage, éviter de cliquer sur les liens ou pièces jointes suspects et vérifier par un canal officiel." },
    { group: "Données personnelles", text: "Reconnaître une donnée personnelle, limiter la surexposition et régler les paramètres de confidentialité." },
    { group: "IA générative", text: "Obtenir un brouillon utile avec une IA, rédiger une consigne claire, puis vérifier les faits et corriger pour produire un contenu fiable." },
    { group: "Transversales", text: "Adopter une posture responsable : esprit critique, éthique, vérification et jugement humain dans les usages numériques." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Comprendre l'enjeu de la sécurité numérique",
      icon: "Shield",
      blocks: [
        { type: "text", html: "Après avoir appris à utiliser l'ordinateur, les outils bureautiques, Internet, la messagerie et le cloud, il faut maintenant <strong>sécuriser ses usages</strong> et découvrir l'intelligence artificielle générative de manière raisonnée. Il ne s'agit pas seulement de cliquer sur un outil, mais d'adopter une <strong>posture responsable</strong> : protéger ses comptes, reconnaître les arnaques, limiter l'exposition de ses données et garder son esprit critique." },
        { type: "text", html: "Un utilisateur débutant commet souvent les mêmes erreurs : un mot de passe faible, un clic sur un lien frauduleux, une diffusion excessive d'informations personnelles ou une confiance aveugle dans une réponse générée par une IA. L'objectif de ce module est précisément d'<strong>éviter ces erreurs les plus courantes</strong>." },
        { type: "infographic", kind: "categories", title: "Quatre erreurs à éviter", data: { columns: [
          { title: "Mot de passe", accent: "#DC2626", items: [{ label: "Trop court ou trop simple" }, { label: "Réutilisé partout" }, { label: "Partagé avec d'autres" }] },
          { title: "Clic impulsif", accent: "#EA580C", items: [{ label: "Cliquer dans l'urgence" }, { label: "Ouvrir une pièce jointe inconnue" }, { label: "Saisir son mot de passe sur un faux site" }] },
          { title: "Surexposition", accent: "#6D5DF5", items: [{ label: "Tout publier sur soi" }, { label: "Diffuser des données d'autrui" }, { label: "Partages en accès public" }] },
          { title: "Confiance aveugle", accent: "#0891B2", items: [{ label: "Copier une réponse IA sans la lire" }, { label: "Ne rien vérifier" }, { label: "Confier des données sensibles" }] },
        ] } },
        { type: "callout", tone: "info", title: "Cadre de référence", text: "Les compétences visées rejoignent le cadre européen DigComp 2.2 (sécurité, gestion de l'information, création de contenu) et, pour l'IA, les recommandations de l'UNESCO : usage centré sur l'humain, esprit critique, éthique et vérification." },
      ],
    },
    {
      id: "seq-2",
      title: "Créer et gérer des mots de passe robustes",
      icon: "Lock",
      blocks: [
        { type: "text", html: "Le mot de passe est souvent la <strong>première barrière</strong> entre un compte numérique et une personne malveillante. Il protège la messagerie, les fichiers cloud, les réseaux sociaux, les plateformes de formation et parfois les moyens de paiement. Un mot de passe faible, réutilisé ou partagé rend l'utilisateur vulnérable." },
        { type: "text", html: "Un mot de passe robuste n'est pas seulement un mot compliqué : il doit être suffisamment <strong>long</strong>, difficile à deviner, non lié à l'identité de l'utilisateur et différent selon les services importants. La <strong>longueur</strong> compte souvent plus que la complexité artificielle : une phrase longue et imprévisible est plus sûre qu'un mot court agrémenté de quelques symboles." },
        { type: "infographic", kind: "table", title: "Du plus faible au plus robuste", data: { columns: ["Mot de passe (fictif)", "Niveau", "Pourquoi"], rows: [
          ["123456", "Faible", "Suite très courante, devinée ou testée automatiquement."],
          ["Awa2026", "Faible", "Contient un prénom et une année, trop lié à l'identité."],
          ["Soleil!19", "Moyen", "Un symbole et des chiffres, mais court et mot courant."],
          ["CERTEL@2026", "Moyen", "Lisible mais lié au contexte de formation et à l'année."],
          ["TroisMangues!Rivière-72-Cahier", "Robuste", "Long, mémorisable, imprévisible et non lié à l'utilisateur."],
        ] } },
        { type: "callout", tone: "warn", title: "L'erreur la plus grave : la réutilisation", text: "Utiliser le même mot de passe pour sa messagerie, son réseau social, son cloud et sa plateforme de formation est dangereux : la compromission d'un seul service ouvre l'accès à tous les autres. Les comptes critiques (messagerie principale, cloud, banque, administration) méritent chacun un mot de passe différent." },
        { type: "callout", tone: "tip", title: "La phrase de passe", text: "Une bonne pratique consiste à combiner des mots sans lien direct, enrichis de chiffres ou de symboles, et à utiliser si possible un gestionnaire de mots de passe pour les conserver." },
      ],
    },
    {
      id: "seq-3",
      title: "Renforcer la protection : 2FA et verrouillage",
      icon: "KeyRound",
      blocks: [
        { type: "text", html: "L'<strong>authentification à deux facteurs</strong>, appelée 2FA ou MFA, ajoute une seconde preuve d'identité. Même si le mot de passe est connu d'un tiers, celui-ci ne peut pas toujours se connecter sans ce second facteur : un code reçu dans une application, une notification de validation, une clé physique ou la biométrie." },
        { type: "infographic", kind: "two-columns", title: "Le second facteur : du moins au plus robuste", data: { left: { title: "Mieux que rien", subtitle: "à activer si rien d'autre", items: ["Code reçu par SMS", "Question de sécurité"] }, right: { title: "Plus robuste", subtitle: "à privilégier", items: ["Application d'authentification (code à usage unique)", "Notification de validation", "Clé de sécurité physique", "Biométrie (empreinte, visage)"] } } },
        { type: "text", html: "La sécurité ne concerne pas que les mots de passe. Dans une salle informatique, un cybercafé ou un bureau partagé, il faut <strong>verrouiller sa session</strong> lorsqu'on s'éloigne, fermer les comptes ouverts et éviter d'enregistrer ses mots de passe dans un navigateur public." },
        { type: "keypoints", title: "Les gestes de confidentialité au quotidien", points: [
          "Verrouiller ou fermer sa session dès que l'on quitte le poste.",
          "Ne pas enregistrer ses mots de passe sur un ordinateur partagé.",
          "Activer la 2FA sur les comptes importants lorsque c'est possible.",
        ] },
      ],
    },
    {
      id: "seq-4",
      title: "Reconnaître l'hameçonnage et les arnaques",
      icon: "AlertTriangle",
      blocks: [
        { type: "text", html: "L'<strong>hameçonnage</strong>, ou <em>phishing</em>, est une technique par laquelle un fraudeur tente de pousser une personne à révéler un mot de passe, un code, une information bancaire ou une donnée personnelle. Le message peut être un e-mail, un SMS, un message de messagerie instantanée, une fausse notification de livraison ou une fausse alerte de sécurité. Le principe est toujours le même : <strong>créer l'urgence, imiter une autorité et pousser à agir vite</strong>." },
        { type: "infographic", kind: "rules", title: "Les signaux d'alerte d'un message frauduleux", data: { rules: [
          { icon: "Mail", title: "Expéditeur étrange", text: "Adresse incohérente avec le nom affiché, domaine inhabituel." },
          { icon: "AlertTriangle", title: "Urgence et menace", text: "Compte fermé, pénalité, délai très court pour faire peur." },
          { icon: "Lock", title: "Demande de secret", text: "On vous réclame votre mot de passe ou un code de confirmation." },
          { icon: "Search", title: "Lien trompeur", text: "Lien raccourci ou imitant un domaine officiel sans correspondre." },
          { icon: "FileText", title: "Pièce jointe inattendue", text: "Document non demandé, logo mal utilisé, formule impersonnelle." },
        ] } },
        { type: "callout", tone: "tip", title: "Méthode des 5 questions", text: "Qui m'écrit ? Que me demande-t-on ? Pourquoi maintenant ? Où mène le lien ? Quelle preuve indépendante puis-je utiliser pour vérifier ?" },
        { type: "callout", tone: "warn", title: "La règle d'or face à la peur", text: "Lorsqu'un message crée de la peur ou de la précipitation, il faut ralentir. Un vrai service administratif, bancaire ou scolaire ne demande jamais un mot de passe par e-mail. On vérifie l'expéditeur, on survole le lien sans cliquer, on ouvre le site officiel dans un nouvel onglet, on contacte par un canal connu et on signale si nécessaire." },
      ],
    },
    {
      id: "seq-5",
      title: "Protéger ses données personnelles",
      icon: "Eye",
      blocks: [
        { type: "text", html: "Une <strong>donnée personnelle</strong> est une information qui permet d'identifier directement ou indirectement une personne : nom, photo, numéro de téléphone, adresse e-mail, numéro d'identification, localisation, voix, adresse IP, identifiant de compte, notes scolaires ou informations médicales. Certaines données semblent banales lorsqu'elles sont isolées, mais deviennent <strong>sensibles une fois regroupées</strong>." },
        { type: "text", html: "La <strong>surexposition</strong> consiste à publier ou transmettre trop d'informations sur soi ou sur les autres : photo d'enfant avec uniforme et nom d'école, emploi du temps, localisation en temps réel, numéro personnel dans un groupe public, document administratif non flouté, capture d'écran contenant une adresse ou un code. Les risques sont nombreux : usurpation d'identité, harcèlement, ciblage publicitaire excessif, vol de compte ou atteinte à la réputation." },
        { type: "infographic", kind: "table", title: "Est-ce une donnée personnelle ?", data: { columns: ["Information", "Nature", "Risque principal"], rows: [
          ["Nom et prénom", "Oui", "Permet d'identifier directement une personne."],
          ["Photo d'un élève avec badge visible", "Oui", "Révèle l'identité et l'établissement, expose l'élève."],
          ["Adresse e-mail professionnelle", "Oui", "Permet de contacter et d'identifier dans le cadre pro."],
          ["Modèle d'un ordinateur", "Parfois", "Donnée indirecte si associée à un utilisateur."],
          ["Mot de passe", "Secret d'authentification", "Ne se partage jamais : donne accès au compte."],
        ] } },
        { type: "callout", tone: "tip", title: "Le réflexe de minimisation", text: "Ne donner que les informations nécessaires au service demandé. Devant un formulaire, se demander si la date de naissance, l'adresse, la photo ou le numéro est vraiment utile. Régler les paramètres de confidentialité, limiter la visibilité des publications et ne pas diffuser les informations d'autrui sans consentement." },
      ],
    },
    {
      id: "seq-6",
      title: "Découvrir l'IA générative",
      icon: "Sparkles",
      blocks: [
        { type: "text", html: "Une <strong>IA générative</strong> est un système capable de produire du texte, des images, du son, du code, des idées ou des synthèses à partir d'une consigne donnée par l'utilisateur. Elle fonctionne par <strong>production probabiliste</strong> : elle peut produire des réponses utiles, mais aussi inexactes, incomplètes ou biaisées." },
        { type: "text", html: "L'IA peut aider à rédiger un courriel, reformuler un texte, proposer un plan, résumer un document, générer des idées ou améliorer la clarté d'un message. Elle devient un <strong>assistant de production</strong>, mais ne doit pas être considérée comme une autorité absolue." },
        { type: "callout", tone: "info", title: "À retenir", text: "L'IA propose, l'humain vérifie, corrige et assume. Pour un débutant : ne pas fournir de données sensibles à l'IA, ne pas copier une réponse sans la lire, vérifier les faits importants et reformuler dans son propre style." },
        { type: "callout", tone: "warn", title: "Règle d'or", text: "Ne jamais confier à une IA publique des mots de passe, données bancaires, dossiers médicaux, informations confidentielles d'élèves ou documents institutionnels sensibles non autorisés." },
        { type: "keypoints", title: "Ce que l'IA peut et ne peut pas", points: [
          "Elle peut : produire un brouillon de texte, reformuler, résumer, proposer des idées.",
          "Elle ne garantit pas la vérité : elle peut inventer une référence ou une date (hallucination).",
          "Elle ne remplace pas la vérification ni le jugement humain.",
        ] },
      ],
    },
    {
      id: "seq-7",
      title: "Rédiger un prompt clair (R-T-C-F)",
      icon: "FileText",
      blocks: [
        { type: "text", html: "Le <strong>prompt</strong> est la consigne adressée à l'IA. Une consigne vague produit souvent une réponse vague ; une consigne claire augmente les chances d'obtenir un résultat utile. Pour un débutant, on enseigne la formule <strong>R-T-C-F</strong> : Rôle, Tâche, Contexte, Format." },
        { type: "infographic", kind: "steps", title: "La formule R-T-C-F", data: { steps: [
          { title: "Rôle", text: "Indiquer le rôle attendu de l'IA. Ex. : « Agis comme un assistant administratif. »" },
          { title: "Tâche", text: "Dire précisément ce qu'il faut produire. Ex. : « Rédige un e-mail professionnel. »" },
          { title: "Contexte", text: "Donner les informations nécessaires. Ex. : « pour inviter à une séance de diagnostic CERTEL. »" },
          { title: "Format", text: "Préciser la forme de sortie. Ex. : « un objet, un message de 120 mots, une formule de politesse. »" },
        ] } },
        { type: "callout", tone: "example", title: "Un prompt complet", text: "« Agis comme un assistant administratif. Rédige un e-mail professionnel pour inviter des apprenants à une séance de diagnostic CERTEL. Le ton doit être cordial et clair. Le message doit préciser la date, l'heure, le lieu, les documents à apporter et se terminer par une formule de politesse. Propose aussi un objet d'e-mail. »" },
        { type: "text", html: "Après la réponse, l'apprenant <strong>relit et corrige</strong>. Il peut demander une amélioration (plus court, plus formel, plus chaleureux, adapté à un public scolaire), puis vérifier les informations factuelles : date, heure, lieu, noms, liens, chiffres et consignes." },
      ],
    },
    {
      id: "seq-8",
      title: "Vérifier et corriger une réponse de l'IA",
      icon: "Check",
      blocks: [
        { type: "text", html: "La <strong>vérification</strong> est la compétence la plus importante de cette initiation. Une IA peut inventer une référence, se tromper de date, donner une définition imprécise, mélanger des notions ou produire un texte trop général. L'apprenant doit comparer la réponse à une <strong>source fiable</strong>, vérifier les éléments sensibles et corriger les erreurs. La vérification n'est pas facultative : elle fait partie intégrante du travail." },
        { type: "infographic", kind: "steps", title: "Vérifier en quatre étapes", data: { steps: [
          { title: "Lire", text: "Lire entièrement la réponse de l'IA." },
          { title: "Surligner", text: "Repérer les affirmations vérifiables." },
          { title: "Chercher", text: "Confronter à une source fiable (site institutionnel, manuel, page d'aide officielle, document du formateur)." },
          { title: "Corriger", text: "Reformuler le texte avec ses propres mots en indiquant les modifications." },
        ] } },
        { type: "callout", tone: "tip", title: "Méthode V.E.R.I.F.", text: "Vérifier les faits — Examiner la source — Repérer les erreurs — Identifier les informations sensibles — Finaliser avec ses propres mots." },
        { type: "infographic", kind: "rules", title: "Sources fiables pour un débutant", data: { rules: [
          { icon: "Shield", title: "Site institutionnel", text: "Page officielle d'une administration ou d'une organisation reconnue." },
          { icon: "FileText", title: "Manuel ou document officiel", text: "Document de formation ou support fourni par le formateur." },
          { icon: "Info", title: "Aide officielle d'un outil", text: "Page d'aide publiée par l'éditeur du logiciel ou du service." },
        ] } },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "categorize", title: "Classer des mots de passe",
      instruction: "Classez chaque mot de passe fictif selon sa robustesse.",
      categories: ["Faible", "Moyen", "Robuste"],
      items: [
        { label: "123456", category: "Faible" },
        { label: "Awa2026", category: "Faible" },
        { label: "password", category: "Faible" },
        { label: "Soleil!19", category: "Moyen" },
        { label: "CERTEL@2026", category: "Moyen" },
        { label: "TroisMangues!Rivière-72-Cahier", category: "Robuste" },
      ],
      feedback: "Les suites courantes et les mots de passe liés à l'identité (prénom, année) sont faibles. Un symbole et quelques chiffres rendent un mot moyen, mais c'est la longueur et l'imprévisibilité (phrase de passe) qui font un mot de passe robuste.",
    },
    {
      id: "f2", kind: "order", title: "Réagir à un e-mail suspect",
      instruction: "Remettez dans le bon ordre les étapes d'une réaction sûre face à un e-mail suspect.",
      items: ["Ralentir et ne pas cliquer dans la précipitation", "Vérifier l'adresse réelle de l'expéditeur", "Survoler le lien sans cliquer pour voir où il mène", "Ouvrir le site officiel dans un nouvel onglet ou contacter par un canal connu", "Signaler ou supprimer le message"],
      feedback: "Face à un message qui crée l'urgence, on ralentit d'abord, on vérifie l'expéditeur et le lien sans cliquer, on passe par un canal officiel pour confirmer, puis on signale ou supprime.",
    },
    {
      id: "f3", kind: "categorize", title: "Indices d'hameçonnage",
      instruction: "Pour chaque élément d'un message, indiquez s'il s'agit d'un indice suspect ou d'un élément rassurant.",
      categories: ["Indice suspect", "Élément rassurant"],
      items: [
        { label: "« Votre compte sera fermé dans 2 heures »", category: "Indice suspect" },
        { label: "Demande de saisir votre mot de passe", category: "Indice suspect" },
        { label: "Lien imitant un domaine officiel sans correspondre", category: "Indice suspect" },
        { label: "Formule impersonnelle « cher utilisateur »", category: "Indice suspect" },
        { label: "Pièce jointe attendue que vous aviez demandée", category: "Élément rassurant" },
      ],
      feedback: "L'urgence artificielle, la demande de mot de passe, un lien trompeur et une formule impersonnelle sont des signaux d'alerte typiques. Une pièce jointe réellement attendue, à l'inverse, n'est pas en soi suspecte.",
    },
    {
      id: "f4", kind: "order", title: "Vérifier une réponse de l'IA",
      instruction: "Remettez dans le bon ordre les quatre étapes de la vérification d'une réponse IA.",
      items: ["Lire entièrement la réponse", "Surligner les affirmations vérifiables", "Chercher une source fiable", "Corriger le texte en indiquant les modifications"],
      feedback: "On lit d'abord toute la réponse, on repère ce qui est vérifiable, on confronte à une source fiable, puis on corrige avec ses propres mots.",
    },
    {
      id: "f5", kind: "match", title: "La formule R-T-C-F",
      instruction: "Associez chaque élément du prompt à sa fonction.",
      pairs: [
        { left: "Rôle", right: "Indiquer le rôle attendu de l'IA" },
        { left: "Tâche", right: "Dire précisément ce qu'il faut produire" },
        { left: "Contexte", right: "Donner les informations nécessaires" },
        { left: "Format", right: "Préciser la forme de sortie attendue" },
      ],
      feedback: "R-T-C-F : le Rôle situe l'IA, la Tâche dit quoi produire, le Contexte fournit les informations utiles, et le Format précise la forme attendue (longueur, structure, objet).",
    },
    { id: "q1", kind: "qcm", title: "Le mot de passe le plus robuste", instruction: "Quel mot de passe est le plus robuste ?", options: [{ text: "123456", correct: false }, { text: "Awa2026", correct: false }, { text: "TroisMangues!Rivière-72-Cahier", correct: true }, { text: "password", correct: false }], feedback: "Il est long, peu prévisible et plus difficile à deviner ou à tester automatiquement." },
    { id: "q2", kind: "qcm", title: "Réutiliser un mot de passe", instruction: "Pourquoi faut-il éviter de réutiliser le même mot de passe ?", options: [{ text: "Pour aller plus vite", correct: false }, { text: "Parce qu'un compte compromis peut exposer les autres", correct: true }, { text: "Parce que les sites l'interdisent toujours", correct: false }, { text: "Parce que cela empêche Internet de fonctionner", correct: false }], feedback: "La réutilisation facilite les attaques en cascade : un seul service compromis peut donner accès à tous les autres." },
    { id: "q3", kind: "qcm", title: "Que signifie 2FA ?", instruction: "Que signifie 2FA ?", options: [{ text: "Deux fichiers archivés", correct: false }, { text: "Authentification à deux facteurs", correct: true }, { text: "Deux formulaires administratifs", correct: false }, { text: "Deux fois plus d'accès", correct: false }], feedback: "La 2FA ajoute une seconde preuve d'identité en plus du mot de passe." },
    { id: "q4", kind: "qcm", title: "E-mail demandant le mot de passe", instruction: "Face à un e-mail demandant votre mot de passe, que faut-il faire ?", options: [{ text: "Répondre rapidement", correct: false }, { text: "Envoyer le mot de passe", correct: false }, { text: "Ne pas répondre et vérifier par un canal officiel", correct: true }, { text: "Transférer à tous ses contacts", correct: false }], feedback: "Aucun service sérieux ne demande un mot de passe par e-mail : il faut vérifier via un canal officiel." },
    { id: "q5", kind: "qcm", title: "Indice de phishing", instruction: "Quel indice peut signaler un hameçonnage ?", options: [{ text: "Un lien étrange imitant un domaine officiel", correct: true }, { text: "Une formule de politesse correcte", correct: false }, { text: "Un message court", correct: false }, { text: "Une pièce jointe connue et attendue", correct: false }], feedback: "Les liens imitant un domaine officiel sans y correspondre sont fréquents dans les fraudes." },
    { id: "q6", kind: "qcm", title: "Une donnée personnelle", instruction: "Une donnée personnelle est :", options: [{ text: "Une information permettant d'identifier une personne", correct: true }, { text: "Une couleur de fond", correct: false }, { text: "Une touche du clavier", correct: false }, { text: "Un câble réseau", correct: false }], feedback: "Une donnée personnelle identifie directement ou indirectement une personne." },
    { id: "q7", kind: "qcm", title: "Protéger sa vie privée", instruction: "Quelle pratique protège la vie privée ?", options: [{ text: "Publier son emploi du temps complet", correct: false }, { text: "Partager ses documents en accès public par défaut", correct: false }, { text: "Limiter les informations visibles et contrôler les droits d'accès", correct: true }, { text: "Enregistrer tous ses mots de passe sur un ordinateur public", correct: false }], feedback: "Maîtriser ce que l'on publie et les droits d'accès réduit les risques." },
    { id: "q8", kind: "qcm", title: "Quitter un poste partagé", instruction: "Que faut-il faire avant de quitter un ordinateur partagé ?", options: [{ text: "Laisser la session ouverte", correct: false }, { text: "Fermer ou verrouiller la session", correct: true }, { text: "Laisser ses fichiers affichés", correct: false }, { text: "Noter son mot de passe sur l'écran", correct: false }], feedback: "Verrouiller ou fermer la session protège les données contre un accès non autorisé." },
    { id: "q9", kind: "qcm", title: "Capacités de l'IA générative", instruction: "Une IA générative peut :", options: [{ text: "Produire du texte ou des idées", correct: true }, { text: "Garantir toujours la vérité", correct: false }, { text: "Remplacer toute vérification humaine", correct: false }, { text: "Protéger automatiquement tous les secrets", correct: false }], feedback: "Elle peut produire un contenu, mais celui-ci doit toujours être vérifié par l'humain." },
    { id: "q10", kind: "qcm", title: "Qu'est-ce qu'un prompt ?", instruction: "Un prompt est :", options: [{ text: "Une consigne donnée à l'IA", correct: true }, { text: "Un virus", correct: false }, { text: "Une imprimante", correct: false }, { text: "Un mot de passe", correct: false }], feedback: "Le prompt est la consigne qui guide la production de l'IA." },
    { id: "q11", kind: "qcm", title: "Un prompt plus clair", instruction: "Quel élément rend un prompt plus clair ?", options: [{ text: "Une demande vague", correct: false }, { text: "Le rôle, la tâche, le contexte et le format attendu", correct: true }, { text: "Une seule phrase sans précision", correct: false }, { text: "Le silence", correct: false }], feedback: "La formule Rôle-Tâche-Contexte-Format oriente bien mieux la réponse." },
    { id: "q12", kind: "qcm", title: "À ne pas fournir à une IA publique", instruction: "Quelle information ne faut-il pas fournir à une IA publique ?", options: [{ text: "Un thème général de rédaction", correct: false }, { text: "Un style souhaité", correct: false }, { text: "Un mot de passe ou une donnée confidentielle", correct: true }, { text: "Une consigne de longueur", correct: false }], feedback: "Les données sensibles (mots de passe, données bancaires, informations confidentielles) doivent être protégées." },
    { id: "q13", kind: "qcm", title: "Une information importante de l'IA", instruction: "Si une IA donne une information importante, il faut :", options: [{ text: "Copier sans lire", correct: false }, { text: "Vérifier avec une source fiable", correct: true }, { text: "Publier immédiatement", correct: false }, { text: "Supprimer la source", correct: false }], feedback: "La vérification face à une source fiable est indispensable." },
    { id: "q14", kind: "qcm", title: "Une hallucination d'IA", instruction: "Une hallucination d'IA désigne :", options: [{ text: "Une réponse potentiellement inventée ou fausse", correct: true }, { text: "Un fichier Excel", correct: false }, { text: "Une panne d'écran", correct: false }, { text: "Un mot de passe solide", correct: false }], feedback: "L'IA peut produire des contenus plausibles mais erronés : c'est une hallucination." },
    { id: "q15", kind: "truefalse", title: "Même mot de passe partout", instruction: "Vrai ou faux ?", statement: "Pour être sécurisé, il faut utiliser le même mot de passe très compliqué partout afin de ne pas l'oublier.", answer: false, feedback: "Faux : utiliser le même mot de passe partout est dangereux. Si un service est compromis, tous les comptes sont exposés. Il faut des mots de passe robustes et différents pour les comptes importants, aidé si besoin d'un gestionnaire, et activer la 2FA." },
    { id: "q16", kind: "truefalse", title: "L'usage responsable de l'IA", instruction: "Vrai ou faux ?", statement: "L'usage responsable de l'IA implique transparence, vérification et jugement humain.", answer: true, feedback: "Vrai : la responsabilité humaine reste centrale. On reste transparent sur l'usage de l'IA, on vérifie ses réponses et on garde son jugement." },
    { id: "q17", kind: "truefalse", title: "La longueur du mot de passe", instruction: "Vrai ou faux ?", statement: "Une phrase de passe longue et imprévisible peut être plus sûre qu'un mot court agrémenté de quelques symboles.", answer: true, feedback: "Vrai : la longueur compte souvent plus que la complexité artificielle. Une phrase longue et imprévisible résiste mieux aux tentatives automatiques." },
    {
      id: "q18", kind: "match", title: "Méthode des 5 questions",
      instruction: "Associez chaque question de la méthode à ce qu'elle permet de vérifier.",
      pairs: [
        { left: "Qui m'écrit ?", right: "L'identité réelle de l'expéditeur" },
        { left: "Que me demande-t-on ?", right: "La nature de la demande (mot de passe, paiement…)" },
        { left: "Pourquoi maintenant ?", right: "L'urgence artificielle créée par le message" },
        { left: "Où mène le lien ?", right: "La destination réelle du lien sans cliquer" },
      ],
      feedback: "La méthode des 5 questions force à ralentir et à examiner chaque aspect du message avant d'agir.",
    },
  ],
  caseStudy: {
    title: "Étude de cas — L'e-mail urgent et le prompt de Koffi",
    scenario:
      "Koffi, animateur d'un centre de formation, reçoit un e-mail intitulé « URGENT - Votre compte sera fermé aujourd'hui ». Le message, signé « Service technique », lui demande de cliquer sur http://securite-compte-verification.example-login.com et de saisir son mot de passe dans les 2 heures, sinon toutes ses données seront supprimées. Le même jour, il doit inviter des apprenants à une séance de diagnostic CERTEL. Pressé, il demande à une IA : « Fais-moi un message pour les participants. » L'IA répond un texte général, et une autre réponse affirme qu'« il faut utiliser le même mot de passe très compliqué partout afin de ne pas l'oublier ».",
    questions: [
      "Relevez au moins cinq indices suspects dans l'e-mail reçu, puis indiquez la réaction correcte.",
      "Améliorez le prompt « Fais-moi un message pour les participants » en appliquant la formule R-T-C-F.",
      "L'affirmation de l'IA sur les mots de passe est-elle correcte ? Corrigez-la.",
      "Citez trois règles personnelles de sécurité que Koffi devrait adopter.",
    ],
    corrige: [
      "Indices suspects : urgence artificielle et menace de fermeture, formule impersonnelle (« cher utilisateur »), demande du mot de passe, lien ne correspondant pas à un domaine officiel, absence d'identification claire du service, pression psychologique. Réaction : ne pas cliquer, ne pas saisir son mot de passe, vérifier via le site officiel ou le service informatique, puis signaler ou supprimer le message.",
      "Prompt amélioré : « Agis comme un assistant administratif de formation (Rôle). Rédige un e-mail professionnel de 120 mots (Tâche/Format) destiné aux participants d'un diagnostic CERTEL Niveau 1 (Contexte). Le message doit indiquer la date, l'heure, le lieu, les documents à apporter, rappeler d'arriver 15 minutes avant le début et se terminer par une formule de politesse. Propose aussi un objet clair. » Les éléments variables (date, lieu) sont à compléter par l'humain, pas par l'IA.",
      "L'affirmation est dangereuse : utiliser le même mot de passe partout augmente le risque, car un seul service compromis expose tous les comptes. Version corrigée : « Il faut utiliser des mots de passe robustes et différents pour les comptes importants. Un gestionnaire de mots de passe peut aider à les conserver, et l'authentification à deux facteurs doit être activée lorsque c'est possible. »",
      "Trois règles : utiliser des mots de passe robustes et différents pour les comptes critiques (et activer la 2FA) ; ne jamais cliquer dans l'urgence ni saisir son mot de passe sur un lien reçu par e-mail, mais vérifier par un canal officiel ; ne pas fournir de données confidentielles à une IA publique et toujours vérifier ses réponses.",
    ],
  },
};
