import type { N1Module } from "./types";

/** Niveau 1 — Module 4 : Présentations claires avec PowerPoint. */
export const MODULE_4: N1Module = {
  code: "N1-M4",
  slug: "module-4",
  num: 4,
  title: "Présentations claires avec PowerPoint",
  subtitle:
    "Transformer ses idées en supports visuels clairs, lisibles et professionnels qui soutiennent la parole.",
  duration: "15 heures · 1,5 semaine",
  finalite:
    "Concevoir un support de présentation clair avec PowerPoint : structurer un message, créer des diapositives lisibles, intégrer des visuels avec mesure, exporter en PDF et présenter oralement en trois minutes.",
  objectives: [
    "Structurer le message d'une présentation en définissant un objectif, un public cible et un fil conducteur.",
    "Créer des diapositives lisibles en respectant la sobriété visuelle, le contraste, l'alignement et l'aération.",
    "Intégrer du texte, des images, des formes et des icônes de manière cohérente et utile.",
    "Appliquer un thème, une palette de couleurs et des transitions mesurées.",
    "Utiliser les notes de l'orateur et le mode présentateur pour soutenir une prise de parole courte.",
    "Vérifier, enregistrer, exporter en PDF et diffuser une présentation conforme.",
    "Présenter oralement un contenu en trois minutes à partir d'un support de 6 à 8 diapositives.",
  ],
  competences: [
    { group: "Communication", text: "Clarifier un message et organiser un discours en introduction, développement et conclusion." },
    { group: "Création numérique", text: "Produire un support PowerPoint professionnel, cohérent et lisible." },
    { group: "Design fonctionnel", text: "Choisir des couleurs, des polices, des images et des espacements adaptés au public." },
    { group: "Accessibilité", text: "Préserver la lisibilité par un bon contraste, une taille de texte suffisante et une hiérarchie visuelle simple." },
    { group: "Diffusion", text: "Exporter en PDF, présenter en plein écran et transmettre un livrable exploitable." },
    { group: "Autonomie", text: "Relire, corriger, harmoniser et améliorer un support à partir d'une grille de critères." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Comprendre le rôle d'une présentation",
      icon: "Presentation",
      blocks: [
        { type: "text", html: "Une présentation n'est pas un document Word projeté sur un écran. Le document écrit peut contenir beaucoup de phrases, de détails et de références. La diapositive, elle, doit <strong>guider l'attention</strong> : elle sert de repère visuel pour l'auditoire et de support de parole pour l'orateur. Une erreur fréquente consiste à copier tout le texte d'un rapport dans PowerPoint : cette pratique alourdit le support, fatigue le public et réduit la qualité de l'écoute." },
        { type: "callout", tone: "tip", title: "La règle d'or", text: "Une diapositive doit porter une seule idée principale. Elle peut être illustrée par un mot-clé, une image, une courte phrase, un schéma ou quelques données. La diapositive est un panneau indicateur : elle oriente, elle ne remplace pas le trajet." },
        { type: "text", html: "La norme d'utilisabilité <strong>ISO 9241-11</strong> insiste sur le fait qu'un produit se juge dans un contexte d'usage précis : des utilisateurs, des objectifs et un environnement déterminés. Appliqué à PowerPoint, un bon support n'existe pas dans l'absolu : il est bon s'il permet à un public donné de comprendre efficacement un message donné dans une situation donnée." },
        { type: "keypoints", title: "Trois questions à se poser avant de commencer", points: [
          "Question de départ : que doit retenir le public à la fin de ma présentation ?",
          "Question de contexte : à qui je m'adresse — élèves, collègues, responsables, parents, partenaires ?",
          "Question d'action : qu'est-ce que le public doit comprendre, décider ou faire après mon intervention ?",
        ] },
      ],
    },
    {
      id: "seq-2",
      title: "Définir l'objectif, le public et le fil conducteur",
      icon: "Target",
      blocks: [
        { type: "text", html: "Avant d'ouvrir PowerPoint, l'apprenant doit rédiger une <strong>intention de présentation en une phrase</strong>. Cette phrase répond à trois éléments : le public, le sujet et le résultat attendu. Par exemple : « Présenter aux parents les avantages d'une plateforme de suivi scolaire afin qu'ils comprennent comment accompagner leurs enfants. » Cette phrase devient la boussole du support." },
        { type: "text", html: "Le <strong>public</strong> conditionne le vocabulaire, le niveau de détail, les exemples et le rythme. On ne présente pas de la même manière devant des élèves de collège, des enseignants, des responsables administratifs ou des partenaires techniques. Une présentation destinée à <em>convaincre</em> met en avant des bénéfices et des preuves ; une présentation destinée à <em>former</em> progresse étape par étape ; une présentation destinée à <em>rendre compte</em> privilégie les résultats, les indicateurs et les décisions attendues." },
        { type: "callout", tone: "info", title: "Limiter le nombre de diapositives", text: "Le fil conducteur évite la dispersion : titre, contexte, problème, solution, exemple, conclusion. Pour un débutant, il est préférable de se limiter à 6 ou 8 diapositives afin d'apprendre la concision." },
        { type: "infographic", kind: "table", title: "Le rôle recommandé de chaque diapositive", data: { columns: ["Diapositive", "Rôle recommandé"], rows: [
          ["1. Titre", "Annoncer clairement le sujet, le nom de l'auteur et le contexte."],
          ["2. Contexte", "Expliquer brièvement pourquoi le sujet est important."],
          ["3. Problème ou besoin", "Montrer la difficulté, la question ou l'objectif à atteindre."],
          ["4. Idée principale 1", "Présenter le premier argument, élément ou résultat."],
          ["5. Idée principale 2", "Présenter le deuxième argument, élément ou résultat."],
          ["6. Illustration ou exemple", "Montrer un cas, une image, un schéma ou une donnée simple."],
          ["7. Conclusion", "Résumer les messages essentiels."],
          ["8. Merci / contacts", "Clôturer et ouvrir les échanges."],
        ] } },
      ],
    },
    {
      id: "seq-3",
      title: "Découvrir l'interface de PowerPoint",
      icon: "LayoutDashboard",
      blocks: [
        { type: "text", html: "PowerPoint est organisé autour d'un <strong>ruban</strong> qui regroupe les principales commandes. Chaque onglet correspond à une famille d'actions : <em>Accueil</em> pour saisir et mettre en forme, <em>Insertion</em> pour ajouter images, formes, icônes, tableaux ou graphiques, <em>Création</em> pour choisir un thème, <em>Transitions</em> et <em>Animations</em> pour introduire du mouvement, <em>Diaporama</em> pour lancer la présentation." },
        { type: "infographic", kind: "categories", title: "Les onglets du ruban et leur usage", data: { columns: [
          { title: "Concevoir le message", accent: "#0891B2", items: [{ label: "Accueil", hint: "saisir, mettre en forme" }, { label: "Insertion", hint: "images, formes, tableaux" }] },
          { title: "Habiller le support", accent: "#6D5DF5", items: [{ label: "Création", hint: "thème et couleurs" }, { label: "Transitions", hint: "passage entre diapositives" }, { label: "Animations", hint: "mouvement des objets" }] },
          { title: "Présenter et vérifier", accent: "#16A34A", items: [{ label: "Diaporama", hint: "plein écran" }, { label: "Révision", hint: "orthographe" }, { label: "Affichage", hint: "modes de travail" }] },
        ] } },
        { type: "callout", tone: "tip", title: "Préférer les dispositions (layouts)", text: "Une disposition est une organisation prédéfinie de la diapositive : titre seul, titre et contenu, deux contenus, comparaison, image avec légende. Les débutants placent souvent tous les objets à la main ; mieux vaut choisir une disposition adaptée, car elle maintient les alignements et la cohérence." },
        { type: "text", html: "Microsoft présente PowerPoint comme un outil permettant de créer une présentation, d'ajouter et de formater du texte, puis d'ajouter des images, formes et graphiques. Cette logique correspond à la progression du module : <strong>d'abord le message, ensuite la structure, enfin les éléments visuels</strong>." },
      ],
    },
    {
      id: "seq-4",
      title: "Concevoir des diapositives lisibles",
      icon: "Eye",
      blocks: [
        { type: "text", html: "La lisibilité dépend d'abord du <strong>contraste</strong>. Un texte gris clair sur fond blanc, ou bleu foncé sur fond noir, devient difficile à lire. Les recommandations <strong>WCAG 2.2</strong> indiquent un rapport de contraste d'au moins 4,5:1 pour le texte normal au niveau AA. Même conçues pour le web, elles offrent un repère utile : un texte projeté doit être lisible par tous, y compris au fond de la salle." },
        { type: "callout", tone: "warn", title: "La taille de police", text: "Une diapositive n'est pas une page imprimée : un texte lisible sur l'écran de l'ordinateur peut devenir illisible une fois projeté. Règle pratique : éviter les textes inférieurs à 24 points pour le contenu courant, et utiliser des titres encore plus grands." },
        { type: "text", html: "La <strong>sobriété visuelle</strong> ne signifie pas pauvreté graphique : elle signifie maîtrise. Une présentation professionnelle peut être élégante avec peu de couleurs, peu de polices et une organisation régulière. Le vide n'est pas une perte d'espace : il permet de respirer et de mieux distinguer les éléments importants." },
        { type: "keypoints", title: "Sept réflexes de lisibilité", points: [
          "Utiliser une ou deux polices au maximum.",
          "Limiter les couleurs à une palette cohérente.",
          "Éviter les arrière-plans trop chargés.",
          "Ne pas dépasser une idée principale par diapositive.",
          "Remplacer les longs paragraphes par des mots-clés ou de courtes phrases.",
          "Aligner les objets au lieu de les disposer au hasard.",
          "Laisser des espaces autour des textes et des images.",
        ] },
      ],
    },
    {
      id: "seq-5",
      title: "Intégrer texte, images, formes et icônes",
      icon: "Image",
      blocks: [
        { type: "text", html: "Une image doit <strong>servir le message</strong> : illustrer un contexte, montrer un exemple, rendre une idée plus concrète ou provoquer une émotion adaptée. Une image décorative sans lien clair distrait l'auditoire. Les principes de Mayer invitent à éviter les éléments superflus et à rapprocher les mots des images correspondantes afin de réduire la charge cognitive inutile." },
        { type: "callout", tone: "warn", title: "Qualité et droits d'auteur", text: "Une image insérée doit être de bonne qualité, proportionnée et correctement recadrée. Il ne faut pas l'étirer dans un seul sens, car cela déforme personnes, objets ou logos. Toutes les images trouvées sur Internet ne sont pas libres d'utilisation : préférer des images libres, des icônes intégrées à PowerPoint ou des illustrations produites par l'apprenant." },
        { type: "text", html: "Les <strong>formes</strong> et les <strong>icônes</strong> servent à hiérarchiser, signaler, séparer ou schématiser : une flèche indique un processus, un encadré met en évidence une définition, une icône représente une idée. Mais ces éléments doivent rester constants — mêmes styles, mêmes couleurs, mêmes épaisseurs de trait. L'harmonie graphique résulte de la <em>répétition contrôlée</em>." },
        { type: "infographic", kind: "two-columns", title: "Une image utile ou une image distrayante ?", data: { left: { title: "Image utile", subtitle: "sert la compréhension", items: ["Icône de disque dur pour parler de sauvegarde", "Capture d'écran d'une procédure", "Schéma simple d'un processus", "Photo concrète d'un cas réel"] }, right: { title: "Image distrayante", subtitle: "à éviter", items: ["Photo décorative sans lien avec le sujet", "Image humoristique hors propos", "Visuel étiré et déformé", "Image de basse qualité ou pixelisée"] } } },
      ],
    },
    {
      id: "seq-6",
      title: "Utiliser transitions et animations avec mesure",
      icon: "Sparkles",
      blocks: [
        { type: "text", html: "Les transitions et animations donnent du dynamisme, mais elles peuvent vite devenir gênantes. Le mouvement doit avoir une <strong>fonction pédagogique ou communicationnelle</strong> : révéler progressivement les étapes d'un raisonnement, empêcher le public de tout lire d'un coup, accompagner une démonstration. À l'inverse, une animation spectaculaire répétée sans nécessité détourne l'attention." },
        { type: "callout", tone: "info", title: "Pour un module d'initiation", text: "Limiter les transitions à un effet simple et uniforme (fondu ou apparition). Les animations doivent rester rares et cohérentes. Règle de base : si l'animation n'aide pas à comprendre, elle doit être supprimée." },
        { type: "infographic", kind: "rules", title: "Mouvement : oui ou non ?", data: { rules: [
          { icon: "Check", title: "Révéler par étapes", text: "Faire apparaître les points l'un après l'autre pour accompagner le raisonnement." },
          { icon: "Check", title: "Effet uniforme", text: "Une même transition simple sur toute la présentation." },
          { icon: "X", title: "Effets multipliés", text: "Cinq animations différentes sur une seule diapositive distraient." },
          { icon: "AlertTriangle", title: "Masquer un défaut", text: "Une animation ne corrige pas un contenu surchargé : il faut le simplifier." },
        ] } },
        { type: "text", html: "Le dynamisme d'une présentation ne vient pas de la multiplication des effets : il vient de la <strong>clarté du message</strong>, du rythme de la parole, de la progression des idées et de l'interaction avec le public." },
      ],
    },
    {
      id: "seq-7",
      title: "Préparer la prise de parole",
      icon: "Mic",
      blocks: [
        { type: "text", html: "Une présentation claire doit être accompagnée d'une parole claire. L'apprenant prépare des <strong>notes de l'orateur</strong> : elles ne sont pas destinées à être lues mot à mot devant le public, mais servent de repères — phrase d'ouverture, exemple à donner, transition vers la diapositive suivante, conclusion à formuler." },
        { type: "callout", tone: "tip", title: "Le mode présentateur", text: "Il permet à l'orateur de voir ses notes, le minutage et la diapositive suivante, pendant que le public ne voit que la diapositive en cours. Faire une simulation avant la présentation réelle : certains apprenants découvrent trop tard un câble non branché, un écran mal détecté, un fichier non sauvegardé, une police absente ou une vidéo non intégrée." },
        { type: "text", html: "La <strong>simulation orale de trois minutes</strong> est un exercice essentiel : elle oblige à sélectionner l'essentiel, à regarder le public, à éviter la lecture intégrale et à respecter le temps. Consigne simple du formateur : une idée, une phrase forte et un exemple par diapositive." },
        { type: "keypoints", title: "Avant de présenter, je vérifie", points: [
          "Le matériel : câble, écran, son, fichier ouvert et sauvegardé.",
          "Mes notes de l'orateur, comme aide-mémoire et non comme texte à lire.",
          "Mon minutage, en répétant pour rester proche des trois minutes.",
        ] },
      ],
    },
    {
      id: "seq-8",
      title: "Vérifier, exporter et diffuser",
      icon: "FileCheck",
      blocks: [
        { type: "text", html: "La dernière étape consiste à <strong>vérifier la présentation avant diffusion</strong> : orthographe, alignement, taille du texte, images, transitions, cohérence des titres, numérotation et informations de contact. La relecture par un pair est très efficace, car l'auteur ne voit pas toujours ses propres erreurs." },
        { type: "infographic", kind: "steps", title: "De la relecture à la diffusion", data: { steps: [
          { title: "Relire", text: "orthographe, titres, alignements" },
          { title: "Faire relire", text: "par un pair pour repérer les oublis" },
          { title: "Enregistrer", text: "le fichier .pptx de travail" },
          { title: "Exporter", text: "une version .pdf pour le partage" },
          { title: "Vérifier le nom", text: "fichier clairement nommé" },
        ] } },
        { type: "callout", tone: "example", title: "Deux formats complémentaires", text: "Le fichier .pptx reste le fichier de travail modifiable ; le .pdf constitue la version de diffusion, stable, lisible sur différents appareils et moins dépendante des polices ou versions de PowerPoint. Pour une présentation orale, conserver les deux : .pptx pour présenter, .pdf pour partager." },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "order", title: "Identifier la bonne structure",
      instruction: "Remettez les diapositives dans l'ordre logique d'une présentation.",
      items: ["Titre", "Contexte", "Idée principale 1", "Idée principale 2", "Exemple", "Conclusion", "Merci / échanges"],
      feedback: "Le titre annonce le sujet, le contexte justifie l'intérêt, les idées développent le message, l'exemple rend le propos concret, la conclusion fixe les messages à retenir, et la dernière diapositive ouvre les échanges.",
    },
    {
      id: "f2", kind: "categorize", title: "Une image utile ou distrayante ?",
      instruction: "Pour une diapositive sur la sauvegarde des fichiers, classez chaque visuel.",
      categories: ["Visuel pertinent", "Visuel distrayant"],
      items: [
        { label: "Icône de disque dur", category: "Visuel pertinent" },
        { label: "Capture d'écran d'un dossier de sauvegarde", category: "Visuel pertinent" },
        { label: "Photo décorative de plage", category: "Visuel distrayant" },
        { label: "Image humoristique sans lien", category: "Visuel distrayant" },
      ],
      feedback: "L'icône de disque dur et la capture d'écran servent directement la compréhension ; la photo de plage et l'image humoristique distraient car elles n'aident ni à comprendre ni à mémoriser.",
    },
    {
      id: "f3", kind: "qcm", multiple: true, title: "Diagnostiquer une mauvaise diapositive",
      instruction: "Une diapositive contient 12 lignes de texte, une police de 12 points, un fond très coloré, trois images non alignées et cinq animations différentes. Quels problèmes faut-il corriger ?",
      options: [
        { text: "Le texte est trop long et doit être réduit à quelques points essentiels", correct: true },
        { text: "La police est trop petite et doit être agrandie", correct: true },
        { text: "Le fond gêne la lecture et doit être rendu sobre", correct: true },
        { text: "Les animations excessives doivent être limitées à un effet utile", correct: true },
        { text: "Il faut ajouter encore plus de couleurs pour attirer l'œil", correct: false },
      ],
      feedback: "Une diapositive surchargée se corrige en réduisant le texte, en agrandissant la police, en choisissant un fond sobre, en alignant les images et en supprimant les animations inutiles. Ajouter des couleurs aggraverait le problème.",
    },
    {
      id: "f4", kind: "match", title: "Un titre informatif",
      instruction: "Associez chaque titre vague à une version plus informative qui porte déjà le message.",
      pairs: [
        { left: "Résultats", right: "Le taux de participation a augmenté de 35 % en trois mois" },
        { left: "Introduction", right: "Pourquoi ce projet est nécessaire" },
        { left: "Conclusion", right: "Les trois messages à retenir" },
      ],
      feedback: "Un titre informatif informe immédiatement le public : il est plus utile qu'un titre générique car il porte déjà l'idée principale de la diapositive.",
    },
    { id: "q1", kind: "qcm", title: "Le rôle d'une diapositive", instruction: "Une diapositive efficace doit principalement :", options: [{ text: "Contenir tout le texte du discours", correct: false }, { text: "Soutenir le message oral", correct: true }, { text: "Remplacer la parole de l'orateur", correct: false }, { text: "Multiplier les effets visuels", correct: false }], feedback: "Une diapositive est un support visuel : elle aide le public à suivre le message, mais ne remplace pas l'explication orale." },
    { id: "q2", kind: "qcm", title: "Par où commencer", instruction: "Avant d'ouvrir PowerPoint, il faut d'abord :", options: [{ text: "Choisir les animations", correct: false }, { text: "Définir l'objectif et le public", correct: true }, { text: "Chercher une image décorative", correct: false }, { text: "Exporter en PDF", correct: false }], feedback: "La conception commence par l'intention de communication : à qui parle-t-on et pour quel résultat ?" },
    { id: "q3", kind: "qcm", title: "Une bonne règle pour débuter", instruction: "Une bonne règle pour débuter est :", options: [{ text: "Une idée principale par diapositive", correct: true }, { text: "Dix idées par diapositive", correct: false }, { text: "Aucune image", correct: false }, { text: "Autant de couleurs que possible", correct: false }], feedback: "Une idée par diapositive améliore la clarté et facilite l'attention." },
    { id: "q4", kind: "qcm", title: "Le texte trop petit", instruction: "Un texte trop petit est problématique parce qu'il :", options: [{ text: "Rend la diapositive plus moderne", correct: false }, { text: "Empêche une partie du public de lire", correct: true }, { text: "Augmente le poids du fichier", correct: false }, { text: "Supprime les images", correct: false }], feedback: "La lisibilité est indispensable, surtout en projection." },
    { id: "q5", kind: "qcm", title: "Quand utiliser une transition", instruction: "Une transition doit être utilisée :", options: [{ text: "Pour décorer toutes les diapositives", correct: false }, { text: "Pour faire rire le public", correct: false }, { text: "Lorsqu'elle accompagne utilement la progression", correct: true }, { text: "Pour masquer un mauvais contenu", correct: false }], feedback: "Les effets doivent soutenir la compréhension et non distraire." },
    { id: "q6", kind: "qcm", title: "Le mode présentateur", instruction: "Le mode présentateur sert à :", options: [{ text: "Modifier les images", correct: false }, { text: "Voir les notes et contrôler la présentation", correct: true }, { text: "Convertir le fichier en Word", correct: false }, { text: "Supprimer les diapositives", correct: false }], feedback: "Il aide l'orateur à gérer ses notes, le temps et la progression." },
    { id: "q7", kind: "qcm", title: "L'utilité du PDF", instruction: "Le format PDF est utile pour :", options: [{ text: "Garantir une diffusion plus stable", correct: true }, { text: "Ajouter automatiquement des animations", correct: false }, { text: "Remplacer le fichier modifiable", correct: false }, { text: "Supprimer toutes les images", correct: false }], feedback: "Le PDF conserve la mise en forme et facilite le partage, tandis que le .pptx reste le fichier de travail modifiable." },
    { id: "q8", kind: "qcm", title: "Une image insérée", instruction: "Une image insérée dans PowerPoint doit :", options: [{ text: "Être étirée librement", correct: false }, { text: "Avoir un lien avec le message", correct: true }, { text: "Remplacer tous les titres", correct: false }, { text: "Être toujours animée", correct: false }], feedback: "Un visuel doit aider à comprendre ou à mémoriser." },
    { id: "q9", kind: "qcm", title: "Le rôle d'un thème", instruction: "Un thème cohérent permet de :", options: [{ text: "Harmoniser la présentation", correct: true }, { text: "Empêcher l'export PDF", correct: false }, { text: "Supprimer les notes", correct: false }, { text: "Créer un virus", correct: false }], feedback: "Le thème aide à garder des styles réguliers d'une diapositive à l'autre." },
    { id: "q10", kind: "qcm", title: "La relecture finale", instruction: "La relecture finale porte notamment sur :", options: [{ text: "Orthographe, alignement, cohérence", correct: true }, { text: "Uniquement la couleur du titre", correct: false }, { text: "Uniquement la taille du fichier", correct: false }, { text: "Uniquement les sons", correct: false }], feedback: "La qualité finale dépend à la fois du contenu, de la forme et de la conformité technique." },
    { id: "q11", kind: "qcm", title: "Une présentation orale courte", instruction: "Une présentation orale courte doit être :", options: [{ text: "Lue mot à mot", correct: false }, { text: "Improvisée sans préparation", correct: false }, { text: "Structurée et chronométrée", correct: true }, { text: "Faite sans regarder le public", correct: false }], feedback: "La préparation permet de respecter le temps et de transmettre l'essentiel." },
    { id: "q12", kind: "qcm", title: "Les notes de l'orateur", instruction: "Les notes de l'orateur servent surtout à :", options: [{ text: "Écrire le discours complet sur la diapositive", correct: false }, { text: "Garder des repères de parole", correct: true }, { text: "Changer la couleur du fond", correct: false }, { text: "Exporter le fichier", correct: false }], feedback: "Elles aident l'orateur sans surcharger l'écran du public." },
    { id: "q13", kind: "qcm", title: "L'importance du contraste", instruction: "Le contraste est important parce qu'il :", options: [{ text: "Améliore la lisibilité", correct: true }, { text: "Réduit toujours le nombre de diapositives", correct: false }, { text: "Transforme le texte en image", correct: false }, { text: "Bloque les animations", correct: false }], feedback: "Un bon contraste permet au public de lire facilement, y compris au fond de la salle." },
    { id: "q14", kind: "truefalse", title: "Une diapositive surchargée", instruction: "Vrai ou faux ?", statement: "Une diapositive surchargée doit être simplifiée en retirant les éléments inutiles et en hiérarchisant l'information.", answer: true, feedback: "Vrai : il faut retirer les éléments inutiles, réduire le texte et hiérarchiser pour rendre la diapositive plus lisible et plus utile." },
    { id: "q15", kind: "truefalse", title: "La diapositive de conclusion", instruction: "Vrai ou faux ?", statement: "La diapositive de conclusion sert surtout à introduire un nouveau sujet.", answer: false, feedback: "Faux : la conclusion sert à rappeler les messages essentiels et à aider le public à les mémoriser, pas à ouvrir un nouveau sujet." },
    { id: "q16", kind: "qcm", title: "L'intérêt des dispositions", instruction: "Pourquoi utiliser une disposition (layout) plutôt que placer tous les objets à la main ?", options: [{ text: "Pour maintenir les alignements et la cohérence", correct: true }, { text: "Pour empêcher la sauvegarde", correct: false }, { text: "Pour réduire le contraste", correct: false }, { text: "Pour ajouter des virus", correct: false }], feedback: "Une disposition prédéfinie aide à garder des alignements réguliers et une organisation cohérente." },
  ],
  caseStudy: {
    title: "Étude de cas — La présentation de Koffi",
    scenario:
      "Koffi doit présenter aux parents les avantages d'une plateforme de suivi scolaire. Il copie tout le texte de son rapport dans PowerPoint : sa première diapositive contient 12 lignes en police de 12 points, sur un fond très coloré, avec trois images non alignées et cinq animations différentes. Ses titres sont vagues (« Introduction », « Résultats »). Il n'a prévu aucune note de l'orateur et compte lire ses diapositives mot à mot. Le fichier s'appelle « presentation finale vrai.pptx » et n'a pas été exporté.",
    questions: [
      "Identifiez quatre problèmes sur la première diapositive de Koffi.",
      "Rédigez l'intention de présentation en une phrase (public, sujet, résultat attendu).",
      "Proposez un plan de 6 à 8 diapositives avec des titres informatifs.",
      "Indiquez les bonnes pratiques à appliquer pour la prise de parole et la diffusion.",
    ],
    corrige: [
      "Quatre problèmes : le texte est trop long (réduire à quelques points), la police de 12 points est trop petite (passer à au moins 24 points), le fond très coloré nuit au contraste (choisir un fond sobre), et les images non alignées et les cinq animations distraient (aligner les images, limiter à un effet simple et uniforme).",
      "Intention : « Présenter aux parents les avantages d'une plateforme de suivi scolaire afin qu'ils comprennent comment accompagner leurs enfants. » Cette phrase fixe le public, le sujet et le résultat attendu.",
      "Plan possible : 1) Titre et auteur ; 2) Pourquoi suivre la scolarité de son enfant est important (contexte) ; 3) La difficulté actuelle de communication école-famille (problème) ; 4) Une plateforme accessible à tout moment (idée 1) ; 5) Des alertes et un suivi en temps réel (idée 2) ; 6) Exemple ou capture d'écran d'un tableau de bord ; 7) Ce qu'il faut retenir (conclusion) ; 8) Merci et contacts.",
      "Préparer des notes de l'orateur comme repères (sans les lire), répéter pour rester proche de trois minutes, utiliser le mode présentateur, regarder le public. Renommer le fichier clairement (par exemple Presentation_SuiviScolaire_Koffi_2026-06_V1.pptx), relire et faire relire par un pair, puis exporter en PDF pour la diffusion tout en conservant le .pptx modifiable.",
    ],
  },
};
