import type { N1Module } from "./types";

/** Niveau 1 — Module 5 : Internet, e-mail, cloud et collaboration en ligne. */
export const MODULE_5: N1Module = {
  code: "N1-M5",
  slug: "module-5",
  num: 5,
  title: "Internet, e-mail, cloud et collaboration en ligne",
  subtitle: "Rechercher, vérifier, communiquer, partager et collaborer en ligne avec efficacité et sécurité.",
  duration: "18 heures · 2 semaines",
  finalite:
    "Rendre l'apprenant capable de rechercher une information pertinente, d'évaluer la fiabilité d'une source, de communiquer par e-mail, de partager des fichiers dans le cloud et de participer à une réunion en visioconférence.",
  objectives: [
    "Effectuer une recherche d'information pertinente sur Internet en utilisant des mots-clés adaptés.",
    "Distinguer une source fiable d'une source incertaine ou douteuse, et recouper l'information.",
    "Rédiger et envoyer un e-mail professionnel avec objet, formule d'appel, message clair, politesse et pièce jointe.",
    "Distinguer les champs À, Cc et Cci, et les utiliser avec discernement.",
    "Organiser une boîte mail en dossiers, recherches et filtres simples.",
    "Téléverser, télécharger, renommer et classer des fichiers dans un espace cloud.",
    "Partager un fichier ou un dossier en définissant correctement les droits d'accès.",
    "Participer activement et correctement à une réunion Zoom, Teams ou Google Meet.",
    "Respecter les bonnes pratiques de confidentialité, de sécurité et d'étiquette numérique.",
  ],
  competences: [
    { group: "Recherche", text: "Construire une requête efficace : mots-clés précis, guillemets si nécessaire, opérateurs simples et choix raisonné des résultats." },
    { group: "Évaluation", text: "Vérifier la fiabilité d'une source à partir de l'auteur, de la date, de l'intention, des preuves et du recoupement, et repérer les signaux d'alerte." },
    { group: "Communication", text: "Envoyer un e-mail professionnel : objet explicite, destinataires pertinents, corps clair, pièces jointes nommées et formule de politesse." },
    { group: "Cloud", text: "Stocker et partager un fichier : dépôt dans le bon dossier, lien partagé, droits limités et suppression des accès inutiles." },
    { group: "Visioconférence", text: "Participer à une réunion en ligne : connexion à l'heure, micro et caméra maîtrisés, chat utilisé avec pertinence, parole claire." },
    { group: "Sécurité", text: "Protéger les informations : prudence face aux liens, mots de passe non partagés, pièces sensibles évitées ou protégées." },
  ],
  lessons: [
    {
      id: "seq-1",
      title: "Comprendre Internet et le navigateur Web",
      icon: "Globe",
      blocks: [
        { type: "text", html: "Internet est un <strong>réseau mondial</strong> qui permet à des ordinateurs, serveurs, téléphones et objets connectés d'échanger des informations. Pour l'utilisateur débutant, Internet apparaît surtout à travers le <strong>navigateur Web</strong> : le logiciel qui affiche les pages, ouvre les liens, lance les recherches et donne accès aux services en ligne. Les navigateurs les plus connus sont Chrome, Edge, Firefox, Safari ou Opera." },
        { type: "callout", tone: "info", title: "Trois mots souvent confondus", text: "Le navigateur est le logiciel qui ouvre les pages ; le moteur de recherche est un service qui aide à trouver des pages à partir de mots-clés ; le site Web est l'espace consultable (une institution, une université, une entreprise, un média)." },
        { type: "infographic", kind: "two-columns", title: "Navigateur, moteur, site : ne pas confondre", data: { left: { title: "Le navigateur", subtitle: "un logiciel", items: ["Chrome, Edge, Firefox, Safari, Opera", "Affiche les pages Web", "Gère les onglets et les favoris", "Conserve l'historique", "Permet le téléchargement"] }, right: { title: "Le moteur / le site", subtitle: "des services en ligne", items: ["Moteur de recherche : trouve des pages à partir de mots-clés", "Site Web : l'espace consultable d'une organisation", "On accède au moteur et aux sites grâce au navigateur"] } } },
        { type: "keypoints", title: "Les éléments à connaître dans le navigateur", points: [
          "Les onglets : ouvrir plusieurs pages sans perdre la page actuelle.",
          "La barre d'adresse : saisir une adresse ou une recherche.",
          "Les favoris : conserver un lien utile pour y revenir.",
          "L'historique : retrouver une page déjà consultée.",
          "Fermer les onglets inutiles pour garder un espace de travail clair.",
        ] },
      ],
    },
    {
      id: "seq-2",
      title: "Construire une requête de recherche efficace",
      icon: "Search",
      blocks: [
        { type: "text", html: "Une recherche efficace commence par une <strong>bonne question</strong>. Beaucoup d'apprenants saisissent des phrases vagues ou trop longues. Il faut transformer une question ordinaire en <strong>mots-clés pertinents</strong>. Au lieu de taper « je veux savoir comment créer un mot de passe solide », on cherche « créer mot de passe solide recommandations CNIL » : cette requête précise oriente le moteur vers des sources institutionnelles." },
        { type: "infographic", kind: "steps", title: "Une méthode en quatre étapes", data: { steps: [
          { title: "Définir le besoin", text: "que cherche-t-on exactement ?" },
          { title: "Extraire les mots importants", text: "garder les termes essentiels" },
          { title: "Choisir le type de source", text: "officielle, universitaire, média fiable" },
          { title: "Comparer les résultats", text: "ne pas retenir le premier venu" },
        ] } },
        { type: "infographic", kind: "table", title: "Quelques opérateurs simples", data: { columns: ["Opérateur", "Effet", "Exemple"], rows: [
          ["\"...\"", "Chercher une expression exacte", "\"éducation aux médias\""],
          ["- (signe moins)", "Exclure un mot", "jaguar -voiture"],
          ["site:", "Limiter à un domaine", "site:unesco.org éducation aux médias"],
        ] } },
        { type: "callout", tone: "tip", title: "Adapter à l'objectif", text: "Pour une information officielle, privilégier les sites gouvernementaux, institutionnels ou universitaires. Pour une actualité, vérifier la date et comparer plusieurs médias fiables. À ce niveau, l'objectif n'est pas la recherche avancée mais de bonnes habitudes méthodiques." },
      ],
    },
    {
      id: "seq-3",
      title: "Évaluer la fiabilité d'une information",
      icon: "ShieldCheck",
      blocks: [
        { type: "text", html: "Toute information trouvée en ligne ne doit pas être considérée comme vraie. Internet contient des documents scientifiques, des textes officiels, des opinions personnelles, des publicités, des contenus militants, des rumeurs et parfois de <strong>fausses nouvelles</strong>. L'apprenant doit adopter une posture de <strong>vérification</strong> avant de réutiliser une information." },
        { type: "infographic", kind: "categories", title: "La grille des cinq questions", data: { columns: [
          { title: "Qui ?", accent: "#0891B2", items: [{ label: "Qui parle ?" }, { label: "Auteur ou organisme identifié" }] },
          { title: "Quand ?", accent: "#6D5DF5", items: [{ label: "Date de publication" }, { label: "Date de mise à jour" }] },
          { title: "Pourquoi ?", accent: "#D97706", items: [{ label: "Intention de la page" }, { label: "Informer, vendre, convaincre ?" }] },
          { title: "Preuves & recoupement", accent: "#16A34A", items: [{ label: "Quelles preuves sont données ?" }, { label: "Retrouve-t-on l'info ailleurs ?" }] },
        ] } },
        { type: "callout", tone: "warn", title: "Popularité n'est pas fiabilité", text: "Un contenu très partagé n'est pas automatiquement exact. Une vidéo convaincante n'est pas forcément vérifiée. Une capture d'écran peut être manipulée. Une information doit, autant que possible, être reliée à une source primaire, officielle ou reconnue." },
        { type: "callout", tone: "example", title: "Justifier son choix", text: "Dans une formation certifiante, on doit savoir écrire une courte justification : « J'ai retenu cette source parce qu'elle est publiée par une institution reconnue, datée, signée et confirmée par une deuxième source. »" },
      ],
    },
    {
      id: "seq-4",
      title: "Repérer une information douteuse ou une fausse nouvelle",
      icon: "AlertTriangle",
      blocks: [
        { type: "text", html: "Une information douteuse présente souvent des <strong>signaux d'alerte</strong>. L'apprenant doit apprendre à <strong>ralentir avant de partager</strong> et à suivre une procédure simple de vérification." },
        { type: "infographic", kind: "rules", title: "Les signaux d'alerte", data: { rules: [
          { icon: "AlertTriangle", title: "Titre exagéré", text: "Promesse spectaculaire, ton sensationnaliste, appel au partage urgent." },
          { icon: "X", title: "Sans auteur ni date", text: "Absence d'auteur identifiable et de date de publication ou de mise à jour." },
          { icon: "Eye", title: "Image sans contexte", text: "Photo ou capture présentée seule, sans source ni explication." },
          { icon: "Info", title: "Confusion fait / opinion", text: "Mélange entre information documentée et avis personnel ou publicité." },
        ] } },
        { type: "infographic", kind: "steps", title: "Une procédure de vérification", data: { steps: [
          { title: "Lire au-delà du titre", text: "ne pas s'arrêter à l'accroche" },
          { title: "Identifier la source", text: "qui publie cette information ?" },
          { title: "Chercher la date", text: "l'information est-elle récente ?" },
          { title: "Rechercher ailleurs", text: "un autre moteur, un autre média fiable" },
          { title: "Vérifier l'image", text: "et demander conseil en cas de doute" },
        ] } },
        { type: "callout", tone: "tip", text: "Cette posture critique protège l'apprenant contre la désinformation et renforce sa responsabilité dans les espaces numériques." },
      ],
    },
    {
      id: "seq-5",
      title: "Rédiger un e-mail professionnel",
      icon: "Mail",
      blocks: [
        { type: "text", html: "L'e-mail professionnel est un <strong>acte de communication</strong> : il doit être clair, concis, poli et exploitable. Un bon e-mail comporte un objet explicite, un destinataire correctement choisi, une formule d'appel, un message organisé, une formule de politesse, une signature et, si nécessaire, une pièce jointe correctement nommée." },
        { type: "infographic", kind: "tree", title: "Les éléments d'un e-mail", data: { root: "E-mail professionnel", nodes: [
          { label: "Objet explicite", children: [{ label: "« Transmission du rapport de diagnostic — Formation CERTEL N1-M5 »" }] },
          { label: "Destinataires", children: [{ label: "À : destinataire principal" }, { label: "Cc : personnes en copie" }, { label: "Cci : copie cachée" }] },
          { label: "Corps du message", children: [{ label: "Formule d'appel" }, { label: "Contexte, demande, action attendue" }, { label: "Formule de politesse" }, { label: "Signature" }] },
          { label: "Pièce jointe", children: [{ label: "Fichier nommé clairement" }] },
        ] } },
        { type: "callout", tone: "warn", title: "Un objet vague ne suffit pas", text: "Un objet comme « Demande » est trop vague. L'objet doit permettre au destinataire de comprendre le sujet avant d'ouvrir le message." },
        { type: "infographic", kind: "table", title: "Distinguer À, Cc et Cci", data: { columns: ["Champ", "Usage", "Visibilité des adresses"], rows: [
          ["À", "Destinataires principaux, responsables de l'action", "Visibles de tous"],
          ["Cc", "Personnes informées mais non responsables de l'action", "Visibles de tous"],
          ["Cci", "Copie cachée, à utiliser avec prudence et transparence", "Masquées aux autres destinataires"],
        ] } },
      ],
    },
    {
      id: "seq-6",
      title: "Joindre, recevoir et enregistrer une pièce jointe",
      icon: "Paperclip",
      blocks: [
        { type: "text", html: "<strong>Joindre</strong> un fichier signifie l'envoyer avec l'e-mail. Avant d'ajouter une pièce jointe, il faut vérifier que le fichier est le bon, qu'il est correctement nommé, que son format est lisible et que sa taille est raisonnable. Pour un document finalisé, le format <strong>PDF</strong> est souvent préférable : il préserve la mise en forme et limite les modifications involontaires." },
        { type: "keypoints", title: "Avant d'ajouter une pièce jointe", points: [
          "Vérifier que c'est bien le bon fichier.",
          "Vérifier qu'il est correctement nommé.",
          "Vérifier que le format est lisible par le destinataire (PDF pour un document finalisé).",
          "Vérifier que la taille reste raisonnable.",
        ] },
        { type: "callout", tone: "warn", title: "Recevoir une pièce jointe : prudence", text: "Ne pas ouvrir un fichier inattendu, surtout s'il provient d'un expéditeur inconnu ou s'il demande une action inhabituelle. Certains fichiers peuvent contenir des programmes malveillants. Les pièces sensibles doivent être traitées avec discrétion et stockées dans un dossier approprié." },
        { type: "callout", tone: "tip", text: "Enregistrer une pièce jointe reçue dans un dossier choisi, plutôt que de laisser les téléchargements s'accumuler sans classement dans le dossier Téléchargements." },
      ],
    },
    {
      id: "seq-7",
      title: "Organiser sa boîte mail",
      icon: "Inbox",
      blocks: [
        { type: "text", html: "Une boîte mail mal organisée devient vite une source de stress et de perte d'information. L'apprenant apprend à <strong>créer des dossiers ou libellés</strong>, à rechercher un message par mot-clé, expéditeur ou date, à supprimer les messages inutiles et à archiver les messages terminés. Il utilise aussi une <strong>signature</strong> simple contenant son nom, sa fonction et ses contacts professionnels." },
        { type: "keypoints", title: "Une boîte mail bien tenue", points: [
          "Créer des dossiers ou libellés pour classer les messages.",
          "Rechercher par mot-clé, expéditeur ou date.",
          "Supprimer les messages inutiles, archiver les messages terminés.",
          "Utiliser une signature professionnelle simple.",
        ] },
        { type: "callout", tone: "info", title: "L'e-mail n'est pas une armoire", text: "L'e-mail n'est pas un espace de stockage permanent. Les fichiers importants doivent être enregistrés dans un dossier local ou dans un cloud organisé. L'e-mail doit rester un outil de communication, non une armoire numérique désordonnée." },
      ],
    },
    {
      id: "seq-8",
      title: "Comprendre le cloud et le partage de fichiers",
      icon: "Cloud",
      blocks: [
        { type: "text", html: "Le <strong>cloud</strong> est un espace de stockage accessible par Internet. Il permet de conserver des fichiers en ligne, de les retrouver sur plusieurs appareils et de les partager. Les exemples courants sont Google Drive, OneDrive, Dropbox ou iCloud. On peut le comparer à une <strong>armoire numérique accessible à distance</strong>, avec des clés d'accès que l'on peut donner ou retirer." },
        { type: "text", html: "L'essentiel n'est pas seulement de déposer un fichier, mais de le déposer <strong>au bon endroit</strong>, de le <strong>nommer correctement</strong> et de choisir les <strong>droits d'accès appropriés</strong>." },
        { type: "infographic", kind: "categories", title: "Les trois droits d'accès courants", data: { columns: [
          { title: "Lecteur", accent: "#0891B2", items: [{ label: "Peut consulter" }, { label: "Ne peut pas modifier" }] },
          { title: "Commentateur", accent: "#6D5DF5", items: [{ label: "Peut consulter" }, { label: "Peut ajouter des remarques" }] },
          { title: "Éditeur", accent: "#D97706", items: [{ label: "Peut modifier le document" }, { label: "À donner seulement si nécessaire" }] },
        ] } },
        { type: "callout", tone: "warn", title: "Confidentialité avant tout", text: "Un lien partagé publiquement peut être transféré à d'autres personnes. Une erreur de partage peut exposer des données personnelles, des notes ou des documents administratifs. Le bon réflexe : partager uniquement avec les personnes concernées, limiter les droits, vérifier les accès et retirer le partage quand le besoin est terminé." },
      ],
    },
    {
      id: "seq-9",
      title: "Téléverser, télécharger et synchroniser",
      icon: "RefreshCw",
      blocks: [
        { type: "text", html: "Trois verbes que les débutants confondent souvent doivent être distingués clairement. <strong>Téléverser</strong>, c'est envoyer un fichier depuis son ordinateur vers un espace en ligne. <strong>Télécharger</strong>, c'est récupérer un fichier depuis Internet ou le cloud vers son ordinateur. <strong>Synchroniser</strong>, c'est maintenir une correspondance automatique entre un dossier local et un espace en ligne." },
        { type: "infographic", kind: "two-columns", title: "Téléverser ou télécharger ?", data: { left: { title: "Téléverser (envoyer)", subtitle: "ordinateur → en ligne", items: ["Déposer un devoir dans un dossier cloud", "Mettre une photo en ligne", "Ajouter une pièce jointe à un e-mail"] }, right: { title: "Télécharger (récupérer)", subtitle: "en ligne → ordinateur", items: ["Récupérer une ressource du formateur", "Enregistrer une pièce jointe reçue", "Sauvegarder un fichier du cloud en local"] } } },
        { type: "callout", tone: "warn", title: "Attention à la synchronisation", text: "Un fichier synchronisé supprimé localement peut parfois être supprimé en ligne, selon le service utilisé. La prudence consiste à lire les messages d'alerte avant de confirmer une suppression." },
      ],
    },
    {
      id: "seq-10",
      title: "Participer efficacement à une réunion en ligne",
      icon: "Video",
      blocks: [
        { type: "text", html: "La <strong>visioconférence</strong> est devenue un outil courant de formation, de réunion administrative et de collaboration. Elle exige des compétences à la fois <strong>techniques</strong> et <strong>relationnelles</strong>. Techniquement, il faut savoir rejoindre une réunion à partir d'un lien, autoriser le micro et la caméra, couper ou activer le micro, régler le volume, utiliser le chat, lever la main et partager son écran si nécessaire." },
        { type: "infographic", kind: "rules", title: "L'étiquette d'une réunion en ligne", data: { rules: [
          { icon: "Clock", title: "Connexion à l'heure", text: "Rejoindre la réunion ponctuellement, depuis un lieu calme." },
          { icon: "MicOff", title: "Couper le micro", text: "Désactiver le micro lorsqu'on ne parle pas, éviter les bruits de fond." },
          { icon: "Hand", title: "Demander la parole", text: "Lever la main, rester attentif, contribuer au bon moment." },
          { icon: "Lock", title: "Respecter la confidentialité", text: "Ne pas diffuser le lien à des personnes non invitées." },
        ] } },
        { type: "callout", tone: "warn", title: "Avant de partager son écran", text: "Le partage d'écran peut exposer des informations personnelles si des fichiers, onglets ou notifications restent visibles. Avant de partager, fermer les contenus inutiles." },
        { type: "callout", tone: "tip", text: "Une bonne participation ne signifie pas parler beaucoup : c'est être présent, attentif, audible, respectueux et capable de contribuer au moment opportun." },
      ],
    },
  ],
  exercises: [
    {
      id: "f1", kind: "categorize", title: "Navigateur, moteur ou site ?",
      instruction: "Classez chaque élément dans la bonne catégorie.",
      categories: ["Navigateur", "Moteur de recherche", "Site Web"],
      items: [
        { label: "Chrome", category: "Navigateur" },
        { label: "Firefox", category: "Navigateur" },
        { label: "Edge", category: "Navigateur" },
        { label: "Le service qui trouve des pages à partir de mots-clés", category: "Moteur de recherche" },
        { label: "L'espace consultable d'une université", category: "Site Web" },
        { label: "Le site officiel de l'UNESCO", category: "Site Web" },
      ],
      feedback: "Le navigateur (Chrome, Firefox, Edge) est le logiciel qui ouvre les pages ; le moteur de recherche est un service qui aide à trouver des pages ; le site Web est l'espace consultable d'une organisation.",
    },
    {
      id: "f2", kind: "order", title: "Une méthode de recherche",
      instruction: "Remettez dans l'ordre les quatre étapes d'une recherche efficace.",
      items: ["Définir le besoin", "Extraire les mots importants", "Choisir le type de source souhaité", "Comparer les résultats"],
      feedback: "On clarifie d'abord le besoin, on en extrait des mots-clés, on choisit le type de source visé, puis on compare les résultats sans retenir automatiquement le premier.",
    },
    {
      id: "f3", kind: "qcm", multiple: true, title: "Requêtes pertinentes",
      instruction: "Parmi ces requêtes, lesquelles sont les plus efficaces pour trouver une recommandation officielle sur les mots de passe ?",
      options: [
        { text: "mot de passe", correct: false },
        { text: "comment créer mot de passe solide", correct: true },
        { text: "mot de passe recommandations CNIL", correct: true },
        { text: "site:cnil.fr mots de passe recommandations", correct: true },
        { text: "je veux tout savoir sur la sécurité informatique en général", correct: false },
      ],
      feedback: "Une requête trop large (« mot de passe ») ou trop bavarde est peu efficace. De bons mots-clés, et surtout l'ajout d'une source reconnue (CNIL, site:cnil.fr), augmentent la pertinence des résultats.",
    },
    {
      id: "f4", kind: "categorize", title: "Fiable ou douteux ?",
      instruction: "Pour chaque indice rencontré sur une page Web, dites s'il renforce la fiabilité ou s'il s'agit d'un signal d'alerte.",
      categories: ["Indice de fiabilité", "Signal d'alerte"],
      items: [
        { label: "Auteur ou organisme clairement identifié", category: "Indice de fiabilité" },
        { label: "Date de publication récente et visible", category: "Indice de fiabilité" },
        { label: "Information confirmée par une autre source fiable", category: "Indice de fiabilité" },
        { label: "Titre sensationnaliste qui demande de partager vite", category: "Signal d'alerte" },
        { label: "Aucun auteur, aucune date", category: "Signal d'alerte" },
        { label: "Beaucoup de publicités et une image sans contexte", category: "Signal d'alerte" },
      ],
      feedback: "Auteur identifié, date visible et recoupement renforcent la fiabilité ; titre racoleur, absence d'auteur ou de date, surabondance de publicités et images hors contexte sont des signaux d'alerte.",
    },
    {
      id: "f5", kind: "match", title: "À, Cc, Cci",
      instruction: "Reliez chaque champ d'un e-mail à son usage.",
      pairs: [
        { left: "À", right: "Destinataires principaux, responsables de l'action" },
        { left: "Cc", right: "Personnes informées, en copie visible" },
        { left: "Cci", right: "Copie cachée aux autres destinataires" },
      ],
      feedback: "Le champ À désigne les destinataires principaux, Cc met des personnes en copie visible, et Cci envoie une copie cachée — à utiliser avec discernement et transparence.",
    },
    {
      id: "f6", kind: "order", title: "Vérifier une information",
      instruction: "Remettez dans l'ordre la procédure de vérification d'une information douteuse.",
      items: ["Lire au-delà du titre", "Identifier la source", "Chercher la date", "Rechercher l'information dans un autre média fiable", "Demander conseil en cas de doute"],
      feedback: "On lit le contenu, on identifie qui publie, on cherche la date, on recoupe avec une autre source fiable, et on demande conseil si le doute persiste.",
    },
    {
      id: "f7", kind: "match", title: "Les droits du cloud",
      instruction: "Associez chaque droit de partage à ce qu'il autorise.",
      pairs: [
        { left: "Lecteur", right: "Peut seulement consulter le document" },
        { left: "Commentateur", right: "Peut consulter et ajouter des remarques" },
        { left: "Éditeur", right: "Peut modifier le document" },
      ],
      feedback: "Le lecteur consulte, le commentateur ajoute des remarques, l'éditeur modifie. On donne le minimum de droits nécessaire à la mission.",
    },
    { id: "q1", kind: "qcm", title: "Ouvrir des pages Web", instruction: "Quel logiciel permet d'ouvrir des pages Web ?", options: [{ text: "Un navigateur", correct: true }, { text: "Un tableur", correct: false }, { text: "Une imprimante", correct: false }, { text: "Un antivirus", correct: false }], feedback: "Un navigateur affiche les pages Web et permet d'accéder aux sites." },
    { id: "q2", kind: "qcm", title: "Navigateur et moteur", instruction: "Quelle est la différence entre un navigateur et un moteur de recherche ?", options: [{ text: "Il n'y en a aucune", correct: false }, { text: "Le navigateur ouvre les pages, le moteur aide à trouver des pages", correct: true }, { text: "Le moteur remplace Internet", correct: false }, { text: "Le navigateur sert seulement à imprimer", correct: false }], feedback: "Le navigateur est le logiciel ; le moteur est un service de recherche." },
    { id: "q3", kind: "qcm", title: "La requête la plus précise", instruction: "Quelle requête est la plus précise pour trouver un document officiel sur l'IA à l'UNESCO ?", options: [{ text: "IA", correct: false }, { text: "tout sur IA", correct: false }, { text: "site:unesco.org intelligence artificielle éducation", correct: true }, { text: "intelligence", correct: false }], feedback: "La commande site: cible le domaine UNESCO et les mots-clés précisent le sujet." },
    { id: "q4", kind: "qcm", title: "Évaluer une source", instruction: "Quel critère est essentiel pour évaluer une source ?", options: [{ text: "La couleur de la page", correct: false }, { text: "L'auteur, la date et les preuves", correct: true }, { text: "Le nombre d'images", correct: false }, { text: "La longueur du titre", correct: false }], feedback: "La fiabilité dépend notamment de l'identification de la source, de son actualité et des éléments de preuve." },
    { id: "q5", kind: "truefalse", title: "Information partagée", instruction: "Vrai ou faux ?", statement: "Une information très partagée est toujours vraie.", answer: false, feedback: "Faux : la popularité ne prouve pas l'exactitude. Il faut vérifier et recouper." },
    { id: "q6", kind: "qcm", title: "L'objet d'un e-mail", instruction: "Dans un e-mail professionnel, l'objet doit être :", options: [{ text: "Vide", correct: false }, { text: "Très vague", correct: false }, { text: "Clair et explicite", correct: true }, { text: "Remplacé par une pièce jointe", correct: false }], feedback: "L'objet aide le destinataire à comprendre rapidement le sujet avant d'ouvrir le message." },
    { id: "q7", kind: "qcm", title: "Le champ Cc", instruction: "Le champ Cc sert à :", options: [{ text: "Mettre les destinataires principaux", correct: false }, { text: "Informer des personnes en copie", correct: true }, { text: "Cacher tous les destinataires", correct: false }, { text: "Supprimer une pièce jointe", correct: false }], feedback: "Cc signifie copie conforme : les destinataires sont visibles de tous." },
    { id: "q8", kind: "qcm", title: "Le champ Cci", instruction: "Le champ Cci permet :", options: [{ text: "D'envoyer une copie invisible aux autres destinataires", correct: true }, { text: "De chiffrer automatiquement les fichiers", correct: false }, { text: "De bloquer le message", correct: false }, { text: "De créer un dossier cloud", correct: false }], feedback: "Cci signifie copie cachée ; il doit être utilisé avec discernement." },
    { id: "q9", kind: "qcm", title: "Avant la pièce jointe", instruction: "Avant d'envoyer une pièce jointe, il faut vérifier :", options: [{ text: "Son nom, son format, sa taille et son contenu", correct: true }, { text: "Uniquement sa couleur", correct: false }, { text: "Uniquement le jour de la semaine", correct: false }, { text: "Rien", correct: false }], feedback: "Une pièce jointe incorrecte peut créer une confusion ou exposer une information sensible." },
    { id: "q10", kind: "qcm", title: "Format d'un document finalisé", instruction: "Quel format est souvent adapté à un document finalisé à transmettre ?", options: [{ text: ".pdf", correct: true }, { text: ".tmp", correct: false }, { text: ".exe", correct: false }, { text: ".bat", correct: false }], feedback: "Le PDF préserve la mise en forme et convient à la lecture ou à l'impression." },
    { id: "q11", kind: "qcm", title: "Téléverser", instruction: "Téléverser signifie :", options: [{ text: "Envoyer un fichier vers un espace en ligne", correct: true }, { text: "Supprimer un message", correct: false }, { text: "Éteindre le navigateur", correct: false }, { text: "Allumer le micro", correct: false }], feedback: "Téléverser, c'est envoyer un fichier local vers Internet ou le cloud." },
    { id: "q12", kind: "qcm", title: "Télécharger", instruction: "Télécharger signifie :", options: [{ text: "Récupérer un fichier depuis Internet ou le cloud", correct: true }, { text: "Envoyer un e-mail sans objet", correct: false }, { text: "Partager son mot de passe", correct: false }, { text: "Créer un mot de passe", correct: false }], feedback: "Télécharger, c'est récupérer un fichier vers son appareil." },
    { id: "q13", kind: "qcm", title: "Droit de modification", instruction: "Quel droit cloud convient pour permettre à quelqu'un de modifier un document ?", options: [{ text: "Lecteur", correct: false }, { text: "Éditeur", correct: true }, { text: "Spectateur sans accès", correct: false }, { text: "Aucun droit", correct: false }], feedback: "Le droit éditeur autorise la modification ; il ne doit être donné que si nécessaire." },
    { id: "q14", kind: "qcm", title: "Lien de partage public", instruction: "Quel est le risque d'un lien de partage public ?", options: [{ text: "Il peut être transmis à des personnes non prévues", correct: true }, { text: "Il améliore toujours la sécurité", correct: false }, { text: "Il supprime le fichier", correct: false }, { text: "Il bloque Internet", correct: false }], feedback: "Un lien public peut circuler largement : les droits doivent être limités." },
    { id: "q15", kind: "truefalse", title: "Micro en réunion", instruction: "Vrai ou faux ?", statement: "Dans une réunion en ligne, il est recommandé de couper son micro quand on ne parle pas.", answer: true, feedback: "Vrai : cela réduit les bruits de fond et facilite l'écoute de tous." },
    { id: "q16", kind: "qcm", title: "Avant de partager l'écran", instruction: "Avant de partager son écran, il faut :", options: [{ text: "Fermer les documents et onglets personnels ou inutiles", correct: true }, { text: "Ouvrir tous ses messages", correct: false }, { text: "Afficher ses mots de passe", correct: false }, { text: "Désactiver Internet", correct: false }], feedback: "Le partage d'écran peut exposer des informations confidentielles : on ferme les contenus inutiles." },
    { id: "q17", kind: "qcm", title: "E-mail demandant un mot de passe", instruction: "Un e-mail demandant votre mot de passe doit être considéré comme :", options: [{ text: "Normal", correct: false }, { text: "Suspect", correct: true }, { text: "Obligatoire", correct: false }, { text: "Sans importance", correct: false }], feedback: "Suspect : les mots de passe ne doivent jamais être transmis par e-mail." },
    { id: "q18", kind: "qcm", title: "Bonne pratique cloud", instruction: "Une bonne pratique de cloud consiste à :", options: [{ text: "Donner le droit éditeur à tout le monde", correct: false }, { text: "Nommer et classer les fichiers", correct: true }, { text: "Partager tous les liens publiquement", correct: false }, { text: "Supprimer les dossiers", correct: false }], feedback: "Le classement et le nommage facilitent le travail collaboratif." },
  ],
  caseStudy: {
    title: "Étude de cas — La note de veille de Kouassi",
    scenario:
      "Kouassi doit préparer une courte note de veille pour son service sur un sujet numérique. Pressé, il tape « tout sur le sujet » dans le navigateur et retient la première page trouvée : un article au titre accrocheur, sans auteur ni date, entouré de publicités, qui demande de partager rapidement. Il rédige ensuite un e-mail au formateur avec l'objet « salut » et le message « bjr je vous envoie le truc demandé. merci ». Il dépose enfin sa fiche dans un dossier cloud qu'il partage publiquement avec un droit d'édition pour tout le monde.",
    questions: [
      "Identifiez les erreurs commises par Kouassi (recherche, source, e-mail, cloud).",
      "Proposez une meilleure requête de recherche pour ce sujet.",
      "Réécrivez correctement l'objet et le message de l'e-mail.",
      "Indiquez comment Kouassi aurait dû partager son dossier cloud.",
    ],
    corrige: [
      "Erreurs : requête trop vague ; source non fiable (sans auteur ni date, publicités, appel au partage urgent) sans recoupement ; e-mail à objet vague et message peu professionnel sans pièce jointe annoncée ; partage public avec droit d'édition pour tous (risque de confidentialité).",
      "Meilleure requête : des mots-clés précis et, si possible, une source institutionnelle, par exemple « créer mot de passe solide recommandations CNIL » ou « site:cnil.fr mots de passe recommandations ».",
      "Objet : « Transmission de la fiche de veille — Module N1-M5 ». Message : « Bonjour Monsieur/Madame, veuillez trouver ci-joint la fiche de veille réalisée dans le cadre du module N1-M5. Je reste disponible pour toute précision. Cordialement, Kouassi — Nom et prénom. » avec la pièce jointe nommée Fiche_Source_N1M5_Kouassi.pdf.",
      "Partage : créer un dossier nommé N1_M5_Kouassi, y déposer la fiche, puis partager uniquement avec le formateur en droit lecteur (ou commentateur selon la consigne), et retirer l'accès lorsque le besoin est terminé — jamais un lien public en édition.",
    ],
  },
};
